### ISSUE TITLE
Remove range fan tools from Range Cards toolbox

### ISSUE THREAD

**Issue by mfunk** [Esri/solutions-geoprocessing-toolbox#104]
Parameters have changed for the Range Fan By Bearing and Traversal, and Range Fan By Bearing Limits tools so the tool tests have to be modified to make them run again. The tool test affected are:

- [x] TestRangeFanByBearingLimits.py
- [x] TestRangeFanByBearingAndTraversal.py

**Comment by mfunk** [comment]
@nfeuerstein @jrweakland So this is another case where we had several early templates that shared common tools. So we duplicated the tools among the toolboxes as needed. Unfortunately this means if changes are updated in one place, they must be made in all of the other copied locations as well. Double that for Desktop and Pro templates and this becomes crappy management task. Since we already maintain these tools in the Visibility and Range template(s) I think we should remove the **Range Fans From Bearing And Traversal** and **Range Fans From Bearing Limits** in this toolbox. For Pro projects/packages we can include both toolboxes. Thoughts?

**Comment by nfeuerstein** [comment]
@mfunk, barring objections from @jrweakland, I agree with you.  We should only maintain the tools in the Visibility and Range toolbox, in github.

**Comment by mfunk** [comment]
@jrweakland @nfeuerstein A long time in coming, but i'm going to rename this task to remove range fan tools from the range cards toolbox and add to Asana. The task will have additional subtasks to add documentation to use the Visibility and Range template to build range fans.
