### ISSUE TITLE
Weird ArcInfo dialog with Position Analysis tools

### ISSUE THREAD

**Issue by mfunk** [Esri/solutions-geoprocessing-toolbox#109]
Got a weird one with the Position Analysis Tools.tbx. When you open one of the tools (e.g. Locate Events) you get a "New ArcInfo Workspace" dialog box before the tool dialog.
![image](https://cloud.githubusercontent.com/assets/3093182/4276222/8367989c-3d03-11e4-9081-1bdf25f7907d.png)
Clicking Cancel eventually makes the ArcInfo dialog go away and the correct tool dialog appears.

This MIGHT have something to do with some of the intermediate or output data paths pointing to %scratchworkspace%, instead of %scratchGDB%, or %scratchFolder%.

**Comment by nsm91** [comment]
I also found that if you just fill in the workspace parameter in the model it prevents the prompt from appearing. Whatever workspace is defined will be pre-auto-filled as the parameter for that model, but users will still have the option to change it before they run it.
