### ISSUE TITLE
MAoT Concealment from Aerial Detection: Add buildings to definition query for output

### ISSUE THREAD

**Issue by erikreid** [Esri/solutions-geoprocessing-toolbox#117]
Add buildings to the definition query for concealment vs just vegetation.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/129342386639048/129344613496942)

**Comment by mfunk** [comment]
@erikreid I'm looking at the Concealment tool but i'm not seeing where the buildings are used as input into the tool. Right now the tool accepts:
1. Input Area of Interest
2. Input Combined Vegetation Coverage
3. Output Concealment
4. Spatial Reference (optional)

![image](https://cloud.githubusercontent.com/assets/3093182/6374414/95ee98fc-bcc5-11e4-970c-7803761da0d1.png)

I checked for updates to **Generate Intermediate Layers** but don't see the UTDS StructuresSrf added to it. Unfortunately I don't have any way of testing this one.

**Comment by erikreid** [comment]
The concealment tool bases its analysis on the F-Code, which are pulled from the intermediate layer generation. You are correct that the Generate Intermediate Layers do not take StructureSrf into account. Other tools within the MAoT toolbox do use that layer because they pull directly from the TDS dataset. So we can either adjust Concealment to pull in those additional layers, or adjust the Generate Intermediate Layers script to pull in the StructureSrf while processing. This brings up two concerns: 1) If we adjust the Generate Intermediate Layers to take StructureSrf into account, do we adjust all of the other tools to avoid feature duplication or 2)  Include the ability to add additional features when running the analysis. Either way it will take some time to make the adjustments.

**Comment by mfunk** [comment]
Perhaps we need to start thinking about another configuration tool for buildings, say a *Buildings and Structures* layer. Again there are different types of structures spread across UTDS datasets (eg. BARN is under AGRICULTURE and CASTLE is under MILITARY). With that we can then add an option to the tool to include this layer, just as we did for *Combined Vegetation Coverage*. That sound like a useful idea?

**Comment by jrweakland** [comment]
@erikreid - please take a look at this when you get back tot he solutions division.

**Comment by mfunk** [comment]
@jrweakland Hey JRW any idea where Erik left this one? You still have something in your backlog?

**Comment by mfunk** [comment]
@jrweakland is this one still valid? If so I will keep it around, if not please close it out. Thanks.

**Comment by lfunkhouser** [comment]
The Military Aspects of Terrain tools will not be enhanced. Last supported version was 10.1. These tools are retired as of the April 2018 release. Future work is planned for environmental impacts on operations, release date TBD.
