### ISSUE TITLE
MAoT: Find Local Peaks Error 999999 and warning error 000950

### ISSUE THREAD

**Issue by erikreid** [Esri/solutions-geoprocessing-toolbox#119]
Ran the tool using services and received error 999999 and warning error 000950. Could be due to the version of the template vs current services. 

![find local peaks error message](https://cloud.githubusercontent.com/assets/8561343/4312783/bf25aba0-3ebe-11e4-8241-84d754e17f9f.png)

**Comment by mfunk** [comment]
Tested with AGOL Terrain service and tool works well..

```
Executing: FindLocalPeaks62 AOI 5 Terrain C:\Workspace\Test\TestForErikReid\aTarget.gdb\mfLP0001
Start Time: Mon Feb 23 10:50:47 2015
Executing (Clip): Clip Terrain "7822639.36631812 4087454.43754038 7839268.91146099 
...
...
Executing (Copy Features): CopyFeatures peaks_sorted_Layer C:\Workspace\Test\TestForErikReid\aTarget.gdb\mfLP0001 # 0 0 0
Start Time: Mon Feb 23 11:01:48 2015
Succeeded at Mon Feb 23 11:01:48 2015 (Elapsed Time: 0.51 seconds)
Succeeded at Mon Feb 23 11:01:49 2015 (Elapsed Time: 11 minutes 2 seconds)
```

![image](https://cloud.githubusercontent.com/assets/3093182/6334849/1273fb86-bb4c-11e4-8c4c-87c3396b148e.png)
