### ISSUE TITLE
MAoT Vegetation Query for HLZ and DZ

### ISSUE THREAD

**Issue by erikreid** [Esri/solutions-geoprocessing-toolbox#128]
The queries within the model do not match the requirements for HLZ's and DZ in accordance with FM 5-33. Need to be adjusted to ensure the end user has the correct output. Reference FM 5-33 7-11.

**Comment by mfunk** [comment]
Suitable Drop Zones:

![image](https://cloud.githubusercontent.com/assets/3093182/6374090/87331fb0-bcc3-11e4-9b9b-5f9ea82172e9.png)


Hasty HLZ Analysis:

![image](https://cloud.githubusercontent.com/assets/3093182/6374277/bb734d44-bcc4-11e4-8b9d-79f3ee4bdba9.png)

With our limited set of vegetation data I cannot tell if this works well enough or not. It produced results that would seem acceptable with what we have.
