### ISSUE TITLE
MAoT HLZ Suitability Received Errors 999999, 010213, 010325 and 010067.

### ISSUE THREAD

**Issue by erikreid** [Esri/solutions-geoprocessing-toolbox#129]
Ran the HLZ Suitability tool with services and received errors 999999, 010213, 010325 and 010067. Could be due to the version difference between the template and current software/service build.

Error 99999 General fault error

Error 010325 Run-time error - *** "The tool or method encountered an error during execution. This is a general response that may be used for many possible error conditions or where a specific cause could not be trapped"

Error 010213 Error in reading grid "There was an error encountered when trying to read the specified grid. Problems accessing a grid are most commonly the result of missing required component files in the grid's folder. Consult the documentation to see the required files for the ESRI Grid format. If all of the required components are present, it is also possible that the files that contain the binary raster data are internally corrupted"

Error 010067 Error in executing grid expression " There was a problem executing the map algebra expression"

![hlz suitability error messages](https://cloud.githubusercontent.com/assets/8561343/4327538/0e9aafda-3f7a-11e4-8a2d-19e570e65310.png)

**Comment by mfunk** [comment]
Since **Suitable HLZs** no longer exists in the repo this is for **Deliberate HLZ Analysis** and **Hasty HLZ Analysis**.

For **Deliberate HLZ Analysis**:
* [ ] Parameter "UTDS Feature Set" is not a Feature Set but a Feature Dataset and should be renamed as such.
* [ ] After almost 4 hours of running the tool failed with...
```
Executing (Generate Linear Obstacle Layer for HLZ): GenerateLinearObstacleLayerforHLZ \\afmiedev\DBConnections\UTDS.sde\utds.sde.UTDS "C:\Workspace\ArcGIS Defense Templates\Military_Aspects_of_Terrain_for_ArcGIS_10_1\Maps\Toolbox\scratch\scratch.gdb" "C:\Workspace\ArcGIS Defense Templates\Military_Aspects_of_Terrain_for_ArcGIS_10_1\Maps\Toolbox\scratch\scratch.gdb\CulturePnt_GenerateLinearObs"
Start Time: Tue Jan 20 12:35:29 2015
ERROR 000576: Script associated with this tool does not exist.
Failed to execute (Generate Linear Obstacle Layer for HLZ).
Failed at Tue Jan 20 12:35:30 2015 (Elapsed Time: 0.19 seconds)
Failed to execute (SuitableHLZs2).
Failed at Tue Jan 20 12:35:32 2015 (Elapsed Time: 3 hours 54 minutes 15 seconds)
```
I also found a few others like this too, such as Generate Point Obstacle for HLZ points to *C:\Users\matt2542\Documents\Users\erik0000\Desktop\solutions-geoprocessing-toolbox-master\suitability\toolboxes\scripts\GenerateIHLZPointObstacles.py* which is a folder that does NOT exist.

more to come as testing continues ...

**Comment by mfunk** [comment]
Actually that's it for **Deliberate HLZ Analysis**. Continued for a few hours then completed successfully...
```
Executing: SuitableHLZs2 OtherAOI Slope_Elevat1 "Combined Vegetation Coverage" \\afmiedev\DBConnections\UTDS.sde\utds.sde.UTDS C:\Workspace\Personal_Docs\PSU_GEOINT_Certificate\GEOG_883_Remote_Sensing\Final_Project\default.gdb\mfDelHLZ0001 #
Start Time: Tue Jan 20 12:47:04 2015
Executing (Copy Features (2)): CopyFeatures OtherAOI "C:\Workspace\ArcGIS Defense Templates\Military_Aspects_of_Terrain_for_ArcGIS_10_1\Maps\Toolbox\scratch\scratch.gdb\AOI" # 0 0 0
Start Time: Tue Jan 20 12:47:05 2015
Succeeded at Tue Jan 20 12:47:06 2015 (Elapsed Time: 0.39 seconds)
Executing (Extract by Mask): ExtractByMask Slope_Elevat1 "C:\Workspace\ArcGIS Defense Templates\Military_Aspects_of_Terrain_for_ArcGIS_10_1\Maps\Toolbox\scratch\scratch.gdb\AOI" "C:\Workspace\ArcGIS Defense Templates\Military_Aspects_of_Terrain_for_ArcGIS_10_1\Maps\Toolbox\scratch\scratch.gdb\clippe
...
...
Sorting Attributes...
Dissolving...
Succeeded at Tue Jan 20 17:16:53 2015 (Elapsed Time: 10 minutes 54 seconds)
Succeeded at Tue Jan 20 17:17:00 2015 (Elapsed Time: 4 hours 29 minutes 53 seconds)
```

Continuing testing with **Hasty HLZ Analysis**...

**Comment by erikreid** [comment]
Yea the dissolve took too long due to a setting. The adjustments have been made.

**Comment by mfunk** [comment]
OK. Need to check **Hasty HLZ Analysis** because it also took some time to run..
```
Executing: HastyHLZAnalysis OtherAOI Slope_Elevat1 "Combined Vegetation Coverage" C:\Users\matt2542\Documents\ArcGIS\Default.gdb\mfHastHLZ0001
Start Time: Wed Jan 21 07:23:46 2015
Executing (Copy Features (2)): CopyFeatures OtherAOI "C:\Workspace\ArcGIS Defense Templates\Military_Aspects_of_Terrain_for_ArcGIS_10_1\Maps\Toolbox\scratch\scratch.gdb\AOI" # 0 0 0
Start Time: Wed Jan 21 07:23:48 2015
...
...
Executing (Dissolve): Dissolve "C:\Workspace\ArcGIS Defense Templates\Military_Aspects_of_Terrain_for_ArcGIS_10_1\Maps\Toolbox\scratch\scratch.gdb\HLZUnion_Project" C:\Users\matt2542\Documents\ArcGIS\Default.gdb\mfHastHLZ0001 HLZ_Suitability # MULTI_PART DISSOLVE_LINES
Start Time: Wed Jan 21 07:59:29 2015
Sorting Attributes...
Dissolving...
Succeeded at Wed Jan 21 09:06:32 2015 (Elapsed Time: 1 hours 7 minutes 2 seconds)
Succeeded at Wed Jan 21 09:06:35 2015 (Elapsed Time: 1 hours 42 minutes 49 seconds)
```

**Comment by mfunk** [comment]
Tested this with AGOL service data and works just fine.

```
Executing: HastyHLZAnalysis AOI "Pct Slope (AGOL)" CombinedVegetationCoverage C:\Workspace\Test\TestForErikReid\aTarget.gdb\mfHHZ0001
Start Time: Wed Feb 25 07:18:27 2015
Executing (Copy Features (2)): CopyFeatures AOI C:\Workspace\Test\TestForErikReid\scratch.gdb\AOI # 0 0 0
Start Time: Wed Feb 25 07:18:28 2015
Succeeded at Wed Feb 25 07:18:29 2015 (Elapsed Time: 0.94 seconds)
Executing (Extract by Mask): ExtractByMask "Pct Slope (AGOL)" 
...
...
...
Succeeded at Wed Feb 25 07:22:09 2015 (Elapsed Time: 2.19 seconds)
Executing (Dissolve): Dissolve C:\Workspace\Test\TestForErikReid\scratch.gdb\HLZUnion_Project C:\Workspace\Test\TestForErikReid\aTarget.gdb\mfHHZ0001 HLZ_Suitability # SINGLE_PART DISSOLVE_LINES
Start Time: Wed Feb 25 07:22:09 2015
Sorting Attributes...
Dissolving...
Succeeded at Wed Feb 25 07:22:11 2015 (Elapsed Time: 2.21 seconds)
Succeeded at Wed Feb 25 07:22:12 2015 (Elapsed Time: 3 minutes 45 seconds)
```

![image](https://cloud.githubusercontent.com/assets/3093182/6373390/399e4b2a-bcbf-11e4-8723-8bd809eedf1d.png)
