### ISSUE TITLE
Add Mobility Corridor for Air 

### ISSUE THREAD

**Issue by erikreid** [Esri/solutions-geoprocessing-toolbox#131]
Add the ability to produce Aerial Mobility Corridor to the MAoT toolset and/or HLZ Suitability tool.  This will further aid in planing Aerial operations. This can effect planning for Drop Zones or HLZs.

**Comment by mfunk** [comment]
@jrweakland @erikreid guess we need to add this to Asana now.

**Comment by jrweakland** [comment]
@erikreid Do we have the criteria for the air mobility corridor in a military publication that we can reference?
