### ISSUE TITLE
Validation error in Radial Line of Sight and Range

### ISSUE THREAD

**Issue by dfoll** [Esri/solutions-geoprocessing-toolbox#136]
Open up the tool, and there is immediately a validation error

![image](https://cloud.githubusercontent.com/assets/5322669/4653313/cacfb190-54ac-11e4-84dd-9237e052d89f.png)

```
ERROR 
updateParameters Execution Error: Runtime error Traceback (most recent call last): File
"D:\Work\10201update\AFM-VisibilityAndRangeTemplate_10.2.0.1\toolboxes\Visibility and Range
 Tools.tbx#TowerRangeandLineofSight2_VandR.UpdateParameters.py", line 4, in File 
"D:\Work\10201update\AFM-VisibilityAndRangeTemplate_10.2.0.1\toolboxes\Visibility and Range
Tools.tbx#TowerRangeandLineofSight2_VandR.UpdateParameters.py", line 53, in updateParameters 
AttributeError: 'NoneType' object has no attribute 'getValue' 
```

**Comment by mfunk** [comment]
@nfeuerstein Checking back in on this one, we still need this released for 10.2.2? Any chance we can do a one-off toolbox for a template rather than a 1.0.3 release for the whole repo?

**Comment by nfeuerstein** [comment]
@mfunk Yes, I don't think we want to do an entire release of the repo to fix this.  We should just release the template with working tools at the correct versions.  This should be addressed during the stand down.

**Comment by mfunk** [comment]
@nfeuerstein Is this one still and issue with the 2.0.0 release done already?

**Comment by nfeuerstein** [comment]
@dfoll - could you answer @mfunk question?

**Comment by mfunk** [comment]
@dfoll @nfeuerstein Since it's been a few months I'm going to close this issue. If it's still a problem, please log a new issue.
