### ISSUE TITLE
Remove Range Rings from Coordinate and Conversion (Position Analysis) Tools

### ISSUE THREAD

**Issue by mfunk** [Esri/solutions-geoprocessing-toolbox#139]
Remove __Range Rings__ from Coordinate and Conversion (Position Analysis) Tools. Should only be maintained by Visibility and Range.

**Comment by mfunk** [comment]
@nfeuerstein @conklinbd @jrweakland  With the recent interest in Coordinate and Conversion template from customers I'm not certain we should remove this. It is still a duplication of tools (maintained in Visibility and Range Tools). What do you think?

**Comment by nfeuerstein** [comment]
I think its fine, and makes sense in the long run.  At the present time, the interested customers are on 10.2 - so we have a while to clearly communicate the changes before they get their hands on this version anyways.

**Comment by mfunk** [comment]
Fixed in commit #196
