### ISSUE TITLE
Radial Line of Sight and Range has no output parameter

### ISSUE THREAD

**Issue by mfunk** [Esri/solutions-geoprocessing-toolbox#145]
Radial Line of Sight and Range has no output parameter

![image](https://cloud.githubusercontent.com/assets/3093182/4957974/c01cfba4-66a9-11e4-86b1-2e6842bc841c.png)

**Comment by mfunk** [comment]
@nfeuerstein this is the one that we wanted to completely redo from scratch. That not the case anymore?

**Comment by nfeuerstein** [comment]
Still the case, I just assigned it to you because I know you'll resolve the issue when you rebuild the tool.

**Comment by mfunk** [comment]
Added an output "Out Features" parameter at index 19 in TowerRangeFans.py for Radial Line of Sight and Range - Single Tower:

![image](https://cloud.githubusercontent.com/assets/3093182/11721812/89abe242-9f1a-11e5-9208-0aa7aa7bcb39.png)
