### ISSUE TITLE
Analyze Tools for Pro - Clearing Operations Toolbox Results

### ISSUE THREAD

**Issue by joebayles** [Esri/solutions-geoprocessing-toolbox#152]
@mfunk, I ran this tool in holistic because I was throwing a lot of errors trying to migrate Clearing Operations to Pro. I don't know if you want this or not, I saw you have a lot of #TODO's, but figured I'd capture it somewhere.

 
<code>Parameters
Input	C:\Users\htlab\Documents\ArcGIS\Projects\ClearingOperations\ClearingOperations.tbx
Output File	
 
<code>Messages
Start Time: Fri Nov 14 15:48:39 2014
 WARNING 001683: Found Python 2 to 3 errors: Line 164:             raise Exception, "Shape type {0} is not supported".format(shpType) ->             raise Exception("Shape type {0} is not supported".format(shpType))
Line 180:     except MsgError, xmsg: ->     except MsgError as xmsg:
Line 189:     except Exception, xmsg: ->     except Exception as xmsg:" within script tool CanvasAreaGRGScript_ClearingOperations(C:\Users\htlab\Documents\ArcGIS\ProjectTemplates\Clearing Operations\toolboxes\Scripts\CanvasAreaGRG.py)
 WARNING 001678: Found REMOVED Python method RefreshActiveView" within script tool NumberFeatures222_ClearingOperations(C:\Users\htlab\Documents\ArcGIS\ProjectTemplates\Clearing Operations\toolboxes\Scripts\NumberFeatures.py@16)
 WARNING 001678: Found REMOVED Python method mapping.ListLayers" within script tool NumberFeatures222_ClearingOperations(C:\Users\htlab\Documents\ArcGIS\ProjectTemplates\Clearing Operations\toolboxes\Scripts\NumberFeatures.py@19)
 WARNING 001678: Found REMOVED Python method mapping.MapDocument" within script tool NumberFeatures222_ClearingOperations(C:\Users\htlab\Documents\ArcGIS\ProjectTemplates\Clearing Operations\toolboxes\Scripts\NumberFeatures.py@27)
 WARNING 001678: Found REMOVED Python method mapping.ListDataFrames" within script tool NumberFeatures222_ClearingOperations(C:\Users\htlab\Documents\ArcGIS\ProjectTemplates\Clearing Operations\toolboxes\Scripts\NumberFeatures.py@28)
 WARNING 001678: Found REMOVED Python method mapping.ListLayers" within script tool NumberFeatures222_ClearingOperations(C:\Users\htlab\Documents\ArcGIS\ProjectTemplates\Clearing Operations\toolboxes\Scripts\NumberFeatures.py@32)
 WARNING 001678: Found REMOVED Python method mapping.Layer" within script tool NumberFeatures222_ClearingOperations(C:\Users\htlab\Documents\ArcGIS\ProjectTemplates\Clearing Operations\toolboxes\Scripts\NumberFeatures.py@75)
 WARNING 001678: Found REMOVED Python method mapping.AddLayer" within script tool NumberFeatures222_ClearingOperations(C:\Users\htlab\Documents\ArcGIS\ProjectTemplates\Clearing Operations\toolboxes\Scripts\NumberFeatures.py@76)
 WARNING 001678: Found REMOVED Python method mapping.Layer" within script tool NumberFeatures222_ClearingOperations(C:\Users\htlab\Documents\ArcGIS\ProjectTemplates\Clearing Operations\toolboxes\Scripts\NumberFeatures.py@79)
 WARNING 001678: Found REMOVED Python method mapping.AddLayer" within script tool NumberFeatures222_ClearingOperations(C:\Users\htlab\Documents\ArcGIS\ProjectTemplates\Clearing Operations\toolboxes\Scripts\NumberFeatures.py@80)
 WARNING 001683: Found Python 2 to 3 errors: Line 179:             raise Exception, "Shape type {0} is not supported".format(shpType) ->             raise Exception("Shape type {0} is not supported".format(shpType))
Line 195:     except MsgError, xmsg: ->     except MsgError as xmsg:
Line 204:     except Exception, xmsg: ->     except Exception as xmsg:" within script tool CanvasAreaGRGScript2_ClearingOperations(C:\Users\htlab\Documents\ArcGIS\ProjectTemplates\Clearing Operations\toolboxes\Scripts\PointTargetGRG.py)
 WARNING 001683: Found Python 2 to 3 errors: Line 263:     print msgs ->     print(msgs)
Line 280:     print pymsg + "\n" ->     print(pymsg + "\n")
Line 281:     print msgs ->     print(msgs)" within script tool sourceRLOSscript_ClearingOperations(C:\Users\htlab\Documents\ArcGIS\ProjectTemplates\Clearing Operations\toolboxes\Scripts\RLOS.py)
Succeeded at Fri Nov 14 15:48:42 2014 (Elapsed Time: 3.18 seconds)<code>

:octocat: Octocat says enjoy!

**Comment by mfunk** [comment]
@joebayles (and @rbernstein ) OK Janette has updated all of the arcpy.mp issues for the scripts in this toolbox. I need you to check it out and make sure this issue is fixed.

**Comment by joebayles** [comment]
Verified. :+1: 
Thanks @jscott11 and @mfunk!
