### ISSUE TITLE
Results from Hasty HLZ Model includes open water in acceptable areas

### ISSUE THREAD

**Issue by jrweakland** [Esri/solutions-geoprocessing-toolbox#187]
![hastyhlz](https://cloud.githubusercontent.com/assets/5739155/5740968/01284b42-9bbd-11e4-8782-42dc04f813dd.png)

![hastyhlzwater](https://cloud.githubusercontent.com/assets/5739155/5740971/085857cc-9bbd-11e4-8e4a-7b731d22ecc0.png)

After running the Hasty HLZ Model I noticed that open water was included in the final output as an acceptable area to land a helicopter. Upon further investigation I notice that many areas of the Hydrography Surface feature class were also included as acceptable areas. The model needs to be reviewed for accuracy in the selection of acceptable and acceptable with caution areas.

**Comment by joebayles** [comment]
http://en.wikipedia.org/wiki/Amphibious_helicopter

![amphibioushelicopter](http://upload.wikimedia.org/wikipedia/commons/thumb/6/61/HH-3F_Pelican_on_the_water_with_a_burning_boat.jpg/250px-HH-3F_Pelican_on_the_water_with_a_burning_boat.jpg)

**Comment by conklinbd** [comment]
:+1:

**Comment by erikreid** [comment]
Sigh

**Comment by erikreid** [comment]
Already fixed. closed out.

**Comment by jrweakland** [comment]
@erikreid - can you provide a screen capture of the results from running the fixed tool?

**Comment by erikreid** [comment]
![hasty hlz results](https://cloud.githubusercontent.com/assets/8561343/8629927/0edfee32-2715-11e5-8b97-bc7120a3ce23.png)

**Comment by jrweakland** [comment]
@erikreid - looks good from this view. Have you done a visual swipe analysis to ensure the results are legit?
