### ISSUE TITLE
In Memory Feature Sets in ArcGIS Pro

### ISSUE THREAD

**Issue by joebayles** [Esri/solutions-geoprocessing-toolbox#190]
Several tools in this repository use *In Memory Feature Sets* to input parameters, like in the picture below.
![image](https://cloud.githubusercontent.com/assets/5016557/5768941/5f3373d4-9cca-11e4-96a3-eb31506d9193.png)

While this works great in ArcMap, currently this capability has not been implemented in ArcGIS Pro.

So, my question is: **Can/Should we remove the default** ```in_memory\feature_set``` **from these tools in the ArcGIS Pro toolboxes?**

After talking with @mfunk about the Pro team's decision making process in regards to implementing this capability, I think it best that we come up with a standard workaround. It seems to me there are three options:

1. Leave it blank / Have the user add their own data - Definitely the easiest of the three, but goes against the "spirit" of having the in memory feature sets at all. Plus, even if we add another default value here, they can always choose to Browse...
2. Default to another layer / Have the user create that data in a previous step - The step I'm inclined to choose. Create a step that directs the user to digitize the feature for use in a subsequent step (i.e. "Sketch the area of operations. This will be used later to ____."). Have the geoprocessing tool default to that layer, and it still has the option for the user to browse to and add their own data.
3. Have the user use Map Notes - This is what was suggested to me as an option, but it is unnecessarily difficult and defeats the purpose in my opinion. Map notes, when it comes to being used as a parameter in a geoprocessing tool, are just like any other feature class, and therefore we might as well use something specific.

**Comment by conklinbd** [comment]
I vote for option 2. We can use Map Notes as the source for 2 if it helps but either way, the choice should be deliberate.

**Comment by mfunk** [comment]
Let me talk with a few people on the GP team and see what they suggest. I'd rather not decide now, wait a day or two until I can talk with them, instead of having to rebuild the tools inputs twice.

**Comment by joebayles** [comment]
That's what I was hoping you'd say!

**Comment by mfunk** [comment]
Some changes to Pro 1.1 will address this, not directly, but in a pleasantly unexpected way. Can't really say more now. Sorry. :)
