### ISSUE TITLE
Clearing Operations tools - lyrx file not properly being represented in Model output

### ISSUE THREAD

**Issue by ScottCecilio** [Esri/solutions-geoprocessing-toolbox#205]
Layer symbology is not being properly displayed with ArcGIS Pro project. The model does utilize the lyrx but does not display labelling or maintain the symbology for the labels once turned on.  The tools also finished with all features in the layer selected.

Current result from the tool:
![image](https://cloud.githubusercontent.com/assets/6999909/5964774/cb471a44-a7c4-11e4-8a64-b27e0cfa23ae.png)

Desired result (obtained from applying lyrx afterwards):
![image](https://cloud.githubusercontent.com/assets/6999909/5964788/e8581958-a7c4-11e4-9acd-67436e5ed41f.png)

A temporary fix that I have done is to add the "Apply Symbology From Layer" tool to the model.  I was not able to simply drag and drop the tool into the model however.  I had to copy the tool into my project toolbox first then and only then was I able to drag the tool inside of the model.  I do not think this was the intended process from development.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/129342386639048/129362678846666)

**Comment by jrweakland** [comment]
@mfunk - same as https://github.com/Esri/solutions-geoprocessing-toolbox/issues/219. I would verify with Pro 1.1 daily builds.

**Comment by mfunk** [comment]
In testing this one I'm getting errors and the tool is NOT working (see issue #362). Going to defer this one until the other is resolved.

**Comment by adgiles** [comment]
It is a known issue that the lyrx file will not apply labelling, the work around we have implemented is a task step to use the apply symbology gp tool.

**Comment by topowright** [comment]
This is no longer an issue because we have removed the models from the toolbox. Now the script tool handles everything correctly.
