### ISSUE TITLE
Add repo release/versioning info to README

### ISSUE THREAD

**Issue by mfunk** [Esri/solutions-geoprocessing-toolbox#206]
I need to add info on how and when we will do releases for this repo.
Obviously starting with semantic versioning http://semver.org/. But need to add how WE will decide when to do releases.
Unfortunately this still requires some discussion that we won't be doing until the end of Feb this year.

**Comment by conklinbd** [comment]
Is this still open? I thought we sorted this out.

**Comment by mfunk** [comment]
@conklinbd probably doesn't need to be.
