### ISSUE TITLE
Add Miscellaneous CADRG/ECRG Rasters To Mosaic Dataset fails

### ISSUE THREAD

**Issue by mfunk** [Esri/solutions-geoprocessing-toolbox#208]
The **Add Miscellaneous CADRG/ECRG Rasters To Mosaic Dataset** tool is failing it's tests because the parameter order has changed from the v1.0.2 release from the current tool.
```
TestAddMiscCADRGRastersToMosaicDataset:
     [exec] C:\Users\matt2542\Documents\GitHub\solutions-geoprocessing-toolbox\data_management\test\test_scanned_map_tools
     [exec] C:\Users\matt2542\Documents\GitHub\solutions-geoprocessing-toolbox\data_management\toolboxes
     [exec] Starting Test: Add Misc CARDG Rasters To Mosaic Dataset
     [exec] C:\Users\matt2542\Documents\GitHub\solutions-geoprocessing-toolbox\data_management\data\ScannedMaps\Sample\ScannedMaps.gdb\ScannedMapsMisc_Test
     [exec] Running from: C:\Users\matt2542\Documents\GitHub\solutions-geoprocessing-toolbox\data_management\test\test_scanned_map_tools
     [exec] Geodatabase path: C:\Users\matt2542\Documents\GitHub\solutions-geoprocessing-toolbox\data_management\data\ScannedMaps\Sample
     [exec] ERROR 000622: Failed to execute (Add Miscellaneous CADRG/ECRG Rasters To Mosaic Dataset). Parameters are not valid.
     [exec] ERROR 000628: Cannot set input into parameter Raster_Type.

BUILD FAILED
C:\Users\matt2542\Documents\GitHub\solutions-geoprocessing-toolbox\data_management\test\build.xml:54: The following error occurred while executing this line:
C:\Users\matt2542\Documents\GitHub\solutions-geoprocessing-toolbox\data_management\test\test_scanned_map_tools\build.xml:43: exec returned: -1
```
In the previous release the parameters were:
![image](https://cloud.githubusercontent.com/assets/3093182/6010407/ef9f5968-aae6-11e4-9c2f-22a5f53b9eeb.png)

In the current tool:
![image](https://cloud.githubusercontent.com/assets/3093182/6010411/f89b0580-aae6-11e4-82b6-d381e5dac927.png)

The addition of the optional Raster Type parameter in between two existing required parameters breaks GP tool convention. The **Add Miscellaneous CADRG/ECRG Rasters To Mosaic Dataset** tool parameters need to be reordered so that the Raster Type is after the Input Data parameter.

**Comment by NatalieCampos** [comment]
Tools were reverted/edited back to previous version

**Comment by mfunk** [comment]
@NatalieCampos I can verify when there is a pull request to verify against.

**Comment by NatalieCampos** [comment]
Matt 
These changes were made in the last pull request.  Can you verify?

**Comment by mfunk** [comment]
I can't verify by testing as the test data has been removed, however visually the tool parameters are as they were.
