### ISSUE TITLE
Range Fans not being constructed properly.

### ISSUE THREAD

**Issue by pshowalter** [Esri/solutions-geoprocessing-toolbox#214]
The Range Fan script "sourceRangeFan" appears to not be constructing the fan correctly.  It seems the problem is produced by a for loop that that loops throught the requested traversal angle, but leaves out the last vertex.

Example would be requesting fan with Traversal:  21 (degrees) ,
Maximum Range:  100,000 meters, Bearing: 100 (degrees), and appropriate Input  Surface for the aoi.  The resulting fan will have 20 1 degree segments corresponding to the step increments; it should have 21 segmants.  Related to the issue is that "for" loops don't handle decimals.

In figure below, note 20 segments:
![21degfan_20vertex](https://cloud.githubusercontent.com/assets/6842145/6249414/0e73dcae-b755-11e4-88ef-1690a7dd5d48.png)

In figure below, note 21 segments:
![image](https://cloud.githubusercontent.com/assets/6842145/6249505/a115858a-b755-11e4-905a-3469f87723b7.png)

Comparison of the two, below, showing slight offset at begining (related to using int on the fan angle, and the additional Traversal that occurs if an additional point is generated by the for loop.

![image](https://cloud.githubusercontent.com/assets/6842145/6249640/8facd874-b756-11e4-874c-14426478c15d.png)

Related to the issue is use of the GP Tool "Bearing Distanc To Line", which should generate a line that bisects the fan when using same origin, bearing, and distance.  It would be expected to intersect the fan between the 10th, and 11th vertext counting from bottom, but intersects after the 11th.
![image](https://cloud.githubusercontent.com/assets/6842145/6249765/5f67a30a-b757-11e4-888b-a613b219dbcf.png)

If the line of bearing is created using "Edit - Create", snap the beginging of the line to the same origin point, then righ click to bring up context menu, and select "Direction and Distance", key in 

100, NAz and 100,000 m, then the line of bearing will bisect the fan at the appropriate segment.
![image](https://cloud.githubusercontent.com/assets/6842145/6250005/fb5f51a8-b758-11e4-9981-d93215f4b9f5.png)
![image](https://cloud.githubusercontent.com/assets/6842145/6250051/4c4c64b6-b759-11e4-9bf3-dc0157d78b18.png)

**Comment by mfunk** [comment]
Tested with bearing 120.3 and traversal 135.8...

```
Executing: RangeFan "Feature Set" 3000 120.3 135.8 "Terrain (AGOL)" C:\Workspace\Test\TestForErikReid\aTarget.gdb\mfRR0001 C:\Workspace\Test\TestForErikReid\aTarget.gdb\mfVIZ0001 "PROJCS['WGS_1984_UTM_Zone_42N',GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['false_easting',500000.0],PARAMETER['false_northing',0.0],PARAMETER['central_meridian',69.0],PARAMETER['scale_factor',0.9996],PARAMETER['latitude_of_origin',0.0],UNIT['Meter',1.0]];-5120900 -9998100 10000;-100000 10000;-100000 10000;0.001;0.001;0.001;IsHighPrecision"
...
...
```

Left bearing should be 120.3 - (135.8 / 2) = **52.4**
Right bearing should be 120.3 + (135.8 / 2) = **188.2**

1. Start Edit Session
2. COGO tools >> COGO Report
3. Select Direction and Distance Of A Line 
![image](https://cloud.githubusercontent.com/assets/3093182/6375787/40607780-bcce-11e4-8392-ff6b36de81f5.png)
4. Click center point, then left bearing point....
![image](https://cloud.githubusercontent.com/assets/3093182/6375830/930e1578-bcce-11e4-86d0-ed8104e08bf1.png)

hmmmm ... very close in angle, off by ~0.1 degrees. But the distance is off horribly.

Check the right azimuth the same way.
![image](https://cloud.githubusercontent.com/assets/3093182/6375881/f3a70c46-bcce-11e4-9503-900e5e4680ba.png)


Again the angle is close, off by ~0.1 degrees but the distance is off by about 645 meters.
I'm going to close this one and start a new one for the distance problem after a bit more testing.

**Comment by mfunk** [comment]
Ahhh the dangers of coordinate systems. The Range Fans are building features correctly. The COGO report is showing incorrect distances because my Data Frame's coordinate system was Web Mercator (I was using this MXD for my Web Merc transition testing and forgot to reset it). Anyway the distances and angles being created by the Range Fans tool are correct...

![image](https://cloud.githubusercontent.com/assets/3093182/6376667/395d7be4-bcd4-11e4-8008-a9bbc740eac9.png)

... and ....

![image](https://cloud.githubusercontent.com/assets/3093182/6376703/67c951e2-bcd4-11e4-8a2d-d4c6c2c9b8b2.png)
