### ISSUE TITLE
Point Of Origin Site Detection not applying symbology in Pro 1.0

### ISSUE THREAD

**Issue by mfunk** [Esri/solutions-geoprocessing-toolbox#219]
The Point Of Origin Site Detection tool is not properly applying the symbology for the output Impact point features. This is a problem with the ApplySymbologyFromLayer tool not working properly in ArcGIS Pro 1.0. 
![image](https://cloud.githubusercontent.com/assets/3093182/6277389/0df3b256-b843-11e4-9307-167ae64b1c0a.png)

The correct symbology is applied in ArcMap 10.3.
![image](https://cloud.githubusercontent.com/assets/3093182/6277198/701ed3fe-b841-11e4-911d-30484c38fced.png)

When a fix is applied to ApplySymbologyFromLayer this tool should work correctly. I logged this issue as more of an FYI than anything.

**Comment by jrweakland** [comment]
@mfunk - have we tried to run this tool in Pro 1.1 daily builds?

**Comment by pshowalter** [comment]
This is resolved, I moved some code that applied the layer symbol above the point where it is added to the grouped layer.  1.02 and 1.1.
![image](https://cloud.githubusercontent.com/assets/6842145/8557709/251fa9c0-24cd-11e5-9f44-9a6ea63652f5.png)

**Comment by jrweakland** [comment]
:+1:
