### ISSUE TITLE
Incident Analysis - Find Percent Change - should be showing decrease, but shows increase

### ISSUE THREAD

**Issue by pshowalter** [Esri/solutions-geoprocessing-toolbox#227]
Setup: Run the: data_management\toolboxes\Adjust Sample Data Dates Tools.tbx\Change Sample Data Dates to Recent Dates

Run the “Find Percent Change” using Month Before Last as (Old Activity) and Last 30 days as (New Activity)
![image](https://cloud.githubusercontent.com/assets/6842145/6415807/5773eca2-be6f-11e4-95c3-4644527120e5.png)

Result will be 6% form District 1 (D1).
![image](https://cloud.githubusercontent.com/assets/6842145/6415809/5dc03084-be6f-11e4-9ffb-b8dc0d6293a7.png)

Analysis: 
Select District D1
![image](https://cloud.githubusercontent.com/assets/6842145/6415810/6390d75c-be6f-11e4-8ec8-4824397986ed.png)

Select Incidents in that District using Select by Location. Select both “Last 30 Days” and “Month Before Last” in same operation.
![image](https://cloud.githubusercontent.com/assets/6842145/6415820/7230bca0-be6f-11e4-9d98-a9d75afe1be1.png)
![image](https://cloud.githubusercontent.com/assets/6842145/6415827/77ca6c60-be6f-11e4-8312-c1df6f1671db.png)

144 Records in Last 30
153 in Month before last
Should be a decrease or negative percentage? 

It appears that values NewActivity_JoinCount and OldActivity_JoinCount are swapped in the result feature class….? Percent Change is positive shows a 6% increase…

![image](https://cloud.githubusercontent.com/assets/6842145/6415831/809866da-be6f-11e4-9963-3b316b70518d.png)

Looking at the model section…

![image](https://cloud.githubusercontent.com/assets/6842145/6415838/85ddd7ec-be6f-11e4-8c40-8e5cb9757cb9.png)

The Feature Class to Feature Class is using a technique in the Field Map that I am not familiar with.
I can’t find “LaterActivitySpatialJoin” in the model, which appears is where the NewActivity_JoinCount and OldActivity_JoinCount fields are coming from, but I am thinking this is where the values are being swapped.

![image](https://cloud.githubusercontent.com/assets/6842145/6415841/8e61a344-be6f-11e4-9e66-72cc69612811.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/129342386639048/129373043794867)

**Comment by mfunk** [comment]
@dfoll Can you try this one out on 10.4 as part of the certification? I'd like to know if we still see the problem.

**Comment by mfunk** [comment]
Moving this to Version - After Next.

**Comment by mfunk** [comment]
Manually tested the percentage change using field values from the tool and the values match.

![image](https://cloud.githubusercontent.com/assets/3093182/25357178/baab9ab0-28f1-11e7-84da-bf1cf226a4f9.png)

example for D-1 in this case:
- Join_Count: **12**
- Join_Count_1: **23**
- Difference = Join_Count_1 - Join_Count = 23 - 12 = **11**
- Quotient = Difference/Join_Count = 11/12 = **0.916666666...**
- PercentChange = Quotient * 100 = 91.66666666... ~ **92%**

Same calculations work for all of the other values in the table also.
Closing this one as not reproducible.
