### ISSUE TITLE
Add Unit Tests for Data Management\Mosaic Dataset Toolboxes

### ISSUE THREAD

**Issue by csmoore** [Esri/solutions-geoprocessing-toolbox#230]
These:

- [x] CADRG ECRG Tools.pyt
- [x] CIB Tools.pyt
- [x] Elevation Tools.pyt
- [x] LiDAR Elevation Tools_10.3.tbx (update based on comment below)

Also in cases where a tool is repeated in the above .pyt and in another existing toolbox (.tbx) - we might need some guidance on which one to use in readme.

**Comment by mfunk** [comment]
Also...
* [ ] LiDAR Elevation Tools_10.3.tbx needs tests written

**Comment by mfunk** [comment]
The following tools need tests written:
* CADRG ECRG Tools.pyt
   * [ ] CADRG/ECRG Mosaic Datasets
* CIB Tools.pyt
   * [ ] Create CIB Mosaic
* Elevation Tools.pyt
   * [ ] Create Derived Elevation Mosaic
   * [ ] Crate Source Elevation Mosaic
* LiDAR Elevation Tools_10.3.tbx
   * [ ] Create Source LAS Ground Elevation Mosaic
   * [ ] Create Source LAS Surface Elevation Mosaic

**Comment by mfunk** [comment]
So as of now the tests are written for these tools, however we are having difficulty getting test data that we can release (using local, non-releaseable stuff to build tests for now). This may stop us from having any tests available for these tools that are connected to the overall test suite.

**Comment by mfunk** [comment]
Talked with Clark about getting test data that we can release. He said he will have to check with his contacts about what we can do.

**Comment by mfunk** [comment]
No data from NGA. Moving this into Version - Deferred.

**Comment by mfunk** [comment]
As of September 2016 these toolboxes are all being deprecated per November 2016 release plans. So this issue will be closed as tests are not needed.
