### ISSUE TITLE
The MDCS scripts are missing if a user downloads it as a zip file

### ISSUE THREAD

**Issue by abhiataero** [Esri/solutions-geoprocessing-toolbox#232]
The MDCS scripts are missing if a user downloads it as a zip file

this break the python tool boxes ( CIB, CADRG,Elevation)

**Comment by mfunk** [comment]
Hi @abhiataero did you run the **config_mdcs.bat** in the *data_management\toolboxes\config_mdcs* folder? Check the [README.md](https://github.com/Esri/solutions-geoprocessing-toolbox/blob/master/data_management/README.md).

**Comment by csmoore** [comment]
We might have to update the main readme: 

https://github.com/Esri/solutions-geoprocessing-toolbox#getting-started-with-the-tools to tell folks

1. They have to *clone* the repo now (vs. getting a zip)
2. That "Note: these component have additional configuration steps" & a link to those that do

Might be a dumb question, but I wonder it these submodule files will be in the [Releases](https://github.com/Esri/solutions-geoprocessing-toolbox/releases) when they get created? If not, that might be an issue

**Comment by mfunk** [comment]
Well if you have GIT installed when you download the ZIP it will not be a problem, the BAT file will get the mdcs files as needed, and then overlay the solutions-specific files needed in the mdcs folder.

However do we want to force all users to have GIT installed for any ZIP file we give them? This changes requirements in our Solutions Pages that i'm working on, so we need to decide now.

**Comment by conklinbd** [comment]
We do not want to require people to have git installed when they download the zip. Remember that the purpose of the zip files is to take our solutions and deploy them on their own networks, where they don't have access to github.

**Comment by mfunk** [comment]
So that leaves us with two options:

1. have a deployment script (PY?) that downloads and copies the MDCS repo ZIP contents to a known folder and then overlays the file. More upfront work, but less maintenance.

2. Have a static copy of the MDCS in our own repo. Easier up front, but much more maintenance.

**Comment by csmoore** [comment]
@mfunk - Another option is to add a full deployment version of the zip to the Release Pages (when you officially release this). 

For any release you can add any addition files/zips to a release if you want: https://github.com/Esri/solutions-geoprocessing-toolbox/releases/edit/v1.0.2 ("Attach binaries" section).

Hopefully the official releases are the ones that we care most about not requiring git be installed - and for the current development version (vs. Release) requiring Github for Windows will be OK. If so this approach should work.

**Comment by mfunk** [comment]
Unfortunately the MDCS repo is looking for the scripts in a specific folder location relative to the PYTs that we are using. Also you'd still have to do the file overlay. In the end we will just copy the mdcs-py repo until we can come up with some kind of management script to do the copy for us.

**Comment by mfunk** [comment]
At this point the solution was to copy the whole MDCS folder to .\solutions-geoprocessing-toolbox\data_management\toolboxes. That is now completed.
