### ISSUE TITLE
Point of Origin Detection

### ISSUE THREAD

**Issue by pshowalter** [Esri/solutions-geoprocessing-toolbox#238]
Using the Point of Origin Tools_10.3.tbx Tool works in 10.3 when using interactive entry of point into a feature_set.  If I create my own feature class in UTM 10 N over Monterrey, the tool will error at the point of creating buffer.

Executing: PointOfOriginSiteDetection pood_impacts_monterey_01_UTM10N C:\myProjects\GitHub\solutions-geoprocessing-toolbox\capability\toolboxes\tooldata\PointOfOrigin.gdb\Weapons Model Minimum_Range Maximum_Range '120mm American Mortar' C:\myProjects\PointofOriginDetection\GDB\PointOfOriginDetection_testing.gdb pnt imp rng  
... (removed projection info)
Start Time: Mon Mar 09 09:54:58 2015
Running script PointOfOriginSiteDetection...
Building impact points...
Getting Range for: '120mm American Mortar'
Buffering Impact Point OID 1 for '120mm American Mortar'
Executing: Buffer # C:\Users\patrick\Documents\ArcGIS\Default.gdb\Impact_Max_1_120mm_American_Mortar "1650 Unknown" FULL ROUND NONE # PLANAR
Start Time: Mon Mar 09 09:55:01 2015
Failed to execute. Parameters are not valid.
ERROR 000735: Input Features: Value is required
Failed to execute (Buffer).
Failed at Mon Mar 09 09:55:01 2015 (Elapsed Time: 0.08 seconds)
Completed script PointOfOriginSiteDetection...
Failed to execute (PointOfOriginSiteDetection).
Failed at Mon Mar 09 09:55:01 2015 (Elapsed Time: 3.77 seconds)

**Comment by mfunk** [comment]
Tried this one out today.
Projected some points (Central CA) into UTM 10N WGS 1984.


```
Executing: PointOfOriginSiteDetection InputProjUTM10N C:\Users\matt2542\Documents\GitHub\solutions-geoprocessing-toolbox\capability\toolboxes\tooldata\PointOfOrigin.gdb\Weapons Model Minimum_Range Maximum_Range 'M120/121 120-mm American Mortar' "C:\Workspace\ArcGIS Defense Templates\Vehicle Checkpoint Template\Certification testing for Desktop 10.4\testgdb.gdb" pnt imp rng # false
Start Time: Thu Dec 10 11:34:15 2015
Running script PointOfOriginSiteDetection...
Spatial Reference is not defined. Using Spatial Reference of Impact Points: WGS_1984_UTM_Zone_10N
Building impact points...
Getting Range for: 'M120/121 120-mm American Mortar'
Buffering Impact Point OID 1 for 'M120/121 120-mm American Mortar'
Buffering Impact Point OID 2 for 'M120/121 120-mm American Mortar'
...Could not determine version.\n   Looking for ArcMap ['10.2.2', '10.3', '10.3.1'], or ArcGIS Pro ['1.0', '1.1'].
   Found 10.4
Completed script PointOfOriginSiteDetection...
Succeeded at Thu Dec 10 11:34:33 2015 (Elapsed Time: 17.48 seconds)
```

Will try a few other variations.

**Comment by mfunk** [comment]
Tried a few more cases and all are working at 10.4.
