### ISSUE TITLE
Radial Line of Sight and Range tool still has a reference to the computer it was posted from

### ISSUE THREAD

**Issue by dfoll** [Esri/solutions-geoprocessing-toolbox#244]
the Output Workspace parameter still has a default of 
D:\Users\matt2542\Documents\GitHub\solutions-geoprocessing-toolbox\visibility\data\Results.gdb.

this does not affect how the tool runs, but we could clean this up.

**Comment by dfoll** [comment]
![image](https://cloud.githubusercontent.com/assets/5322669/6947684/c3bf9782-d85d-11e4-8f17-8abe016bebc7.png)

**Comment by mfunk** [comment]
Try it now... cleaned up with https://github.com/Esri/solutions-geoprocessing-toolbox/pull/246

**Comment by mfunk** [comment]
No response in 3 weeks ... closing.
