### ISSUE TITLE
Sub Depth Restriction Analysis is missing default input table

### ISSUE THREAD

**Issue by mfunk** [Esri/solutions-geoprocessing-toolbox#245]
The **Sub Depth Restriction Analysis** tool in *Maritime Decision Aid Tools* toolbox (10.3 and Pro) are missing the default 'Sub_Specs' table. We probably had the tool added without including the inputs in the 'tooldata' folder in the repo. This is causing the tool to have a validation error on Open

![image](https://cloud.githubusercontent.com/assets/3093182/6948232/43625314-d861-11e4-8297-64c60cadb5c3.png)

To make this work we:
1) need to add a *Maritime Decision Aid Tools.gdb* to *.\suitabilty\toolboxes\tooldata*.
2) Add the requisite *Sub_Specs* table to the above geodatabase
3) Add the *Sub_Specs* table to the *Ship Specification Table* parameter in the tool.

**Comment by mfunk** [comment]
@jfrygeo Don't think we had tooldata set up when the toolbox was added to the repo.

**Comment by jfrygeo** [comment]
@mfunk Yes, I think that is probably what happened. There was a table in one of the file geodatabases that fed the tool.

**Comment by jrweakland** [comment]
@jfrygeo - please provide @mfunk the necessary files.

**Comment by mfunk** [comment]
@jfrygeo Got the *Sub_Specs* table so I can add it in?

**Comment by jfrygeo** [comment]
Sent to @mfunk via email.
