### ISSUE TITLE
Tool help for Range Fan is not accurate

### ISSUE THREAD

**Issue by dfoll** [Esri/solutions-geoprocessing-toolbox#249]
The tool help for the parameter Spatial Reference states " If no coordinate system is selected then the coordinate system of the Input Centers parameter is used as the common spatial reference.", however when you run the tool that parameter is not actually an optional parameter.Either the parameter should be made optional, or the tool help should be changed.

**Comment by mfunk** [comment]
@dfoll What are the results you are seeing? How do you know it is not optional? Need more info.

**Comment by mfunk** [comment]
No comment in three weeks.... closing.

**Comment by dfoll** [comment]
i'm seeing that the tool won't let you run it without entering that parameter

**Comment by mfunk** [comment]
@dfoll still waiting for detailed steps to reproduce the error and a copy of the message you are seeing.

**Comment by mfunk** [comment]
No response, closing.
