### ISSUE TITLE
Explanation of real world use

### ISSUE THREAD

**Issue by topowright** [Esri/solutions-geoprocessing-toolbox#250]
Explain to users that they can use this toolbox directly from GitHub repository

**Comment by joebayles** [comment]
@topowright (who should correct me if I'm wrong) means explaining how to clone a fork of this repository to one's local machine and linking that up to date solutions-geoprocessing-toolbox folder (or subfolder) with the ArcGIS Pro project or ArcMap map document.

I agree, and think that explanation should live here and in the https://github.com/joebayles/arcgis-solutions-website (or at least complement each other).

**Comment by mfunk** [comment]
@topowright @joebayles I do not agree. Remember that GitHub is a tool for developers, not GIS users, who want the tools without the templates, or want to modify the tool. If we want to explain to users how GitHub works, can do this on the Solutions Pages, **not here**. I can add some instructions to the Getting Started page in Solutions Geoprocessing Toolbox to point users to the GitHub help for this.

**Comment by joebayles** [comment]
@mfunk I like your answer it sounds like they'll complement each other. :+1:

**Comment by topowright** [comment]
@joebayles @mfunk Got it.
