### ISSUE TITLE
Change Detection Tools.tbx do not have tool help

### ISSUE THREAD

**Issue by mfunk** [Esri/solutions-geoprocessing-toolbox#251]
Change Detection Tools.tbx do not have tool help

If you open the tools in ArcGIS Pro and click on the help button the help topic is empty. Something might have happened to the help topics of it existed before. But now this is all I see:

-----------------------------------------------------------------------------------------------------

![image](https://cloud.githubusercontent.com/assets/3093182/7205884/629cc34a-e4e1-11e4-9202-9f643c893688.png)

-----------------------------------------------------------------------------------------------------
ALL tools need to have:
* Description (including explanation of acronyms)
* Usage (tips and tricks of using the tool)
* Parameter explanations
* Tags
* Credits (source of methodology, etc.)

The tools that are missing stuff are:
* [ ] Classification Accuracy (missing everything)
* [ ] Dark Object Subtraction (missing everything)
* [ ] IMAD Analysis (missing everything)
* [ ] PseudoInvariantFactor (missing everything)

**Comment by mfunk** [comment]
@helyx-amcmillan @NatalieCampos Not sure if these tools had help topics and something happened or something else. Anyway I found this because I need to know what *IMAD* means for the Solutions Pages for the tools.

**Comment by NatalieCampos** [comment]
@helyx-amcmillan or @nfeuerstein Would be able to do this. I haven't worked on the latest version of the tools/template

**Comment by helyx-amcmillan** [comment]
@mfunk I stopped development on this set of tools because we were going to consider redeveloping them as raster functions in Core instead. Because they were third party tools we had issues with upgrading them to use in Pro, and referring to them in tasks was throwing errors. I would suggest it would be useful to archive them somewhere, but I would say they're not in a state to release.

**Comment by mfunk** [comment]
@nfeuerstein @conklinbd should these be slated for deprecation?

**Comment by nfeuerstein** [comment]
@mfunk I don't think we need to deprecate them since they were never released.  We should probably have a branch for tools that are truly in development and not ready to be released - and these tools should go there.

**Comment by mfunk** [comment]
A branch would be fine, but should be up to the developer to branch on their remote so the Esri master is maintained. When development is complete then the branch can be merged and PR'ed.

**Comment by conklinbd** [comment]
concur with with approach.

**Comment by mfunk** [comment]
These tools were removed from the whole repo per discussion with @nfeuerstein .
