### ISSUE TITLE
Scripts & Visibility and Range Tools_10.3.tbx

### ISSUE THREAD

**Issue by rfeuerstein** [Esri/solutions-geoprocessing-toolbox#253]
Received the following error running the Radial Line of Site - Multi Positions tool in 10.3...

		Executing: RadialLineofSightMultiplePositions Border_Peaks pointid Elevation Border_DTED_Clip C:\Products\Border\BorderObservationPoints\BorderObservationPoints.gdb LOS_Viewshed_MP false
		Start Time: Mon Apr 20 16:58:36 2015
		Executing (Radial Line of Sight - Multiple Towers): TowersRadialLineOfSight2 Border_DTED_Clip false Border_Peaks pointid Elevation C:\Products\Border\BorderObservationPoints\BorderObservationPoints.gdb LOS_Viewshed_MP
		Start Time: Mon Apr 20 16:58:36 2015
		ERROR 000576: Script associated with this tool does not exist.
		Failed to execute (Radial Line of Sight - Multiple Towers).
		Failed at Mon Apr 20 16:58:36 2015 (Elapsed Time: 0.00 seconds)
		Failed to execute (RadialLineofSightMultiplePositions).
		Failed at Mon Apr 20 16:58:36 2015 (Elapsed Time: 0.03 seconds)

Looks like i need to download and associate the scripts to the tools. 

It appears that the code for the scripts can be examined individually but I can't seem to find a download option. Other than copying each script one by one and creating a local copy, is there an easier process? 

Thanks.

**Comment by mfunk** [comment]
@rfeuerstein I'm seeing some weird naming stuff going on between the model, the script tool, and the script file. The model calls *Radial Line of Sight - Multiple Towers*, but the model tool's actual name is *TowersRadialLineOfSight2*... really bad naming there. The Name should be similar to the Label (Radial Line of Sight - Multiple Towers), but without spaces: *RadialLineofSight-MultipleTowers*.
Changing that now...

**Comment by mfunk** [comment]
@rfeuerstein Made some changes that are working on my end. Need you to test it out, just as you did before. If it works, close the issue. If not, need more info. Thnx.

**Comment by rfeuerstein** [comment]
![image](https://cloud.githubusercontent.com/assets/7117658/7290777/daaab44e-e939-11e4-9155-d63bb9db0b37.png)


The Radial Line of Sight – Multiple Towers script tool in the SourceScripts for Visibility and Range Tools_10.3 is pointing to \\scripts\TowersLOS.py which can be found in the scripts folder in the Visibility folder on GitHub; however, it is not downloaded with the VisibilityandRangeTools_10.3.tbx.  

I grabbed the Visibility download from box: https://esri.box.com/s/cydkw157i4r7e7ubak94uppon28f8hkf and ran the “Radial Line of Sight – Multiple Positions” model.  Since this gp toolbox for Visibility tools does include the scripts folder, I was able to get further when I ran this version of the tool.  But, I’m still getting errors.  See below:

Processing tower 1 of 50
...towerName: a
...scrubbedTowerName: a
...Finding observer's minimum bounding envelope ...
...Finding center of tower ...
PYTHON ERRORS:
Traceback info:
  File "C:\Products\Border\BorderObservationPoints\SolutionsGeoprocessingToolbox-Visibility_2.0.0_ArcGIS10.3\SolutionsGeoprocessingToolbox-Visibility_2.0.0_ArcGIS10.3\toolboxes\scripts\TowersLOS.py", line 186, in <module>
    z_factor = float(zfactor(tower))

Error Info:
'Extent' object has no attribute 'xmin'

ArcPy ERRORS:
Executing: CreateFeatureclass C:\Products\Border\BorderObservationPoints\BorderObservationPoints.gdb mbgCenterPoint_towerlos_a POINT # DISABLED DISABLED "GEOGCS['GCS_North_American_1983',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],VERTCS['Unknown VCS',VDATUM['Unknown'],PARAMETER['Vertical_Shift',0.0],PARAMETER['Direction',1.0],UNIT['Meter',1.0]];-400 -400 11258999068426.2;-100000 10000;-100000 10000;8.98315284119521E-09;0.001;0.001;IsHighPrecision" # 0 0 0
Start Time: Wed Apr 22 17:32:43 2015
Succeeded at Wed Apr 22 17:32:44 2015 (Elapsed Time: 0.30 seconds)

Map package for my data can be found here, https://esri.box.com/s/2nztxubeylxnd7kzrmet8kyi8b58y4as 

Please let me know if I can provide more information.

-Rob

**Comment by mfunk** [comment]
@rfeuerstein not sure what you mean by 'it is not downloaded with the VisibilityandRangeTools_10.3.tbx'. The TowersLOS.py is downloaded with the repo, and with both ZIP files in the first BOX folder listed above.

I'm guessing the inputs you used were as follows:
![image](https://cloud.githubusercontent.com/assets/3093182/7298915/7e256fa4-e987-11e4-9700-c404c17d335f.png)

Anyway I found the bad/missing extent properties around line 28 and fixed them. However, that lead to a more serious problem. The script fixes a maximum radius of '4000' units. Not good to hardcode numbers like that, because eventually you find a point (ID = 'j' or ID = 'h' ) where the edge of the surface is less than 4000 units from the points.

![image](https://cloud.githubusercontent.com/assets/3093182/7299254/9fc872bc-e989-11e4-9dc7-0e0c759d83a1.png)

In otherwords the buffer falls off the edge of the surface ...

```
...Recentering Azimuthal Equidistant to centroid ...
...Running viewshed to the maximum observer radius...
...Creating a buffer from the observer points to the horizion distance.  maximum observer radius: 4000
Executing: Buffer C:\Users\matt2542\Documents\ArcGIS\Packages\BorderObservationPointsMPK_D7F3A605-57F8-4C55-A690-BFD42A46D1B2\v103\borderobservationpoints.gdb\observers_mbg_towerlos_a C:\Users\matt2542\Documents\ArcGIS\Packages\BorderObservationPointsMPK_D7F3A605-57F8-4C55-A690-BFD42A46D1B2\v103\borderobservationpoints.gdb\mbgBuffer_towerslos "4000 Unknown" FULL ROUND NONE # PLANAR
Start Time: Thu Apr 23 07:08:25 2015
ERROR 000599: Falls outside of output geometry domains.
The coordinates or measures are out of bounds.
Failed to execute (Buffer).
Failed at Thu Apr 23 07:08:25 2015 (Elapsed Time: 0.40 seconds)
Removing intermediate datasets...
Done
```

So we'll have to go back to the original requirements (DCGS-A for this tool) and see where the 4000 units came from. Until then you might want to clip a larger DTED... at least wider to the east.

**Comment by mfunk** [comment]
Logged #257 for the subsequent error.
