### ISSUE TITLE
Radial Line Of Sight - Multiple Positions uses hardcoded RADIUS2 measure of 4000 units

### ISSUE THREAD

**Issue by mfunk** [Esri/solutions-geoprocessing-toolbox#257]
Radial Line Of Sight - Multiple Positions uses hardcoded RADIUS2 measure of 4000 units.
The tool uses ..\visibility\toolboxes\scripts\TowersLOS.py, where line 156 sets the values:

`obsMaximums = {'SPOT':None,'OFFSETA':towerHeight, 'RADIUS2':4000, 'REMOVE_SPOT':False}`

As far as I can tell this will ALWAYS use 4000 units to do the viewshed from each observer point. So if an observer falls on the edge of the surface we will get an error message:

```
...Recentering Azimuthal Equidistant to centroid ...
...Running viewshed to the maximum observer radius...
...Creating a buffer from the observer points to the horizion distance.  maximum observer radius: 4000
Executing: Buffer C:\Users\matt2542\Documents\ArcGIS\Packages\BorderObservationPointsMPK_D7F3A605-57F8-4C55-A690-BFD42A46D1B2\v103\borderobservationpoints.gdb\observers_mbg_towerlos_a C:\Users\matt2542\Documents\ArcGIS\Packages\BorderObservationPointsMPK_D7F3A605-57F8-4C55-A690-BFD42A46D1B2\v103\borderobservationpoints.gdb\mbgBuffer_towerslos "4000 Unknown" FULL ROUND NONE # PLANAR
Start Time: Thu Apr 23 07:08:25 2015
ERROR 000599: Falls outside of output geometry domains.
The coordinates or measures are out of bounds.
Failed to execute (Buffer).
Failed at Thu Apr 23 07:08:25 2015 (Elapsed Time: 0.40 seconds)
Removing intermediate datasets...
Done
```

Not sure of the best case to handle this, other than trap the error, throw a warning like "Tower Position is too close to Input Surface Edge", skip it, and move on to the next tower. Looking at the help topic for this tool, there is absolutely no mention of the 4000 unit hardcoded distance. Actually the tool help for this one is missing any kind of Usage notes.

So the first thing we need to do is figure out where the limit came from. Any ideas @nfeuerstein?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/129342386639048/129373044532566)

**Comment by nfeuerstein** [comment]
@mfunk I know exactly where it came from, but it wasn't a user requirement and wasn't based on any real-world logic.  Just to make sure I'm following: 4000 units is referring to the map units right?  So, if the map units are meters then the tool wants 4000 meters of surface around a given point for the viewshed?

**Comment by mfunk** [comment]
This is where the explanation is complicated, but the answer is simple. The RADIUS2 key value is only storing a number: 4000. No units. That is left up to the tool to figure it out, in this case both **Buffer_anlaysis()** and **Viewshed_spatial()**. The one thing that saves us with this tool is that, like **RLOS_VandR()**, it projects the inputs (both I think) into a localized Azimuthal Equidistant, which is in *meters*. But it's still kinda dangerous to hardcode values like that, for the aforementioned reason... what if your surface is only 2000m across? Tool will fail with an error.

**Comment by nfeuerstein** [comment]
Yep, that's complicated.  Regardless, though, I'm with you that its dangerous and definitely not preferred to hardcode situational parameters, like the size of the elevation surface, in the script.  Would it make sense to expose this as a parameter or to pull from the input?

**Comment by mfunk** [comment]
Either case is acceptable. We used to do this with some of the older tools and in the old Military Analyst extension. I'm thinking that perhaps there is another way we should be looking at this. Might need to discuss when we start planning for next V&R template kick-off. I think we should consider separating the creation/use of observers, and the actual viewshed/line-of-sight. We have MANY cases for creating observers from existing points, locations, tables, or just hand-jamming stuff into a dialog. But we really shouldn't try to make a completely separate analytic tool for each case. Like I said we might have to think about this one.

**Comment by nfeuerstein** [comment]
Agreed, in the meantime what is the easiest/best fix?  Use a larger elevation surface with a minimum of 4000 units from each observer point?

**Comment by mfunk** [comment]
In this case the best and easiest fixes are the same: document it. For now the tool *Usage* should have a bullet point that says the range is fixed at 4000 meters in a localized Azimuthal Equidistant. See the **RLOS_VandR()** help for ideas of how we should be doing it.

BTW this probably also applies to **Radial Line Of Sight - Single Position**. :grimacing:

**Comment by topowright** [comment]
This work might not need to be done being that this template might move into mature support.

**Comment by mfunk** [comment]
Added to backlog.

**Comment by mfunk** [comment]
The tool/toolbox associated with this issue has been deprecated and is no longer actively supported. Earlier versions of this toolbox will still be available from previous [Releases](https://github.com/Esri/solutions-geoprocessing-toolbox/releases)
