### ISSUE TITLE
Propose new Labels for toolbox type

### ISSUE THREAD

**Issue by mfunk** [Esri/solutions-geoprocessing-toolbox#260]
All,
To better sort and filter issues I'd like to propose a set of labels to relate the issue to a specific type of toolbox, or which *folder* the issue is related to:

* F - All
* F - Capability
* F - Data Management
* F - Operational Graphics
* F - Patterns
* F - Suitability
* F - Visibility

The **All** label would be for issues/changes/enhancements that would affect ALL of the tools. I'm undecided on this label or simply adding all of the other six to an issue.

The reason I'd like to add these labels is to help sort issues when we do releases. This would make it MUCH easier to do release notes for distributing each folder as its own group. Please add comments! I want to close this one out in another week or two (around 5/15/2015). 

Thanks,
Matt

**Comment by conklinbd** [comment]
I think this is a good idea. Most of the issues would fit into a single label.

**Comment by nfeuerstein** [comment]
:+1:

**Comment by joebayles** [comment]
:+1:

**Comment by mfunk** [comment]
OK. feeling antsy about this one and going to go ahead and implement as above, including the "F - All" label, and then close this out.

**Comment by mfunk** [comment]
Done
