### ISSUE TITLE
Need to update Weapons table with new version.

### ISSUE THREAD

**Issue by pshowalter** [Esri/solutions-geoprocessing-toolbox#261]
.\solutions-geoprocessing-toolbox\capability\toolboxes\tooldata\PointOfOrigin.gdb\Weapons table should be updated with the table used in 10.3 template.  The new table was created based on published reference.

**Comment by mfunk** [comment]
@pshowalter would you replace the updated table and make a pull request? Thanks.

**Comment by mfunk** [comment]
@pshowalter is this related to pull #281?

**Comment by pshowalter** [comment]
@mfunk I will have to investigate and get understanding on how the test scripting runs.

**Comment by pshowalter** [comment]
If I understand what the test_poo script/tool is doing:
These are the old weapon types that we did not have documentation for:

test_poo_tools:
     [exec] inputWeaponsAsString: '82mm Soviet Mortar';'88mm American Mortar';'120mm American Mortar'
     [exec] inputWeaponsAsList: ["'82mm Soviet Mortar'", "'88mm American Mortar'", "'120mm American Mortar'"]

…

Later we see references to the new weapon types that are in the new GDB that we found documentation for.  Is it possible the test script just need new parameters to call the new weapon names?

[exec] Failed to execute. Parameters are not valid.
     [exec] ERROR 000800: The value is not a member of M120/121 120-mm American Mortar | M224 60-mm American Mortar | M252 81-mm American Mortar.
     [exec] ERROR 000800: The value is not a member of M120/121 120-mm American Mortar | M224 60-mm American Mortar | M252 81-mm American Mortar.
     [exec] ERROR 000800: The value is not a member of M120/121 120-mm American Mortar | M224 60-mm American Mortar | M252 81-mm American Mortar.
     [exec] Failed to execute (PointOfOriginSiteDetection).

There may be more to the story, as some of the work I did for the Pro template to use the default Pro folder structure, which differs from the folder structure of the ArcMap template, but I don’t see that Pro or Python 3.4 is part of the output from the test that failed.  So we haven’t hit those test issues yet.

**Comment by pshowalter** [comment]
Modified test script to point to new weapon names.
Had previously sent: 
\capability\toolboxes\tooldata\PointOfOrigin.gdb\Weapons.

Last week, sent new file GDB with new impact points (Monterrey area)
\capability\data\geodatabases\test_poo_tools.gdb\impact_pts_monterey_UTM10N.

Test script runs properly on my local machine/repo.
