### ISSUE TITLE
Hot Spots by Area has a few things that need to be fixed.

### ISSUE THREAD

**Issue by mfunk** [Esri/solutions-geoprocessing-toolbox#264]
* [X] Name is *AOIHotSpots* but should be *HotSpotsbyArea*.
* [X] Naming two parameters "Input Features" is really confusing. While the input parameters should identify if it is an input or an output, it should also uniquely identify WHAT the parameter is. I would have chosen *Input Area of Interest Feature* over *Input Features (Area of Interest)*, and *Input Incident Point Features* over *Input Features (Incident Points)*. This clear without having to add hints in parenthesis.
* A few doc changes will help the end user:
     * [x] Usage should point out that this tool produces multiple feature classes in the Output Workspace (no .. that is NOT obvious).
     * [x] If the user does not select enough incident points the tool will fail. The tool help doesn't say anything about a minimum number of incident points. 

```
Executing (Optimized Hot Spot Analysis): OptimizedHotSpotAnalysis in_memory\Select5 C:\Workspace\Test\TestIncidentAnalysis\Test_IA\Test_IA.gdb\1_HotSpots # COUNT_INCIDENTS_WITHIN_FISHNET_POLYGONS I_Districts_OBJECTID # #
Start Time: Mon May 04 07:40:21 2015
Running script OptimizedHotSpotAnalysis...
************************** Initial Data Assessment ***************************
Making sure there are enough incidents for analysis....
 ERROR 001570: The analysis option you selected requires a minimum of 30 points to be inside the bounding polygon area(s).
Completed script OptimizedHotSpotAnalysis...
Failed to execute (Optimized Hot Spot Analysis).
Failed at Mon May 04 07:40:22 2015 (Elapsed Time: 0.35 seconds)
```

* [x] Like some of the other IA tools the output hot spots are NOT using the included *HotSpotsByArea.lyr* for symbology.

![image](https://cloud.githubusercontent.com/assets/3093182/7455888/c52c8f58-f234-11e4-8c6a-db58f5ea4b9c.png)

**Comment by mfunk** [comment]
@nfeuerstein @dfoll I notice that this tool is in the Pro toolbox (Incident Analysis Tools.tbx) but *NOT* in the 10.3 toolbox (Incident Analysis Tools_10.3.tbx). I don't think this is right, but I could be wrong. Should it be in both toolboxes?

**Comment by nfeuerstein** [comment]
@mfunk You're correct.  It should live in both toolboxes.
