### ISSUE TITLE
Import NetCDF File throws warning at 10.2.2 and Pro

### ISSUE THREAD

**Issue by jrweakland** [Esri/solutions-geoprocessing-toolbox#269]
_From @mfunk on April 22, 2014 21:56_

Came across this warning using the 'forecast.nc' file included with the MAoW template. For some reason it seems to have trouble doing conversions (and also derivatives). The error (actually Warning) is:

*ConvertMetresToFeet_maow("Cloud Ceiling__", "C:\Data\MyData\MAoW_Template_1_0\MAoW Template 1.0\Maps\Forecast data\latestforecast.gdb\Cloud_Ceiling__20120115T0300")*

*Calling tool 'ConvertMetresToFeet_maow' with parameters 'Cloud Ceiling__', 'C:\Data\MyData\MAoW_Template_1_0\MAoW Template 1.0\Maps\Forecast data\latestforecast.gdb\Cloud_Ceiling__20120115T0300'*

*Could not find (or encountered error calling) the conversion tool 'ConvertMetresToFeet_maow in C:\Data\MyData\MAoW_Template_1_0\MAoW Template 1.0\Maps\Toolboxes\MAoW Tools.tbx'
<class 'arcgisscripting.ExecuteError'>*

The tools are named correctly (ConvertMetresToFeet **is** in the maow toolbox).

_Copied from original issue: ArcGIS/military-aspects-of-weather-toolbox-RETIRED#1_

**Comment by jrweakland** [comment]
_From @mfunk on April 22, 2014 21:56_

Assigned this to @dmMartin to review for 10.3/Pro using Python 3.4.

**Comment by jrweakland** [comment]
@abrowning80 - This issue needs to be resolved this sprint.

**Comment by abrowning80** [comment]
@jrweakland is this issue now closed?

**Comment by mfunk** [comment]
@jrweakland you guys have a backlog task for this one?

**Comment by jrweakland** [comment]
@abrowning80 - please test at ArcMap 10.2.2 and 10.3. If fixed, please close this issue.

**Comment by abrowning80** [comment]
@jrweakland - have tested on both 10.3 and 10.2 and it all works fine and does not error so will close issue.
