### ISSUE TITLE
Outputs for Radial Line of Sight - Multiple Positions in Pro 

### ISSUE THREAD

**Issue by rfeuerstein** [Esri/solutions-geoprocessing-toolbox#270]
Is the tool designed to produce this many outputs? 

![image](https://cloud.githubusercontent.com/assets/7117658/7638035/f663ce52-fa26-11e4-8e40-ea3a08f1b3e8.png)

**Comment by mfunk** [comment]
I think you've got some intermediate data hanging around in there. Don't know exactly what the output is for each input observer, but there is at least one output for each input observer.

**Comment by mfunk** [comment]
So I'm thinking this may be something that is resolved in the 'dev' branch vs. the 2.0.0 release. Currently the results in Pro 1.2 look like this:

![image](https://cloud.githubusercontent.com/assets/3093182/9795736/3c69dd46-57a7-11e5-988b-bbc2c6a43994.png)
