### ISSUE TITLE
Trajectory

### ISSUE THREAD

**Issue by ihssan** [Esri/solutions-geoprocessing-toolbox#272]
when my Trajectory tools work recive this erro number ERROR 000732

**Comment by mfunk** [comment]
@jrweakland when you assign issues, would you also label them. Thanks.

**Comment by mfunk** [comment]
Hello @ihssan 
Would you tell us a little more about the issue you've come across? Can you include the tool dialog text along with the error messages? The error message 000732 (http://resources.arcgis.com/en/help/main/10.1/index.html#//00vp00000017000732) relates to a problem with a dataset. Without more information I can only guess that it has to do with the Input Surface. Are you using a raster dataset, a mosaic, or a service? 
Thank you.

**Comment by ihssan** [comment]
hello @mfunk 
i used dem raster an this images about my erros
![capture](https://cloud.githubusercontent.com/assets/8255414/7830891/fe3bb382-0459-11e5-9053-79315f9dc03c.JPG)
thanks u

**Comment by mfunk** [comment]
@ihssan 
From the dialog picture above it seems you are trying to save **test2** to a folder **D:\test_tools**, but the dataset is missing a *.SHP* extension. Normally the tool's dialog should add this for you. I do not know why it would not.

**Comment by mfunk** [comment]
@ihssan Hi, can you check this one out and verify if it is a missing *.shp* on the end of the output? Thanks.
