### ISSUE TITLE
The Hot Spots by Area tool should have more robust checking for names that will trip up the tool

### ISSUE THREAD

**Issue by dfoll** [Esri/solutions-geoprocessing-toolbox#275]
The Hot Spots by Area model tool creates several outputs... these outputs are created by concatenating a value from a field with "_HotSpots". In the model, this is done in the Calculate Value step of the model. The code block currently checks for a hyphen in the value and replaces it with nothing, then does the appending... we should be more robust to check for things like spaces or  commas
 d=n.replace("-", "")
  d=d+"_HotSpots"

**Comment by mfunk** [comment]
So the tool is giving you something like:
1_HotSpots
2_HotSpots
3_HotSpots
4_HotSpots

So you want to also have it look at removing spaces and commas. Anything else?

**Comment by mfunk** [comment]
Currently the code in **Calculate Value** is as follows:
```
def createOutputName(n):
  d=n.replace("-", "")
  d=d+"_HotSpots"
  return d
```

**Comment by mfunk** [comment]
@dfoll I updated **Hot Spot by Area** in both the 10.3 and Pro toolboxes with the above code. I need you to get the latest from **dev** and test it out and see if it is acceptable.

**Comment by dfoll** [comment]
verified
