### ISSUE TITLE
Point of Origin Detection - ArcGIS Pro - Tool Validator function to select Weapons table is modified by the Share as Project Template process. 

### ISSUE THREAD

**Issue by pshowalter** [Esri/solutions-geoprocessing-toolbox#277]
[#BUG-000088621 When there is a string variable in the tool validator class of a script tool created from a project template, it gets replaced by an esri variable: 
g_ESRI_variable_1 = os.path.join(arcpy.env.packageWorkspace,) ]

There is a nice feature in the Desktop version that selects Weapons table automatically for you based on the expected Project.gdb.  This functionality  does not carry through when "Share as Project Template" is used in Pro released version or daily builds tested in June.

(previously erroneously posted in arcgis-solutions-website )

**Comment by pshowalter** [comment]
The status of Esri BUG-000088621 - When there is a string variable in the tool validator class of a script tool created from a project template, it gets replaced by an esri variable:
g_ESRI_variable_1 = os.path.join(arcpy.env.packageWorkspace,) - that you have been associated with has been changed to Closed with a reason of: Will Not Be Addressed.
Public Explanation: Packaging can change data paths (including partial ones)

If you would like to view additional information about this bug, please login to the Esri My Support Portal http://support.esri.com/en/ and enter BUG-000088621 in the search.

**Comment by jrweakland** [comment]
@pshowalter - Can you please track this down with the dev team?

**Comment by pshowalter** [comment]
Anyone specific that I should talk to on dev team?   

Bug Status is:  Closed: Will Not be Addressed.  
Work around is take out some of the validation code, and have user browse to the Weapons table.  
http://support.esri.com/en/bugs/nimbus/role/beta10_1/QlVHLTAwMDA4ODYyMQ==

**Comment by mfunk** [comment]
First person I would talk to would be Drew Flater as he is on GP team and is working on Pro.

**Comment by jrweakland** [comment]
@pshowalter - maybe talk to @erikreid about this for a workaround. He had the same kind of issue for the Military Aspects of Terrain (MAoT) template.

**Comment by csmoore** [comment]
Just for everyone's benefit that might not have been on @erikreid 's email. He discovered 2 issues/workaounds when packaging Pro **Project Templates** that use custom scripts:

1. Custom toolboxes (ex. toolboxes with scripts) can’t be the default toolbox in the Pro Project (you will have 1 extra toolbox in the project)
2. Tools that use custom python scripts must check “Import Script”

![protemplateworkaround](https://cloud.githubusercontent.com/assets/3090809/8594516/6be9e2f6-260f-11e5-88dc-e57de1629ba1.png)

**Comment by pshowalter** [comment]
@erikreid 
Do you have a Pro template for MAoT that I can check out?

**Comment by jrweakland** [comment]
https://nsec.esri.com/arcgis/home/item.html?id=87f169b7dd324279b2a1bc49ea33706c

**Comment by pshowalter** [comment]
Perhaps we have an indexing issue?  I did search nsec portal for "maot", and "Military Aspects of Terrain" using "Search All Content" it returned:
https://nsec.esri.com/arcgis/home/item.html?id=bfd513dd62d345bcb07a13aaf3a1e1fc and the tag libraries.

**Comment by mfunk** [comment]
@pshowalter In your initial description of the problem:

*When there is a string variable in the tool validator class of a script tool created from a project template, it gets replaced by an esri variable:
g_ESRI_variable_1 = os.path.join(arcpy.env.packageWorkspace,)*

... you say *a string variable* do you mean  ANY string variable, a specific string variable, a random string variable, or something else. I'm not clear on which variable it decides to change. I'm asking because I instituted some logic in another tool's tool validator to handle the path to it's  tooldata folder:

```
  def getDefaultGDBPath(a):
    ''' figure out where the tooldata geodatabase is '''
    tbxPath = sys.path[0]
    if os.path.exists(os.path.join(os.path.dirname(tbxPath),r"p1",r"military_aspects_of_terrain_tools.gdb") ):
      # USE THIS ONE WHEN PACKAGING TO MAKE SURE THE LINKS TO THE TABLES DON'T BREAK.
      p = os.path.join(os.path.dirname(tbxPath),r"p1",r"military_aspects_of_terrain_tools.gdb")
    elif os.path.exists(os.path.join(os.path.dirname(tbxPath),r"toolboxes",r"tooldata",r"Military Aspects of Terrain Tools.gdb")):
      # THIS ONE SHOULD BE CORRECT EVERYWHERE ELSE
      p = os.path.join(os.path.dirname(tbxPath),r"toolboxes",r"tooldata",r"Military Aspects of Terrain Tools.gdb")
    else:
      p = ""
    return p
```
So I'm now concerned that the Pro packaging will mess up my attempts to fix the problem ahead of time. I checked BUG-000088621 and it doesn't seem that anything has been added to it (or done with it).

**Comment by pshowalter** [comment]
The Share as Project Template process would detect a GDB location in the validation code and inserts a variable in the result that pointed to a GDB in user profile, that did not exist.
The following did not work.  The Sharing process would replace"
```python 
defaultGDBPath = os.path.join(os.path.dirname(tbxPath),r"PointOfOriginDetection", r"PointOfOriginDetection.gdb")
```
with
```python
g_ESRI_variable_1 = os.path.join(arcpy.env.packageWorkspace,"pointoforigindetection.gdb")
````
And this points to C:\Users\<username>\AppData\Roaming\Esri folder.  So the snippet below with tbxPath and defaultGDBPath would not work.
```python
def initializeParameters(self):
    """Refine the properties of a tool's parameters.  This method is
    called when the tool is opened."""
    tbxPath = os.path.join(os.path.dirname(__file__))
    defaultGDBPath = os.path.join(os.path.dirname(tbxPath),r"PointOfOriginDetection", r"PointOfOriginDetection.gdb")
    weaponsTable = str(os.path.join(defaultGDBPath,r"Weapons"))
```
The code below worked, and was less hard coded, except for "weapons" table name:
```python
def initializeParameters(self):
   """Refine the properties of a tool's parameters.  This method is
    called when the tool is opened."""
    aprx = arcpy.mp.ArcGISProject("CURRENT")
    weaponsTable = str(os.path.join(aprx.defaultGeodatabase,r"weapons"))
```
The Share as Project Template process will change validation code a bit:
```python
# Esri start of added variables
g_ESRI_variable_1 = 'Weapons'
# Esri end of added variables

def initializeParameters(self):
    """Refine the properties of a tool's parameters.  This method is
    called when the tool is opened."""

    aprx = arcpy.mp.ArcGISProject("CURRENT")
    weaponsTable = str(os.path.join(aprx.defaultGeodatabase,g_ESRI_variable_1))
    #arcpy.AddMessage(weaponsTable)
```
But it will work.  

I see you have the r"p1" in the path;  I don't recall that the r"p1" ever showed up in a Shared Template but may be used by something I am unaware of.

Other:
Assumption is the Pro project is using a folder with a GDB and a Toolbox in the project folder (usually same name as project).  Also assumes the "weapons" table is in the project default GDB.  Not using "\tooldata", as it was causing problems early in the development, so moved that data into the default project GDB.  Also, PointOfOriginDetecton relies on existing .aprx files, which you have to add as "attachments"; they get extracted to a folder such as: \PointOfOriginDetection\commondata\userdata, which you don't have control over.

**Comment by mfunk** [comment]
This is going to be an issue with many of our Python scripted tools in Pro, where Pro will change paths in the scripts. Moving to the next release.

**Comment by mfunk** [comment]
Point Of Origin template has moved to Mature Support, and this toolbox along with it. This issue is being closed as the tool will not be worked on any more.
#461
