### ISSUE TITLE
Change Sample Data Dates to Recent Dates throws syntax error

### ISSUE THREAD

**Issue by ScottCecilio** [Esri/solutions-geoprocessing-toolbox#278]
When trying to update dates of Incidents via Pro 1.1 Build 1.1.3308. I received the following error:

![image](https://cloud.githubusercontent.com/assets/6999909/8697508/74f3e596-2ac3-11e5-80d0-ae8356a28759.png)

**Comment by mfunk** [comment]
@ScottCecilio can you get the latest changes from the **dev** branch and see if it still throws the error. I think I fixed this along with adding automated tests for the tool.

**Comment by ScottCecilio** [comment]
This is now functioning as expected.  Thanks.
