### ISSUE TITLE
Is failonerror="true" a good option for complete testing?

### ISSUE THREAD

**Issue by mfunk** [Esri/solutions-geoprocessing-toolbox#292]
Currently the build.xml test files all set *failonerror="true"*, which causes ANT to stop once the first test fails. It does NOT continue with subsequent tests. I'd like to switch this to *failonerror="false"*, which will show the errors posted by the test and then continue on with the next test.

For the best case we might want to write out an error log to note what test failed and what the error was.

**Comment by csmoore** [comment]
I think this was done so if we used a automated build/test server like Jenkins, Jenkins would be notified of the failure - things might still work though, we would just need to test

**Comment by csmoore** [comment]
I think this can be closed now as a result of the test refactor work that @JudTown17 is doing - so just wanted to check.
