### ISSUE TITLE
Add error logging capability during testing

### ISSUE THREAD

**Issue by mfunk** [Esri/solutions-geoprocessing-toolbox#293]
Rather than stop the test at the first failure the test should log the error and continue. This will require a  logging to a central location (single file, database, etc.) from any number of tests run, at any level. It should capture which test failed, when it failed (date/time stamp), and what the error was.

**Comment by csmoore** [comment]
Sounds like we should probably:

1. Switch the output to use the python logger: https://docs.python.org/2/library/logging.html
2. Change the custom python test scripts to not return an exit code (or we could also switch these to use pyunit - but would be more work)

**Comment by mfunk** [comment]
Judson's work on the pilot project for *logging* and *unittest* are included in #308.

**Comment by mfunk** [comment]
Status update as the unittest building progresses we've got this one working, where *TestRunner.py* calls a named logger (setting a unique log file) from *UnitTestUtilities.py* and puts it into *.\solutions-geoprocessing-toolbox\utils\test\log*.
