### ISSUE TITLE
NumberFeatures.py throwing syntax error

### ISSUE THREAD

**Issue by ScottCecilio** [Esri/solutions-geoprocessing-toolbox#296]
Downloaded a fresh copy from both master version and dev and received the following error.

![image](https://cloud.githubusercontent.com/assets/6999909/9333584/8d6dde5c-4598-11e5-86dc-c008c9f414e8.png)

**Comment by pshowalter** [comment]
Are you using Pro 1.1?
If yes, there are 2 places to change:

if gisVersion == "1.0": #Pro: to 

if gisVersion == "1.1": #Pro:

**Comment by ScottCecilio** [comment]
@jrweakland and @pshowalter I am using 1.1.  I asked @garys-esri to look at this for me and he provided me the following code, https://raw.githubusercontent.com/garys-esri/solutions-geoprocessing-toolbox/master/operational_graphics/toolboxes/scripts/NumberFeatures.py,  so far this seems to make it functional again.

**Comment by garys-esri** [comment]
I submitted #297 to fix this.

**Comment by jrweakland** [comment]
:+1:

**Comment by garys-esri** [comment]
#297 was merged. I believe it fixes this issue, but if @ScottCecilio or someone else could verify and close this issue, that would be better than me closing it myself.
