### ISSUE TITLE
Handling ArcMap vs. ArcGIS Pro vs. other stuff

### ISSUE THREAD

**Issue by mfunk** [Esri/solutions-geoprocessing-toolbox#299]
Moved conversation from #297

**Comment by mfunk** [comment]
So I'm trying to figure out a good starting point to determine what the best sequence is for figuring out if a tool is running in ArcMap, ArcGIS Pro, or something else (say ArcCatalog/Globe/Scene).

Looking at combing the stuff @garys-esri did and @pshowalter worked on I've come up with this snippet that might work.
```
import os
import arcpy
import sys
import traceback

try:
    m = "Some initial stuff..."
    print(m)
    arcpy.AddMessage(m)
    m = "Version " + str(arcpy.GetInstallInfo()["Version"])
    print(m)
    arcpy.AddMessage(m)
    
    try:
        '''first check for Pro'''
        from arcpy import mp
        m = "ArcGIS Pro"
        print(m)
        arcpy.AddMessage(m)
        # Do ArcGIS Pro stuff here
    except ImportError:
        m = "Not ArcGIS Pro"
        print(m)
        arcpy.AddMessage(m)
        try:
            '''check if ArcMap'''
            from arcpy import mapping
            mxd = arcpy.mapping.MapDocument("CURRENT")
            m = "ArcMap"
            print(m)
            arcpy.AddMessage(m)
            # Do ArcMap stuff here
        except:
            ''' Here is where we do stuff for other apps'''
            m = "Not ArcMap"
            arcpy.AddMessage(m)
            print(m)
            # Do other app (ArcCatalog,etc) here
    finally:
        m = "End of script"
        arcpy.AddMessage(m)
        print(m)
        # Do end-of-script stuff here

except:
    ''' Generic error stuff'''
    tb = sys.exc_info()[2]
    tbinfo = traceback.format_tb(tb)[0]
    m = "ERROR:\n Traceback Info: \n" + str(tbinfo) + "Error Info:\n" + str(sys.exc_info()[1])
    arcpy.AddError(m)
    print(m)
```


If I run this in ArcCatalog 10.3.1:
```
Executing: VersionCheck
Start Time: Wed Aug 19 08:49:47 2015
Running script VersionCheck...
Some initial stuff...
Version 10.3.1
Not ArcGIS Pro
Not ArcMap
End of script
Completed script VersionCheck...
Succeeded at Wed Aug 19 08:49:47 2015 (Elapsed Time: 0.03 seconds)
```

If I run this in ArcMap 10.3.1:
```
Executing: VersionCheck
Start Time: Wed Aug 19 08:44:51 2015
Running script VersionCheck...
Some initial stuff...
Version 10.3.1
Not ArcGIS Pro
ArcMap
End of script
Completed script VersionCheck...
Succeeded at Wed Aug 19 08:44:51 2015 (Elapsed Time: 0.07 seconds)
```

And if I run this in ArcGIS Pro:
```
Start Time: Wed Aug 19 08:54:30 2015
Running script VersionCheck...
Some initial stuff...
Version 1.2
ArcGIS Pro
End of script
Completed script VersionCheck...
Succeeded at Wed Aug 19 08:54:30 2015 (Elapsed Time: 0.00 seconds)
```

Can someone make this better? (please!)

**Comment by csmoore** [comment]
Do you really care what product that the script is running in (does script need to know? possibly/probably not) or just that the script works in each of those environments (more of a testing issue).

So are you saying you need to know the ArcGIS product/version & Python/version or that the scripts should be written (and tested) so they are robust with respect to:

1. Python 2 or 3 
    1. Guard version specific features (ex. if sys.version > '3' : ...then)
2. Product Standalone ArcPy / Modelbuilder / ArcMap / Pro / etc.
    1. Guard Product/Library specific features/differences (ex. mapping vs. mp)
3. Product Version
    1. Guard if using some feature only available in a newer version
    2. Guard something that requires a workaround because of a change in behavior on a newer/older version

So for an example of case 1, csv changed from python 2 to 3, so a script using this, needs to have a guard to check for this :

```
if sys.version < '3': 
	csv_fp=open(inputFile, 'rb')
else: 
	csv_fp=open(inputFile, 'r')
```

**Comment by mfunk** [comment]
For our purposes we need to know if it's ArcMap, or ArcGIS Pro, or something else. Because adding layers to a MXD is different than adding it to a project, and can't be done at all in, say, ArcCatalog ... or in these test we are writing. Make sense?

Mike Miller made a suggestion that it might work better in it's own separate module, where an **ImportError** wouldn't be affected by subsequent errors from bad import statements.

```
import arcpy

def GetApplication():
    '''Return ARCMAP, ARCGIS_PRO, OTHER'''
    try:
        from arcpy import mp
        return "ARCGIS_PRO"
    except ImportError:
        try:
            from arcpy import mapping
            mxd = arcpy.mapping.MapDocument("CURRENT")
            return "ARCMAP"
        except:
            return "OTHER"


def main():
    m = "Some initial stuff..."
    print(m)
    arcpy.AddMessage(m)
    m = "Version " + str(arcpy.GetInstallInfo()["Version"])
    print(m)
    arcpy.AddMessage(m)
    m = "GetApplication returns: " + GetApplication()
    arcpy.AddMessage(m)
    print(m)


# MAIN =============================================
if __name__ == "__main__":
    main()
```

**Comment by pshowalter** [comment]
I am sure this could be cleaner.  
For the record, PointOfOrigin.py has a guard in a section of the code shared by Desktop and Pro, which is a Python 2 / Python 3 issue related to cursors.  

```python
        if gisVersion in desktopVersion or gisVersion == "1.0":
            record = cursor.next() # this is method for Pro 1.0.2, 
        else:
            record = next(cursor) # Python 3 method - but only works in Pro 1.1 later builds.
```

**Comment by csmoore** [comment]
@pshowalter for something like iterating through a cursor, you could also try to find a pattern that works in both environments ex: `for feature in cursor : ` (if possible & the legacy code isn't too complex/arcane)

I *think* `next(cursor)` should also work in Python 2, but at Python 3 it now throws a "StopIteration" exception when at the end (which would need handled in the Python 2/3 code)

**Comment by mfunk** [comment]
So I've been using the **GetApplication()** method to fix a few scripts now and it looks like it's working really well (so far) and is doing a good job of distinguishing between ArcMap, ArcGIS Pro and 'everything else'. Going to close this one out.

**Comment by csmoore** [comment]
Do you have an example of the final working code in this repo (I couldn't find doing using the github search, but it may not be searching all the branches)?  

If you used the method/version from @MikeMillerGIS above, the only improvement I would suggest, for performance reasons, is to add a check so it needs to do this check only once, otherwise there will be a performance penalty in environments where those exceptions get raised repeatedly.

Below is a modified example of the above, that only does the import/throws the exception once (I used a class for demo purposes, but this could just as easily be done in the same file/module)

But I still caution to only use this method where absolutely necessary and not for things like iterating over cursors and dictionaries which should be converted to something that works in both Python 2 and 3 (the timely subject of our next Python Team meeting I believe)

```
import arcpy

class ArcGisApplicationGetter() :

	app_found = 'NOT_SET'

	@staticmethod
	def GetApplication():

		if ArcGisApplicationGetter.app_found != 'NOT_SET' :  
			return ArcGisApplicationGetter.app_found

		'''Return ARCMAP, ARCGIS_PRO, OTHER'''
		try:
			from arcpy import mp
			ArcGisApplicationGetter.app_found = "ARCGIS_PRO"
		except ImportError:
			try:
				from arcpy import mapping
				mxd = arcpy.mapping.MapDocument("CURRENT")
				ArcGisApplicationGetter.app_found = "ARCMAP"
			except:
				ArcGisApplicationGetter.app_found = "OTHER"

		return ArcGisApplicationGetter.app_found

def main():
    m = "Some initial stuff..."
    print(m)
    arcpy.AddMessage(m)
    m = "Version " + str(arcpy.GetInstallInfo()["Version"])
    print(m)
    arcpy.AddMessage(m)
    m = "GetApplication returns: " + ArcGisApplicationGetter.GetApplication()
    arcpy.AddMessage(m)
    print(m)
    m = "GetApplication returns: " + ArcGisApplicationGetter.GetApplication()
    arcpy.AddMessage(m)
    print(m)


# MAIN =============================================
if __name__ == "__main__":
    main()
```
