### ISSUE TITLE
HELP! Need ideas for adding features to ArcGIS Pro with ArcPy

### ISSUE THREAD

**Issue by mfunk** [Esri/solutions-geoprocessing-toolbox#304]
So the problem is that I can't figure out a good way to use **arcpy.mp**  (for ArcGIS Pro) to a map. The API is different than that of ArcMap so the methods are not transferrable. Currently I have been testing the following snippet:

```
...
        targetLayerName = os.path.basename(outputFeatureClass)
        if appEnvironment == "ARCGIS_PRO":
            #TODO: figure out how to add features to the current map in Pro
            #Currently this fails on 'mapList.addLayer' with no useful error message
            arcpy.MakeFeatureLayer_management(outputFeatureClass, targetLayerName)
            mapList.addLayer(targetLayerName, "AUTO_ARRANGE")
            layer = findLayerByName(targetLayerName)
            if (layer):
                arcpy.AddMessage("Labeling grids")
                labelFeatures(layer, gridField)
            #arcpy.AddWarning("Cannot label output in Pro at this time.")
        elif appEnvironment == "ARCMAP":
...
```

Unfortunately this fails with:

```
...
Adding field for labeling the grid
Numbering the grids
PYTHON ERRORS:
Traceback info:
  File "C:\Users\matt2542\Documents\GitHub\solutions-geoprocessing-toolbox\operational_graphics\toolboxes\Scripts\PointTargetGRG.py", line 535, in main
    mapList.addLayer(targetLayerName, "AUTO_ARRANGE")

Error Info:
outPointGRG_agp
ArcPy ERRORS:
Executing: MakeFeatureLayer C:\Users\matt2542\Documents\GitHub\solutions-geoprocessing-toolbox\operational_graphics\data\geodatabases\scratch.gdb\outPointGRG_agp outPointGRG_agp # # "OBJECTID OBJECTID VISIBLE NONE;Shape Shape VISIBLE NONE;Grid Grid VISIBLE NONE;Shape_Length Shape_Length VISIBLE NONE;Shape_Area Shape_Area VISIBLE NONE"
Start Time: Thu Aug 27 10:34:02 2015
Succeeded at Thu Aug 27 10:34:02 2015 (Elapsed Time: 0.11 seconds)
Completed script PointTargetGRGScript...
Failed to execute (Point Target GRG Script).
...
```
I can't find any useful documentation on ArcPy or arcpy.mp that tells how to add a *feature* or *featureclass* to a map. There are plenty that show how to add a *lyr* or *lyrx*, but not features. So i'm looking for suggestions or ideas.

**Comment by pshowalter** [comment]
*>>So i'm looking for suggestions or ideas.*

I think you have most of the stuff that was used in PointofOrigin.py, which relies of .lyrx files existing in known location.  The approach take by the developer was to add "empty" Group Layer then add Layer(s) to the Group Layer, and change the name of the Group Layer.   

New to me was the use of result object.
```python
results = arcpy.MakeFeatureLayer_management(outputImpactPointFeatures,ipName, None, None).getOutput(0)
...
arcpy.ApplySymbologyFromLayer_management(results,impactPointLayerFilePath) 
...
m.addLayerToGroup(topGroupLayer,results,"TOP")
```
If you don't want to use a Group Layer, then you will still need a way to move the  individual Layers out of the group... so your request for help still stands.

**Comment by mfunk** [comment]
WHOO HOO!!! @pshowalter, you got me headed in the right direction. Instead of passing the layer name string 'targetLayerName', I used the results in *.addLayer* and it is working (so far)

```
results = arcpy.MakeFeatureLayer_management(outputFeatureClass, targetLayerName).getOutput(0)
mapList.addLayer(results, "AUTO_ARRANGE")
```
