### ISSUE TITLE
test_maot is throwing a warning with ImportToolbox

### ISSUE THREAD

**Issue by mfunk** [Esri/solutions-geoprocessing-toolbox#306]
In each of the two tests (test_range_fan, test_local_peaks) give the following message with **ImportToolbox**:

```
[exec] ERROR LOADING VEHICLE TABLE
[exec] ERROR LOADING VEHICLE TABLE
[exec] ERROR LOADING VEHICLE TABLE
[exec] ERROR LOADING VEHICLE TABLE
[exec] ERROR LOADING VEHICLE TABLE
[exec] ERROR LOADING VEHICLE TABLE
[exec] ERROR LOADING VEHICLE TABLE
[exec] ERROR LOADING VEHICLE TABLE
[exec] ERROR LOADING VEHICLE TABLE
[exec] ERROR LOADING VEHICLE TABLE
[exec] ERROR LOADING VEHICLE TABLE
[exec] ERROR LOADING VEHICLE TABLE
[exec] ERROR LOADING VEHICLE TABLE
[exec] ERROR LOADING VEHICLE TABLE
[exec] ERROR LOADING VEHICLE TABLE
[exec] ERROR LOADING VEHICLE TABLE
[exec] ERROR LOADING VEHICLE TABLE
[exec] ERROR LOADING VEHICLE TABLE
[exec] ERROR LOADING VEHICLE TABLE
[exec] ERROR LOADING VEHICLE TABLE
```

The line in the test code (using test_local_peaks) is:
```arcpy.ImportToolbox(TestUtilities.toolbox, "MAoT")```

The message isn't causing the tests or tools to fail, but it is annoying and should be taken care of. The only other tools in the toolbox that use a *vehicle table* are the CCM tools: **FM 5-33 CCM**, and **Raster Off-road Mobility**. And sure enough, when you open one of the tools (FM 5-33 CCM) you get this:

![image](https://cloud.githubusercontent.com/assets/3093182/9552557/e72ffa6a-4d6d-11e5-98aa-9a613ebb95a4.png)

If you take a look at the error it's pointing to a path that doesn't exist:
*C:\Users\<user>\Documents\GitHub\solutions-geoprocessing-toolbox\suitability\Tools\tooldata\Military Aspects of Terrain Tools.gdb\maotVehicleParameters*

Instead it should be pointing to:

*C:\Users\matt2542\Documents\GitHub\solutions-geoprocessing-toolbox\suitability\toolboxes\tooldata\Military Aspects of Terrain Tools.gdb\maotVehicleParameters*

Resetting this path to the correct location throws a new error in the dialog:

![image](https://cloud.githubusercontent.com/assets/3093182/9552594/396e011e-4d6e-11e5-86f2-f424e479c1e6.png)

If you remove the "ERROR LOADING VEHICLE TABLE" from the input parameter, the error goes away.

As it turns out the tool's validation code is causing the problem. Under *initializeParameters(self)* you'll see the following lines:
```
    defaultGDBPath = os.path.join(os.path.dirname(tbxPath),r"Tools",r"tooldata",r"Military Aspects of Terrain Tools.gdb")
    #defaultGDBPath = os.path.join(os.path.dirname(tbxPath),r"toolboxes",r"tooldata",r"Military Aspects of Terrain Tools.gdb")
```

The uncommented line (with "Tools" is the problem here. But this was done deliberately because the CORRECT line (with "toolboxes") is commented. So I'm thinking that something else is going on here.

**Comment by mfunk** [comment]
Nailed it.

In the tool validation for **FM 5-33 CCM** and **Raster Off-road Mobility** I added some logic for handling the path to the tooldata. First I added a method for finding the tooldata geodatabase:

```
  def getDefaultGDBPath(a):
    ''' figure out where the tooldata geodatabase is '''
    tbxPath = sys.path[0]
    if os.path.exists(os.path.join(os.path.dirname(tbxPath),r"p1",r"military_aspects_of_terrain_tools.gdb") ):
      # USE THIS ONE WHEN PACKAGING TO MAKE SURE THE LINKS TO THE TABLES DON'T BREAK.
      p = os.path.join(os.path.dirname(tbxPath),r"p1",r"military_aspects_of_terrain_tools.gdb")
    elif os.path.exists(os.path.join(os.path.dirname(tbxPath),r"toolboxes",r"tooldata",r"Military Aspects of Terrain Tools.gdb")):
      # THIS ONE SHOULD BE CORRECT EVERYWHERE ELSE
      p = os.path.join(os.path.dirname(tbxPath),r"toolboxes",r"tooldata",r"Military Aspects of Terrain Tools.gdb")
    else:
      p = ""
    return p
```

And then I added the method to the validation code...

```
    # Set vehicle Table
    defaultGDBPath = getDefaultGDBPath()
    vehicleParamsTable = str(os.path.join(defaultGDBPath,r"maotVehicleParameters"))
    self.params[1].value = vehicleParamsTable
```

This seems to work for this round. Will have to work with @jrweakland and see how it works in Pro.

**Comment by BobBooth** [comment]
@mfunk - I'm not sure that the "p1" is always the same - I have a project that I packaged and it has "p11" in the path.

**Comment by csmoore** [comment]
Sounds like it might perhaps be version (1.0 vs. 1.1) dependent (and yet another thing you would have to suss out...I miss mxds...)

**Comment by mfunk** [comment]
love my job
