### ISSUE TITLE
Radial Line Of Sight - Multiple Positions error in Pro

### ISSUE THREAD

**Issue by mfunk** [Esri/solutions-geoprocessing-toolbox#309]
Tried running **Radial Line Of Sight - Multiple Positions** tool using the test data from V&R tools:
1. Set the following inputs:
    Input Feature: _C:\Users\matt2542\Documents\GitHub\solutions-geoprocessing-toolbox\visibility\data\geodatabases\test_vis_and_range_inputs.gdb\RlosObserverWebMerc_
    Defensive Position Description Field: _OBJECTID_
    Defensive Position Height Field: _Observer offset_
    Input Elevation Surface: _C:\Users<user>\Documents\GitHub\solutions-geoprocessing-toolbox\visibility\data\geodatabases\test_vis_and_range_inputs.gdb\Jbad_SRTM_USGS_EROS_
    Output Workspace:_C:\Users<user>\Documents\ArcGIS\Projects\MyProject8\MyProject8.gdb_
    Output Prefix: _vsPro_
2. Run the tool:

```
Start Time: Wed Sep 09 14:56:57 2015
Executing (Radial Line of Sight - Multiple Towers): TowersRadialLineOfSight2 Jbad_SRTM_USGS_EROS false RlosObserverWebMerc OBJECTID OFFSETA C:\Users\matt2542\Documents\ArcGIS\Projects\MyProject8\MyProject8.gdb vsPro
Start Time: Wed Sep 09 14:56:58 2015
Running script TowersRadialLineOfSight2...
RLOS will use local RADIUS2 values for calculation.
Input surface is Jbad_SRTM_USGS_EROS
Force visibility is False
Tower Feature Class is RlosObserverWebMerc
Tower Name Field is OBJECTID
Tower Height Field is OFFSETA
Output Visibility is C:\Users\matt2542\Documents\ArcGIS\Projects\MyProject8\MyProject8.gdb
Output Feature Class Prefix is vsPro
Scrubbed Feature Class Prefix is vsPro
Setting snap raster to: Jbad_SRTM_USGS_EROS
Processing tower 1 of 4
PYTHON ERRORS:
Traceback info:
  File "C:\Users\matt2542\Documents\GitHub\solutions-geoprocessing-toolbox\visibility\toolboxes\scripts\TowersLOS.py", line 147, in <module>
    scrubbedTowerName = ''.join(e for e in towerName if (e.isalnum() or e == " " or e == "_"))

Error Info:
'int' object is not iterable
ArcPy ERRORS:
Executing: GetCount RlosObserverWebMerc
Start Time: Wed Sep 09 14:57:02 2015
Row Count = 4
Succeeded at Wed Sep 09 14:57:02 2015 (Elapsed Time: 0.00 seconds)
Removing intermediate datasets...
Done
Completed script TowersRadialLineOfSight2...
Failed to execute (Radial Line of Sight - Multiple Towers).
Failed at Wed Sep 09 14:57:02 2015 (Elapsed Time: 4.42 seconds)
Failed to execute (RadialLineofSightMultiplePositions).
Failed at Wed Sep 09 14:57:02 2015 (Elapsed Time: 4.76 seconds)
```

The error reports line 147 as the issue:

```
scrubbedTowerName = ''.join(e for e in towerName if (e.isalnum() or e == " " or e == "_"))
```

The error message points to a problem trying to iterate over an integer (number). Line 147 is trying to iterate over a name to change it, but this is'nt possible for a number. These line should check for that and skip it if not possible.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/129342386639048/129373044063235)

**Comment by topowright** [comment]
@mfunk I do not think this is an issue in the newest version of the template that we created for ArcGIS Pro 1.3. Please verify or close.

**Comment by mfunk** [comment]
The tool/toolbox associated with this issue has been deprecated and is no longer actively supported. Earlier versions of this toolbox will still be available from previous [Releases](https://github.com/Esri/solutions-geoprocessing-toolbox/releases)
