### ISSUE TITLE
Update MAoW (Military Aspects of Weather) Version 2.0 of Toolbox

### ISSUE THREAD

**Issue by csmoore** [Esri/solutions-geoprocessing-toolbox#320]
Just a task to get the latest/current version of the MAoW added/updated in this repo.

Discussion started here:
https://github.com/ArcGIS/mil-intel-desktop-solutions-templates/issues/139#issuecomment-144465567

**Comment by mfunk** [comment]
@abrowning80 Can you send me a copy (or a link) of the newest versions of the tools? I've also got stuff to add for the CRU climatic data, that never made it into the earlier toolbox.

**Comment by mfunk** [comment]
I'm reworking some things here to make them more consistent. I'll have the tools updated by the end of the day (I hope).

**Comment by mfunk** [comment]
Fixed in https://github.com/Esri/solutions-geoprocessing-toolbox/pull/353.

@lfunkhouser do you want to take a crack at verifying this one?

**Comment by mfunk** [comment]
Closed this one.
