### ISSUE TITLE
Restrict Count Incidents by LOC operational area

### ISSUE THREAD

**Issue by dfoll** [Esri/solutions-geoprocessing-toolbox#321]
Count Incidents by LOC from the Incident Analysis tool box uses road data and counts how many incidents occured along a particular stretch of road. One step early in the model is that is copies the roads features. From what i can tell, when it does the copy, there is no restriction to what roads it copies... not a concern if you have specifically clipped out just the roads in your aoi, however what if your roads data is a much larger set, say the entire state, or country for that matter. We should do something so that only the roads you are working with are copied

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/129342386639048/129373043932993)

**Comment by mfunk** [comment]
@dfoll  Do you have any thoughts how you would like the users to restrict the roads for this tool? Clip the road features? Document that they should use a selection?

**Comment by dfoll** [comment]
i'd say doing the clip for them would prob be most reasonable ..... "here is the bounds of my incident data... clip the roads to that

**Comment by mfunk** [comment]
@dfoll So is it acceptable that the an AOI clipping are is required? If I use Clip then the input can't be empty, meaning you MUST clip, not optional.

**Comment by mfunk** [comment]
Just an FYI, If I use Mask/Extent environment option to have the AOI as Optional it actually returns a much larger number of features (red) that was expected (teal) based on the input AOI (yellow):

![image](https://cloud.githubusercontent.com/assets/3093182/25545036/f7cc5e20-2c11-11e7-995d-36c2e2ac49ca.png)

**Comment by joebayles** [comment]
IMO, there should be two options here:
1. Restrict by operational area should be optional to run, so leaving it blank should not restrict at all.
2. As a user, I want the choice of including events that happened outside of the AOR, but on LOCs that are in the AOR (i.e., events that happened on the blue lines but outside the yellow circle in the picture. A checkbox would suffice.

**Comment by mfunk** [comment]
@joebayles That's a bit  more than we can accomplish in this sprint. With a Model we don't really have a good If/Then control structure, so an AOR is either required by the tool, or not included in the tool at all. Then to add to that a fuzzy AOR is also a  bit more.. more processing, more time. Are we back to just run it on the whole thing or include the near AOR?

**Comment by joebayles** [comment]
@mfunk agreed, but that doesn't change what the end-state should look like. If we have to iterate on it and that's something for 1.1 or 2.0, I completely understand.

In the meantime, I would suggest leaving the AOR in, and we make mention of the fact that some of the incidents may have occurred outside the AOR but are attributed to an LOC that intersects with the AOR.
