### ISSUE TITLE
Bad Variable in Hot Spots by Area tool

### ISSUE THREAD

**Issue by dfoll** [Esri/solutions-geoprocessing-toolbox#323]
The Hot Spots by Area model uses the Optimized Hot Spot Analysis tool.  The output of the Optimized Hot Spot Analysis tool uses the variable %workspace% ... it is my understanding this is not a good idea and we should update this so that the tool explicitly knows to use a .gdb for this.

![image](https://cloud.githubusercontent.com/assets/5322669/10383017/beb4f590-6dde-11e5-9466-babc105810a1.png)

**Comment by dfoll** [comment]
@mfunk if you would like more to this description, let's talk about this and review while it is still fresh in our minds

**Comment by mfunk** [comment]
The problem was that the %workspace% variable didn't exist. It should have been a named variable or %scratchGDB%.

**Comment by mfunk** [comment]
Fixed for Pro and Desktop models.
