### ISSUE TITLE
HLZ Touchdown Points doc missing slope type

### ISSUE THREAD

**Issue by mfunk** [Esri/solutions-geoprocessing-toolbox#326]
Help for **HLZ Touchdown Points** tool in the *Helicopter Landing Zone Tools* in the *capability* folder needs clarification. Slope can come in two different types: percent or degrees. The tool doesn't seem to make a distinction between the two, so a user could make an argument that it should work with either. However if you look at the included *Aircraft_Specifications* the field *Ground_Slope_Max_Degrees* implies that the unit of slope measure should be degrees. The tool documentation should note this in two places:
1) in the *Input Slope* parameter help, and
2) in the tool *Usage* where a better description can be inserted.

I'm assigning to Natalie to check the requirements for the tool, whether it should be DEGREES or PERCENT and to add the update to both toolboxes.

**Comment by mfunk** [comment]
@jrweakland any idea if these are supposed to be PERCENT or DEGREES?

**Comment by jrweakland** [comment]
PERCENT

**Comment by mfunk** [comment]
Updated tool and doc...
* *Aircraft_Specifications* field name to be: Ground_Slope_Max_Percent.
* *Input_Slope* raster clarified to "Values must be in percent slope."
* Added to *Usage*:

```
•	Input aircraft maximum slope specifications must be in percent slope.
•	Input slope data must be in percent slope.
```
