### ISSUE TITLE
Update the ERG tools for the 2016 version of the guidebook

### ISSUE THREAD

**Issue by mfunk** [Esri/solutions-geoprocessing-toolbox#327]
@jeffbaranyi 

After checking out some recent comments on the ERG tools (under _capability_) I noticed that there is a 2016 version of the Emergency Response Guidebook (the "ERG" where the tools get their name). 

[http://www.phmsa.dot.gov/pv_obj_cache/pv_obj_id_CDF7F93A3E0C2F808D9EA09C262749DAEF400200/filename/ERG2016_Preview.pdf](http://www.phmsa.dot.gov/pv_obj_cache/pv_obj_id_CDF7F93A3E0C2F808D9EA09C262749DAEF400200/filename/ERG2016_Preview.pdf)

The tools are based on the 2012 version. I don't know if there were any changes from 2012 to 2016 to the chemical lists or the placard lists that the tools used.**If so do we want to update the tools to reflect the newer version?**

The tool pulls data from an external DBF file, so an update _should_ be as easy as updating the DBF.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/129342386639048/129373020133360)

**Comment by mfunk** [comment]
Actually the 2016 version of the book hasn't been released YET. But it it supposed to be in early 2016. So we might not get a definite answer for a few months. Hold tight.

**Comment by jeffbaranyi** [comment]
Yes please!  Once these get released we should make this a high priority

**Comment by mfunk** [comment]
Guidebook released: http://www.phmsa.dot.gov/pv_obj_cache/pv_obj_id_E00A3F1FBDEEA9079573D27BDFC571C3FDAC4A00/filename/ERG2016.pdf

**Comment by jeffbaranyi** [comment]
Great!  The updated data files look to be here - http://www.phmsa.dot.gov/hazmat/library/erg#page5

@mfunk @NikkiGolding @conklinbd - can we get our friends across the pond to update the tools and certify these with the latest 2016 guidance?

**Comment by conklinbd** [comment]
@jeffbaranyi this is something we can look at in 3rd Quarter this year.

**Comment by jeffbaranyi** [comment]
@mfunk @NikkiGolding @conklinbd - any updated ETA?  Thanks

**Comment by mfunk** [comment]
@nfeuerstein @lfunkhouser FYI...

**Comment by mfunk** [comment]
The tool/toolbox associated with this issue has been deprecated and is no longer actively supported. Earlier versions of this toolbox will still be available from previous [Releases](https://github.com/Esri/solutions-geoprocessing-toolbox/releases)
