### ISSUE TITLE
Incident Analysis - Find Percent Change tool has no output parameter

### ISSUE THREAD

**Issue by mfunk** [Esri/solutions-geoprocessing-toolbox#328]
**Find Percent Change** in *Incident Analysis* has no output parameter. User has no way of saving results to their own geodatabase, or defining an output name. As it is now, the tool will always overwrite the same output features each time it is run.

![image](https://cloud.githubusercontent.com/assets/3093182/10526951/b6bc2cbe-7342-11e5-932a-6d77e743bca8.png)

This should be an easy change in the model by changing the intermediate tool step ** Feature Class to Feature Class (2)** is set to always write to the %scratchGDB% (user cannot change this) and will always write to a feature class named *Activity_with_JoinCounts*. Instead of **Feature Class to Feature Class** it would be easier to use **Copy Feature** and use the output parameter as a model parameter (P), and give it a default value of "%scratchGDB%\Activity_with_JoinCounts". This way the user can just accept the defaults and run the tool, or specify where the output features are created and what they are named.

**Comment by mfunk** [comment]
Don't forget to reapply the *PercentChange.lyr* to the new output parameter.

**Comment by mfunk** [comment]
@dfoll can you verify this works in the **dev** branch then mark *done*?

**Comment by dfoll** [comment]
verfied

**Comment by dfoll** [comment]
verified
