### ISSUE TITLE
Incident Density has no output parameter

### ISSUE THREAD

**Issue by mfunk** [Esri/solutions-geoprocessing-toolbox#329]
**Incident Density** in *Incident Analysis* has no output parameter. User cannot specify where the output features will be created, and cannot specify what the output features will be named. This should be pretty easy, just making the *Output Features (Incident Hot Spots)* a model parameter (P), and giving it a default value of "%scratchGDB%/DensityHotSpots".

![image](https://cloud.githubusercontent.com/assets/3093182/10528390/c4760ebc-734a-11e5-95bf-c5179d5499a8.png)

**Comment by mfunk** [comment]
@dfoll can you verify this works in the **dev** branch then mark *done*?

**Comment by dfoll** [comment]
verified
