### ISSUE TITLE
Consider an MD on geoprocessing tool standards for the repo

### ISSUE THREAD

**Issue by mfunk** [Esri/solutions-geoprocessing-toolbox#330]
Consider an MD on geoprocessing tool standards.
Based on the Esri tool testing standards.
* Tool, toolset, toolbox naming conventions
* Creating and using parameters for a tool
* Tool doc standards
* When to use models or Python scripts, and when to use PYTs vs. TBX
* Links to python coding standards (pylint, etc.)
* Desktop vs. Pro, Python 2.7 vs. 3.4

**Comment by jrweakland** [comment]
:+1:  - This is an issue that should be discussed during our engineer group meeting. @lfunkhouser

**Comment by mfunk** [comment]
This one is being handled as part of an internal resources repo.
