### ISSUE TITLE
TestPointOfOrigin.py - How do you pass Boolean in test tool to reflect a Check Box in the Script tool?

### ISSUE THREAD

**Issue by pshowalter** [Esri/solutions-geoprocessing-toolbox#334]
@mfunk I would like to modify TestPointOfOrigin.py to reflect the addition of a Checkbox in Script Tool that allows user to specify desire for "True Curves" or they can take the default of densified polygons.  At present the TestPointOfOrigin.py will work to completion w/o error, and uses the default without modifying the code to pass the Boolean, but would be nice to have it pass the parameter, and maybe run both cases for completeness.  Looking for Check Box examples.

```
# Set tool param variables
        inputImpactPoints = os.path.join(TestUtilities.testDataGDB, "impact_pts_monterey_UTM10N")
        inputWeaponsTable = os.path.join(TestUtilities.toolDataGDB, r"Weapons")
        inModelField = 'Model'
        inMinRangeField = 'Minimum_range'
        inMaxRangeField = 'Maximum_range'
        inputWeaponsAsString = ("'M120/121 120-mm American Mortar';'M224 60-mm American Mortar';'M252 81-mm American Mortar'")
        print("inputWeaponsAsString: " + str(inputWeaponsAsString))
        inputWeaponsAsList = inputWeaponsAsString.split(";")
        print("inputWeaponsAsList: " + str(inputWeaponsAsList))
        outputWorkspace = arcpy.env.scratchGDB
        outImpactPrefix = r"imp"
        outPooPrefix = r"poo"
        outRangePrefix = r"rng"
        # WGS_1984_UTM_Zone_10N using factoryCode
        sr = arcpy.SpatialReference(32610)
        # None of the following work - how do you pass Boolean in test tool to reflect a Check Box in the Script tool?
##        outUseTrueCurve = "0"
##        outUseTrueCurve = u"false"
##        outUseTrueCurve = u"0"
##        outUseTrueCurve = u"False"
##        outUseTrueCurve = 0
##        outUseTrueCurve = u"False"
        outUseTrueCurve = True

        # Testing Point Of Origin Site Detection
        arcpy.AddMessage("Starting Test: Point of Origin Site Detection")
        results = arcpy.PointOfOriginSiteDetection_ptorigin(inputImpactPoints, inputWeaponsTable,
                                                            inModelField, inMinRangeField, inMaxRangeField,
                                                            inputWeaponsAsString, outputWorkspace,
                                                            outImpactPrefix, outPooPrefix,
                                                            outRangePrefix, sr, outUseTrueCurve)
```
Here is the error while running the test code:

test_poo_tools:
   [exec] inputWeaponsAsString: 'M120/121 120-mm American Mortar';'M224 60-mm American Mortar';'M252 81-mm American Mortar'
     [exec] inputWeaponsAsList: ["'M120/121 120-mm American Mortar'", "'M224 60-mm American Mortar'", "'M252 81-mm American Mortar'"]
     [exec] Starting Test: Point of Origin Site Detection
     [exec] ERROR: Executing: PointOfOriginSiteDetection C:\myProjects\GitHub\solutions-geoprocessing-toolbox-test\capability\data\geodatabases\test_poo_tools.gdb\impact_pts_monter
ey_UTM10N C:\myProjects\GitHub\solutions-geoprocessing-toolbox-test\capability\toolboxes\tooldata\PointOfOrigin.gdb\Weapons Model Minimum_Range Maximum_Range 'M120/121 120-mm Ameri
can Mortar';'M224 60-mm American Mortar';'M252 81-mm American Mortar' C:\Users\patrick\AppData\Local\Temp\scratch.gdb imp poo rng "PROJCS['WGS_1984_UTM_Zone_10N',GEOGCS['GCS_WGS_19
84',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_E
asting',500000.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',-123.0],PARAMETER['Scale_Factor',0.9996],PARAMETER['Latitude_Of_Origin',0.0],UNIT['Meter',1.0]];-5120
900 -9998100 10000;-100000 10000;-100000 10000;0.001;0.001;0.001;IsHighPrecision" 1
     [exec] Start Time: Thu Oct 22 17:00:55 2015
     [exec] Failed to execute. Parameters are not valid.
**[exec] ERROR 000840: The value is not a Boolean.**
     [exec] Failed to execute (PointOfOriginSiteDetection).
     [exec] Failed at Thu Oct 22 17:00:55 2015 (Elapsed Time: 0.16 seconds)

**Comment by mfunk** [comment]
@pshowalter 
Not sure we want to start messing with the ANT test files now since we are moving to Python unittests. However it should be passed as a Python True/False variable.
```
PointOfOriginSiteDetection_ptorigin (Input_Impact_Points, ..., Use_True_Curves) 
```

In the meantime I found an inconsistency between the Desktop and Pro tools that needs to be addressed in #338.

I'm also seeing that the *Use True Curves* option doesn't have a help description for the parameter.

**Comment by pshowalter** [comment]
@jrweakland  - Did you want me to work issue of passing Boolean into test tool issue, perhaps create a "unittest"?  Or was this in reference to the "Use True Curves" missing description (#338) mentioned directly above this?  
It sounded like working on the existing test scripts was not desired, as they are being updated to python unittests.  The missing Description issue was fixed, and pull submitted in https://github.com/Esri/solutions-geoprocessing-toolbox/pull/341

**Comment by jrweakland** [comment]
@pshowalter - you will need to cordinate with @mfunk when it comes to testing.

**Comment by mfunk** [comment]
Point Of Origin template has moved to Mature Support, and this toolbox along with it. This issue is being closed as the tool will not be worked on any more.
#461
