### ISSUE TITLE
Point Of Origin Site Detection options differ between Desktop and Pro

### ISSUE THREAD

**Issue by mfunk** [Esri/solutions-geoprocessing-toolbox#338]
The **Point Of Origin Site Detection** tool in the _10.3 (Desktop) toolbox has an option *Use True Curves* that is missing in the Pro version.

The picture below shows the differences....

![image](https://cloud.githubusercontent.com/assets/3093182/10742753/01474e42-7bec-11e5-8efb-6f27da20c88a.png)

The option needs to be added to the Pro version of the tool. The option is in the source *PointOfOrigin.py* script, but isn't exposed in the tool dialog.

**Comment by pshowalter** [comment]
I have a working Check Box in the Pro project that I have been using for Share as Project Template.  It lives in a Toolbox that does not have spaces in the name; I made an attempt to reconfigure the Pro project in same style as the repo folders and names, and it did not go  well during the share and restore process, things were broken upon restore.  Perhaps newer release will be compatible.

[cid:image001.jpg@01D11020.D5F5F900]

**Comment by pshowalter** [comment]
Have addressed these in recent pull:
https://github.com/Esri/solutions-geoprocessing-toolbox/pull/341

**Comment by mfunk** [comment]
Need to verify fix.

**Comment by mfunk** [comment]
Fixed:

![image](https://cloud.githubusercontent.com/assets/3093182/11725817/7a633338-9f30-11e5-9a44-b53f8380f858.png)
