### ISSUE TITLE
Patrol Data Capture Toolbox needs some additional tests

### ISSUE THREAD

**Issue by conklinbd** [Esri/solutions-geoprocessing-toolbox#34]
The Patrol Data Capture Toolbox needs to have tests created for all of the tools. This toolbox has a large number of script tools. 

So the following 5 tools do NOT have tests:

- [x] Append Tracks to DB
- [x] Import Patrol Rpt --- Not a great tool name
- [x] Make Track Lines
- [x] Recalculate Delta Times
- [x] Rejoin Track Parts

**Comment by jrweakland** [comment]
So the following 5 tools do NOT have tests:

- [ ] Append Tracks to DB
- [ ] Import Patrol Rpt --- Not a great tool name
- [ ] Make Track Lines
- [ ] Recalculate Delta Times
- [ ] Rejoin Track Parts

**Comment by csmoore** [comment]
Just a follow up : 

You can remove these 3 from the list of those needing tests:

* Make Track Lines
* Recalculate Delta Times
* Rejoin Track Parts

test_distinguish_tracks - calls "Distinguish Tracks" which calls "Make Track Lines" and "Recalculate Delta Times" 
Rejoin Track Parts - requires user input and a user selection so doesn't really make sense in an automated test

Also - it wasn't possible to readily rename "Import Patrol Rpt" because there is already a "Import Patrol Report(.py)" in the toolbox

**Comment by mfunk** [comment]
Just an update on this one. I've added test for **Rejoin Track Parts** and **Import Patrol Report**. I renamed *Import Patrol Rpt* to *Import Patrol Report*, in the process. But currently i'm having issues getting the test to work. Unfortunately the tool is failing with an *Invalid field type* error that is proving difficult to locate.

```
test_import_patrol_rpt:
     [exec] Starting Test: TestImportPatrolRpt
     [exec] Setting up inputs and environment...
     [exec] Number of rows in Patrol Report Table before: 0
     [exec] Number of rows in Enemy Sightings Table before: 0
     [exec] Selecting track OBJECTID = 2 for report...
     [exec] Executing RejoinTrackParts_pdc...
     [exec] ERROR: Executing: ImportPatrolReport inputLinesFC_layer TrackGUID C:\Users\matt2542\Documents\GitHub\solutions-geoprocessing-toolbox\data_management\data\PatrolDataCapture\PatrolReport017.xml C:\Users\matt254
2\Documents\GitHub\solutions-geoprocessing-toolbox\data_management\data\geodatabases\test_patrol_data_capture_inputs.gdb\PatrolReport C:\Users\matt2542\Documents\GitHub\solutions-geoprocessing-toolbox\data_management\dat
a\geodatabases\test_patrol_data_capture_inputs.gdb\EnemySightings
     [exec] Start Time: Fri Aug 14 09:01:08 2015
     [exec] Failed to execute. Parameters are not valid.
     [exec] ERROR 000308: Invalid field type
     [exec] Failed to execute (ImportPatrolReport).
     [exec] Failed at Fri Aug 14 09:01:08 2015 (Elapsed Time: 0.01 seconds)
```

If you use the same inputs in a model, or directly in the tool in ArcMap it works just fine. But inside a script it fails. Still working on this.

**Comment by pshowalter** [comment]
I have seen scripts that run fine on laptop using Python 32, wont run on a server, that defaults to Python 64.  In this case it was differing of the handling of path to a FC.

**Comment by mfunk** [comment]
Thanks @pshowalter but it was something in the model tool that was being tested. I converted it to a script and got it working as it should have been.

To this point the tests are made and running.
