### ISSUE TITLE
Create Additional Labels for Templates

### ISSUE THREAD

**Issue by jrweakland** [Esri/solutions-geoprocessing-toolbox#345]
Should we create additional labels for the templates that contain the tools?

Example: The LLOS tools are in the Visibility and Range template.

This will assist with assigning issues and monitoring progress. 

@lfunkhouser @conklinbd @nfeuerstein

**Comment by mfunk** [comment]
OK. Good idea. But how would we label tools that are not associated with a template, e.g. many of the data management tools? Just skip the label?

I'm feeling a bit mixed about importing the existing label set from the template repo. First I'm not sure why "N" is the template prefix. Second, there are a LOT of templates that don't have GP tools and would just be extra crap in the mix. So would you recommend just adding labels for the templates that are represented here?

**Comment by conklinbd** [comment]
I agree that you should only add the labels for templates with GP tools.
I would like to maintain consistency on the naming convention (N-). I don't know where N came from but it helps us with Waffle or other tools for managing issues accross repositories.

**Comment by mfunk** [comment]
Could we copy the labels over (don't remember what the tool is called) and just remove the 'unused' labels from the list?

@jrweakland any chance you want to do the copy and I'll do the cleanup? :smirk:

**Comment by jrweakland** [comment]
@mfunk - sounds good to me. I will let you know when I need you to review!

**Comment by jrweakland** [comment]
@mfunk - ready for your review.

**Comment by mfunk** [comment]
@jrweakland are *N - Cross-Country Mobility*, *N - Drop Zone Suitability*, and *N - Lines Of Communication* new templates with tools? If so, I only have the MAoT set in suitability.

**Comment by jrweakland** [comment]
@mfunk - I have verified the latest version of the templates from the Esri Downloads website. N - Cross-Country Mobility and N - Drop Zone Suitability are both valid tags. These templates are older (from the DCGS-A project) and each one has a toolbox as part of the download. N - Lines Of Communication is not a valid tag, and I will remove that one.

**Comment by mfunk** [comment]
@jrweakland Understood. Don't think we have any of the 'as-released' DCGS toolboxes in this repo. We'll keep them in there anyways. Thanks.
