### ISSUE TITLE
Create Labels for ArcMap and ArcGIS Pro

### ISSUE THREAD

**Issue by jrweakland** [Esri/solutions-geoprocessing-toolbox#346]
We need to create labels for the different versions of ArcMap and ArcGIS Pro. This will help focus our efforts on which versions of the tools need attention. @lfunkhouser @conklinbd @nfeuerstein

**Comment by mfunk** [comment]
So here I'm not really up to the idea of including a label for the version number, e.g. 10.2, 10.3, 1.0, 1.1. That list could very easily grow without bounds.

But I would be OK with having the app, for example:
* ArcGIS Pro
* ArcMap
* Services (for geoprocessing services)

**Comment by jrweakland** [comment]
@mfunk - edited the labels to include: V - ArcGIS Pro, V - ArcMap, and V - Services. Please verify and close.

**Comment by mfunk** [comment]
@jrweakland got 'em. Thanks.
