### ISSUE TITLE
ERG widget completes spiratically or not at all without demographic data

### ISSUE THREAD

**Issue by tylergotatie** [Esri/solutions-geoprocessing-toolbox#351]
We have limited access to Canadian Demographic data, but we can configure facilities data. The ERG widget will complete and solve a handful of times or not at all in testing. Do we have to configure the widget to work use demographic services?

Current status during testing:
- progress bar spins, no result created.

**Comment by mfunk** [comment]
Hi @tylergotatie, this seems like it's with the [ERG widget](https://github.com/Esri/solutions-webappbuilder-widgets/tree/master/ERG) and not the ERG Geoprocessing tool. Is this the case? If so I can move the issue over to the [solution-webappbuilder-widgets repo](https://github.com/Esri/solutions-webappbuilder-widgets).

Thanks, Matt

**Comment by tylergotatie** [comment]
Yes sorry, I was told to post the issue here. I've just posted in the widget issues. 
-Thank you.
