### ISSUE TITLE
Deliberate HLZ Analysis Tool Error

### ISSUE THREAD

**Issue by jrweakland** [Esri/solutions-geoprocessing-toolbox#359]
Executing (Optionally Union Features): OptionallyUnionFeatureClasses C:\Templates\MilitaryAspectsOfTerrain\ArcMap10.4\Military_Aspects_of_Terrain_for_ArcGIS_10_1\Maps\Toolbox\scratch\scratch.gdb\HLZDissolve_Erase CombinedLinearObstacleFeature C:\Templates\MilitaryAspectsOfTerrain\ArcMap10.4\Military_Aspects_of_Terrain_for_ArcGIS_10_1\Maps\Toolbox\scratch\scratch.gdb\tempScriptFC
Start Time: Thu Dec 10 14:33:22 2015
Running script OptionallyUnionFeatureClasses...
1 feature class(es) provided
unionedFeatureClass: C:\Templates\MilitaryAspectsOfTerrain\ArcMap10.4\Military_Aspects_of_Terrain_for_ArcGIS_10_1\Maps\Toolbox\scratch\scratch.gdb\tempunion
Failed script OptionallyUnionFeatureClasses...

Traceback (most recent call last):
  File "C:\Users\jame7507\Documents\GitHub\solutions-geoprocessing-toolbox\suitability\toolboxes\scripts\CheckForFeatureClasses.py", line 30, in <module>
    arcpy.Union_analysis(vtab, unionedFeatureClass)
  File "c:\program files (x86)\arcgis\desktop10.4\arcpy\arcpy\analysis.py", line 564, in Union
    raise e
ExecuteError: Failed to execute. Parameters are not valid.
ERROR 000366: Invalid geometry type
Failed to execute (Union).

Failed to execute (Optionally Union Features).
Failed at Thu Dec 10 14:33:23 2015 (Elapsed Time: 1.22 seconds)
Failed to execute (DeliberateHLZAnalysis).
Failed at Thu Dec 10 14:33:35 2015 (Elapsed Time: 1 hours 52 minutes 5 seconds)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/129342386639048/129373043931773)

**Comment by jrweakland** [comment]
I retested this tool today, and it completed without error. The second time I ran the tool I did not use the ObstructionFeatureClass (optional) option. This might be the origin of the error.

**Comment by mfunk** [comment]
Hey @jrweakland this one still and issue?

**Comment by lfunkhouser** [comment]
The Military Aspects of Terrain tools will not be enhanced. Last supported version was 10.1. These tools are retired as of the April 2018 release. Future work is planned for environmental impacts on operations, release date TBD.
