### ISSUE TITLE
Need to merge MAoW tools to this repo

### ISSUE THREAD

**Issue by mfunk** [Esri/solutions-geoprocessing-toolbox#36]
Need to import tools and test from MAoW repo into this one...
https://github.com/ArcGIS/military-aspects-of-weather-toolbox

**Comment by csmoore** [comment]
Is this still an issue?  

How does the MAOW toolbox relate to this repo? 
https://github.com/ArcGIS/solutions-raster-functions 

(just wondering since I don't see a tbx there)

**Comment by mfunk** [comment]
Sure. Are you volunteering?
The other repo is for keeping and managing raster functions just as this repo is for geoprocessing tools.

**Comment by csmoore** [comment]
I was just trying to locate the current (version-controlled) version of the toolbox (& told by @joebayles that's where it is) since it was mentioned the template was releasing soon...

**Comment by mfunk** [comment]
That's the only GitHub version of the MAoW toolbox that I know of. @dmMartin was the last person to use it that i know of.

**Comment by csmoore** [comment]
If (only github version) == (current github version releasing with the template) 

then sounds like you have answered my question of where it is.

**Comment by mfunk** [comment]
Going to close out this issue for now. Original MAoW tools were only release as part of the template. If we (not me) decide that the tools need to be moved then we will reopen this issue.

**Comment by conklinbd** [comment]
There are some tools in the new version (for pulling data on a scheduled basis. These tools need to be in this repository. @jrweakland

**Comment by mfunk** [comment]
Added **Military Aspects of Weather Tools_10.3.tbx** into *Suitability* folder, and RETIRED the old repository: https://github.com/ArcGIS/military-aspects-of-weather-toolbox-RETIRED

Also added #241 to add tests for the 10.3 tools.
