### ISSUE TITLE
FM 5-33 CCM Tool Error

### ISSUE THREAD

**Issue by jrweakland** [Esri/solutions-geoprocessing-toolbox#360]
Executing: FM533CCM bdeaoi C:\Templates\MilitaryAspectsOfTerrain\ArcMap10.4\Military_Aspects_of_Terrain_for_ArcGIS_10_1\Maps\OperationGDB.gdb\maotVehicleParameters "M1 Abrams" Slope_n34_Pr1 C:\Templates\MilitaryAspectsOfTerrain\ArcMap10.4\Data\Topographic\ancillary.gdb\Contours100m C:\Templates\MilitaryAspectsOfTerrain\ArcMap10.4\Military_Aspects_of_Terrain_for_ArcGIS_10_1\Maps\Toolbox\scratch\scratch.gdb\bdeaoi_FM533CCM # # MAX # # DRY # # #
Start Time: Thu Dec 10 15:32:00 2015
Running script FM533CCM...
START: 12/10/2015  15:32:01
Building vehicle table...
vehicleTable: {'HMMWV': ['LIGHT_WHEELED', 'HMMWV', 2.6, 144.0, 60.0, 45.0], 'MRAP Buffalo': ['HEAVY_WHEELED', 'MRAP Buffalo', 24.25, 105.0, 60.0, 45.0], 'M113 APC': ['LIGHT_TRACKED', 'M113 APC', 15.5, 66.0, 60.0, 45.0], 'Wild Ass/Donkey': ['PACK_ANIMAL', 'Wild Ass/Donkey', 0.25, 56.0, 45.0, 45.0], 'Generic ATV': ['ATV', 'Generic ATV', 0.25, 90.0, 60.0, 45.0], 'M2 Bradley': ['MEDIUM_TRACKED', 'M2 Bradley', 27.0, 66.0, 60.0, 45.0], 'M1 Abrams': ['HEAVY_TRACKED', 'M1 Abrams', 69.5, 72.0, 60.0, 45.0], 'IAV Stryker': ['MEDIUM_WHEELED', 'IAV Stryker', 19.0, 100.0, 60.0, 45.0]}
vehicleParams: ['HEAVY_TRACKED', 'M1 Abrams', 69.5, 72.0, 60.0, 45.0]
Spatial Reference is not defined. Using Spatial Reference of Input Area Of Interest: 
fishnet: 12/10/2015  15:32:01
intersect fishnet & AOI: 12/10/2015  15:32:01
AOI has 1 10km square tiles.
fishnet boundary: 12/10/2015  15:32:02
copyraster: 12/10/2015  15:32:02
Reclassify: 12/10/2015  15:32:02
Reclassifying slope...
BoundaryClean: 12/10/2015  15:32:06
CRASH: 12/10/2015  15:32:08
Traceback:   File "C:\Users\jame7507\Documents\GitHub\solutions-geoprocessing-toolbox\suitability\toolboxes\Military Aspects of Terrain Tools_10.3.tbx#FM533CCM_MAoT.py", line 282, in <module>

Executing: BoundaryClean C:\Templates\MilitaryAspectsOfTerrain\ArcMap10.4\Military_Aspects_of_Terrain_for_ArcGIS_10_1\Maps\Toolbox\scratch\scratch.gdb\reclassSlope C:\Templates\MilitaryAspectsOfTerrain\ArcMap10.4\Military_Aspects_of_Terrain_for_ArcGIS_10_1\Maps\Toolbox\scratch\scratch.gdb\Boundar_recl1 NO_SORT TWO_WAY
Start Time: Thu Dec 10 15:32:06 2015
The table was not found. [VAT_Boundar_recl1]
ERROR 010213: Error in reading raster c:\users\jame7507\appdata\local\temp\arcb5dd\xx0006292000.
Failed to execute (BoundaryClean).
Failed at Thu Dec 10 15:32:08 2015 (Elapsed Time: 1.67 seconds)
Completed script FM533CCM...
Failed to execute (FM533CCM).
Failed at Thu Dec 10 15:32:08 2015 (Elapsed Time: 8.09 seconds)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/129342386639048/129373044935095)

**Comment by phil7277** [comment]
Miss you out here bro



Sent from my Verizon Wireless 4G LTE smartphone


-------- Original message --------

**Comment by phil7277** [comment]
Phil Suarez would like to recall the message, "[solutions-geoprocessing-toolbox] FM 5-33 CCM Tool Error (#360)".

**Comment by jrweakland** [comment]
I was able to get the tool to run when I changed the input tables from the GitHub repo instead of the tables from the 10.1 download.

**Comment by mfunk** [comment]
@jrweakland this one still and issue?

**Comment by jrweakland** [comment]
I will check and get back to you @mfunk

**Comment by lfunkhouser** [comment]
The Military Aspects of Terrain tools will not be enhanced. Last supported version was 10.1. These tools are retired as of the April 2018 release. Future work is planned for environmental impacts on operations, release date TBD.
