### ISSUE TITLE
Position Analysis Template RangeRings.py  with german localization. "is not working with with floating-point numbers"

### ISSUE THREAD

**Issue by pshowalter** [Esri/solutions-geoprocessing-toolbox#363]
Position Analysis Template 
Reported on 11/16/2015:
[ArcGIS.com ](http://www.arcgis.com/home/item.html?id=f10d78ae29cd471ebe2e96bad9b67277)

The Range Rings model is not working with floating-point numbers when using a german localization. Within the RangeRings.py you should use: 
`ringInterval = arcpy.GetParameter(2) instead of: ringInterval = float(arcpy.GetParameterAsText(2))`
otherwise there will be an error when the script is trying to parse e.g. ‘5,6’

No further information.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/129342386639048/129373015346259)

**Comment by mfunk** [comment]
The tool/toolbox associated with this issue has been deprecated and is no longer actively supported. Earlier versions of this toolbox will still be available from previous [Releases](https://github.com/Esri/solutions-geoprocessing-toolbox/releases)
