### ISSUE TITLE
Clearing Operations: Potential Issues with Alternative Coordinate Systems

### ISSUE THREAD

**Issue by rfeuerstein** [Esri/solutions-geoprocessing-toolbox#37]
Using the "Canvas GRG" tool in the Clearing Operations Template with WGS 1984 for the data layers and data frame over Boston, MA. Input AO equals 1.4 mile square but the output produces a single grid square (A1) with 4,600 mile diameter: Boston to the Black Sea. Changed AO feature class input projection to WGS 1984 Web Merc and the tools worked as designed.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/129342386639048/129373044063171)

**Comment by jrweakland** [comment]
Added to Asana - https://app.asana.com/0/23179693844547/23186355169299

**Comment by joebayles** [comment]
@mfunk shouldn't this be assigned to @jscott11, since she worked on the tools before?

**Comment by mfunk** [comment]
@jscott11 Can you check this one out also?

**Comment by mfunk** [comment]
Logged into backlog.

**Comment by adgiles** [comment]
This should now be fixed on the version in the september staging folder

**Comment by topowright** [comment]
I will take a look at this.

**Comment by topowright** [comment]
Verifed
