### ISSUE TITLE
Error in Cluster Analysis with scratch workspace

### ISSUE THREAD

**Issue by JudTown17** [Esri/solutions-geoprocessing-toolbox#373]
When running the Cluster Analysis tool in Incident Analysis toolbox, the following error is returned:
```
ERROR: Executing: ClusterAnalysis "C:\Data\Defense Solutions\solutions-geoproces
sing-toolbox\utils\test\patterns_tests\data\IncidentAnalysis.gdb\Incidents" "500
 Unknown" "C:\Data\Defense Solutions\solutions-geoprocessing-toolbox\utils\test\
patterns_tests\data\scratch.gdb\outputClusters"
Start Time: Tue Dec 22 13:11:43 2015
Executing (Copy Features): CopyFeatures "C:\Data\Defense Solutions\solutions-geo
processing-toolbox\utils\test\patterns_tests\data\IncidentAnalysis.gdb\Incidents
" C:\Users\juds5059\AppData\Local\Temp\\copy_cluster # 0 0 0
Start Time: Tue Dec 22 13:11:46 2015
ERROR 000210: Cannot create output C:\Users\juds5059\AppData\Local\Temp\\copy_cl
uster
Failed to execute (Copy Features).
Failed at Tue Dec 22 13:11:48 2015 (Elapsed Time: 1.76 seconds)
```
In the model for Cluster Features, the Output Workspace parameter for the Copy Features tool that is run in the model is hard-coded with **%scratchworkspace%\copy_cluster**

**Comment by JudTown17** [comment]
The error only occurs when running the Cluster Analysis tool in the Incident Analysis Tools.tbx in ArcGIS Pro 1.2. Running Cluster Analysis in the Incident Analysis Tools_10.4.tbx in ArcMap 10.4 works.

Note that changing the Output Feature Class parameter in the Copy Features tool to **%scratchGDB%\copy_cluster** will make it work.

**Comment by mfunk** [comment]
Verified fixed.
