### ISSUE TITLE
Error in Count Incidents By LOC tool (Desktop)

### ISSUE THREAD

**Issue by JudTown17** [Esri/solutions-geoprocessing-toolbox#376]
The following error message is shown when running the Count Incidents By LOC tool in the Incident Analysis Tools_10.4.tbx using ArcMap 10.4.

`INFO: 2016-01-19 11:01:51,493 Running tool (Count Incidents By LOC)`

`ERROR: 2016-01-19 11:01:53,937 Executing: CountIncidentsByLOC "C:\Data\Defense Solutions\solutions-geoprocessing-toolbox\utils\test\patterns_tests\data\IncidentAnalysis.gdb\Incidents" "C:\Data\Defense Solutions\solutions-geoprocessing-toolbox\utils\test\patterns_tests\data\IncidentAnalysis.gdb\Roads" "50 Meters" "C:\Data\Defense Solutions\solutions-geoprocessing-toolbox\utils\test\patterns_tests\data\scratch.gdb\outputCount"
Start Time: Tue Jan 19 11:01:52 2016
Failed to execute. Parameters are not valid.`

`ERROR 000670: output Output Table is same as input Input Table
Failed to execute (CountIncidentsByLOC).
Failed at Tue Jan 19 11:01:53 2016 (Elapsed Time: 0.44 seconds)`

The same error is shown when running it in ArcMap and running the tool from a Python script.

**Comment by dfoll** [comment]
@JudTown17 fixed this issue in 10.4, pull request #408.

**Comment by mfunk** [comment]
@JudTown17 can you verify this one is fixed?

**Comment by JudTown17** [comment]
@mfunk I verified this morning that this issue is indeed fixed.

**Comment by mfunk** [comment]
@JudTown17 if it's fixed and you verified you need to close it.
