### ISSUE TITLE
Issues moving Convert Coordinate tool to new toolbox

### ISSUE THREAD

**Issue by mfunk** [Esri/solutions-geoprocessing-toolbox#378]
In moving **Convert Coordinate** tool from _Import and Conversion Tools_ to a new toolbox the following lines are hardcoded and need to be modified each time the toolbox changes:

line 32:

```
    toolboxpath = os.path.join(scriptpath,"..\\Import and Conversion Tools_10.3.tbx")
```

This line is calling the toolbox to use in line 80. Ideally the tool should be aware of what toolbox it lives in, but it does not. Need to figure out a better method of figuring this out.

line 80:

```
    arcpy.AddUniqueRowID_InC(Output_Table, "JoinID")
```

In line 80 it is the toolbox alias that is the problem. Here it is looking for _AddUniqueRowID_InC_ which probably won't exist in the new toolbox. Another toolbox specific change that needs to occur for the tool to run nicely.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/129342386639048/129368345174088)

**Comment by csmoore** [comment]
I would agree that a tool should not have a dependency on what toolbox it lives in if it can possibly be avoided. 

Another option might be to structure the file so it could be called as both a method and a tool. ex:

```
def tool_method(in_parameters) : 
  # body here (and can also be called as method)

if __name__ == '__main__':
  # get in_parameters
  out_parameters = tool_method(in_parameters)
  # set out_parameters

```

Also you may want to consider moving common functions like "AddUniqueRowID" to a common library/folder that all of the toolboxes use (since they are repeated in multiple folders/toolboxes)

**Comment by mfunk** [comment]
That would be ideal, however CC is the only *script* that uses **AddUniqueRowID**. It is, however, used by 4+ Model Builder models, which can not directly access Python methods (not even sure they can indirectly access them). This goes back to the TBX/PYT argument again, but until we decide to only use scripts and no models ... I'm not sure how to best satisfy both.

What we really should do is get the GP team to figure out a way for script tools to be aware of the toolbox in which they reside, whether it's just by path or object ref, I really don't care. Until then, we're kinda stuck with this. Another time I wish I had time to play with it more :smile:

**Comment by csmoore** [comment]
Just to clarify, the models could still use the existing AddUniqueRowID tool (which would remain unchanged), but (after the file restructuring above) the script itself would call the script method rather than the GP tool

```
import AddUniqueRowID 

AddUniqueRowID.tool_method(Output_Table, "JoinID")

```

**Comment by mfunk** [comment]
Duplicated here: https://github.com/Esri/military-tools-geoprocessing-toolbox/issues/32

**Comment by mfunk** [comment]
The tool/toolbox associated with this issue has been deprecated and is no longer actively supported. Earlier versions of this toolbox will still be available from previous [Releases](https://github.com/Esri/solutions-geoprocessing-toolbox/releases)
