### ISSUE TITLE
Range Ring (in ArcGIS Pro) Model does not apply symbology from layer, or add Labeling from layer file.

### ISSUE THREAD

**Issue by pshowalter** [Esri/solutions-geoprocessing-toolbox#379]
Range Ring (ArcGIS Pro) Model does not apply symbology from layer, or add Labeling from layer file. 
User must point the model to location of the .lyr files, which causes model to then use proper line symbol, but labeling will not be applied.
After running Range Rings, the result should be a set of range rings labeled with distance from "Range Ring Center".  The Model Parameters point to a folder with .lyr files, can be manually applied from Appearance tab - Drawing Group - Import button.
<img width="482" alt="rangeringissue" src="https://cloud.githubusercontent.com/assets/6842145/12586205/5e763fa0-c41d-11e5-86c0-0d4d1548367e.png">

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/129342386639048/129373044128839)

**Comment by csmoore** [comment]
Funnily enough @jscott11 & I were just noticing this

**Comment by jscott11** [comment]
Yep, I had the same issue. I'm using ArcMap 10.3.1, and the Range Fans From Weapon Parameters tool in the Visibility and Range Toolbox.

**Comment by pshowalter** [comment]
Range Rings - in ArcMap 10.3.1 does not apply the symbology or labels.  Manually applying the .lyr file to the result does not result in labels, which differs from ArcGIS Pro (1.2 beta) which will pick up "Range" labels when manually applying the layer file.

**Comment by mfunk** [comment]
@pshowalter What happens if you apply the .LYRX (for Pro, .LYR for Desktop) to the output ring and radial Model Parameters?

**Comment by pshowalter** [comment]
@mfunk  ArcGIS Pro 1.2 beta, will allow user to manually apply the .LYRX file properly and display the labels.  They are lined up in a nice stack from bottom to center of the Range Rings.

ArcMap applies the .LYR file automatically, but labels are placed at various locations around the rings, not stacked.

**Comment by mfunk** [comment]
Unfortunately core development has marked this problem as known limit with BUG-000101471. Stating that LYRX is for symbology only, not labels and cites the *Symbology* section in Pro help: https://pro.arcgis.com/en/pro-app/help/analysis/geoprocessing/modelbuilder/model-parameters.htm

**Comment by mfunk** [comment]
The tool/toolbox associated with this issue has been deprecated and is no longer actively supported. Earlier versions of this toolbox will still be available from previous [Releases](https://github.com/Esri/solutions-geoprocessing-toolbox/releases)
