### ISSUE TITLE
Military Analyst Tools toolbox does not have a description

### ISSUE THREAD

**Issue by dhagens** [Esri/solutions-geoprocessing-toolbox#380]
According to the SolutionsGuideToCreatingGeoprocessingTools document (https://github.com/ArcGIS/Solutions-Resources/blob/master/Python/Style/SolutionsGuideToCreatingGeoprocessingTools.md), the Toolbox Properties MUST have a good description

**Comment by mfunk** [comment]
Hey @dhagens MA toolbox is not tracked here, only in BOX. Until we hear from the Dev Ops on HOW to manage duplicate tools we'll just have to fix it there and repost it back to BOX.

**Comment by mfunk** [comment]
@topowright Need to hammer the procedures out VERY fast. Don't think this can wait.
