### ISSUE TITLE
Help for Number of Rings parameter inconsistent with default value

### ISSUE THREAD

**Issue by dhagens** [Esri/solutions-geoprocessing-toolbox#381]
Help for Number of Rings parameter inconsistent with default value of 5 rings stated in the help.  Actual default value is 10

**Comment by mfunk** [comment]
@dhagens I'm reopening this one to be fixed in the repo version of the RR tools.

**Comment by mfunk** [comment]
New Range Rings tools added to Visibility and Range for Desktop (10.4) and Pro (1.2) . So this issue is no longer a problem.
