### ISSUE TITLE
Help for Ring Interval parameter inconsistent with default value of 1000 units

### ISSUE THREAD

**Issue by dhagens** [Esri/solutions-geoprocessing-toolbox#382]
Help for Ring Interval parameter inconsistent with default value of 1000 units stated in the help. Actual default value is 100

**Comment by mfunk** [comment]
Was fixed in MA, but not here. Need to branch from DEV, fix, then submit Pull Request (don't merge).

**Comment by mfunk** [comment]
Keep this one simple and include fix for #381 in same Pull Request.

**Comment by mfunk** [comment]
New Range Ring tools added for Desktop (10.4) and Pro (1.2). This issue is no longer a problem.
