### ISSUE TITLE
Add note to readme about "py not recognized..." message and update Requirements

### ISSUE THREAD

**Issue by mfunk** [Esri/solutions-geoprocessing-toolbox#390]
Need to add a note to the README for users who come across:

```
Python 3.4 Tests ===============================
'py' is not recognized as an internal or external command,
operable program or batch file.
Python 2.7 Tests ===============================
'py' is not recognized as an internal or external command,
operable program or batch file.
```

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/129342386639048/129373043652199)

**Comment by mfunk** [comment]
@JudTown17 What do you think about having a separate .BAT file for running Desktop vs Pro tools?

* ProTestRunner.bat - runs only the Pro tests
* DesktopTestRunner.bat - runs only the Desktop tests
* AllPlatformTestRunner.bat - to run both Pro and Desktop tests

**Comment by JudTown17** [comment]
@mfunk I think that is a good idea. TestRunner.py can be re-factored to support running Pro and Desktop tests separately or together.

**Comment by mfunk** [comment]
Perhaps we should look at trying to remove TestKickStart.bat entirely. Depending upon a users setup, the call to python.exe or py.exe can change. We probably shouldn't try to force it to be in one location.

**Comment by csmoore** [comment]
py is no longer used in .bat's - closing
