### ISSUE TITLE
Drop " Join" from Incident Table to Point tool in Incident Analysis Tools

### ISSUE THREAD

**Issue by dfoll** [Esri/solutions-geoprocessing-toolbox#396]
Because of an update to the convert coordinate notation tool which the Table to point tool uses, the join is no longer necessary... leaving the join in results in duplication of all the fields which are then suffixed with "_[n]"

**Comment by topowright** [comment]
@dfoll This update was done in the last update. This is also a template that was moved to mature support. I am closing this issue.
