### ISSUE TITLE
Unable to determine ArcGIS version on Import Patrol Report

### ISSUE THREAD

**Issue by dfoll** [Esri/solutions-geoprocessing-toolbox#397]
Found while using Pro 1.2

Import Patrol Report in the Patrol Data Capture Tools toolbox, in the Data Management folder has an error when running that it is unable to determine ArcGIS version number.  

Start Time: Thu Feb 18 13:56:27 2016
Running script ImportPatrolReport...
PYTHON ERRORS:
Traceback info:
  File "C:\Users\dere5261\Documents\ArcGIS\Projects\Patrol Data Capture Cert\ImportPatrolReport.py", line 106, in main
    tbx = os.path.join(getToolboxPath(),getToolboxName())

Error Info:
Unable to determine ArcGIS version
ArcPy ERRORS:
Completed script ImportPatrolReport...
Failed to execute (ImportPatrolReport).
Failed at Thu Feb 18 13:56:27 2016 (Elapsed Time: 0.08 seconds)

**Comment by dfoll** [comment]
@lfunkhouser this is the point where pdc is held up right now... i THINK everything will be good with the template when this is cleaned up, but i don't want to say that is set in stone until i this is fixed up

**Comment by dfoll** [comment]
@ACueva  i was wondering if you would be interested in helping me look at this tomorrow

**Comment by csmoore** [comment]
If this tool/script is being called from within the same toolbox, I'm not sure why those calls mentioned (get toolbox name, import toolbox) would even be necessary at: https://github.com/Esri/solutions-geoprocessing-toolbox/blob/master/data_management/toolboxes/scripts/ImportPatrolReport.py#L97

**Comment by mfunk** [comment]
Version issue is probably because the script is calling arcpy.mapping/arcpy.mp. There was an update to our methods for determining version that this script probably didn't get. Instead of matching existing version to a specific list of numbers we were checking against:

```
def GetApplication():
    '''Return app environment as ARCMAP, ARCGIS_PRO, OTHER'''
    try:
        from arcpy import mp
        return "ARCGIS_PRO"
    except ImportError:
        try:
            from arcpy import mapping
            mxd = arcpy.mapping.MapDocument("CURRENT")
            return "ARCMAP"
        except:
            return "OTHER"
```

**Comment by mfunk** [comment]
Patrol Data Capture template has moved to Mature Support, and this toolbox along with it. This issue is being closed as the tool will not be worked on any more.
#461
