### ISSUE TITLE
Replace "Add Unique Row ID" script with "Add Incrementing ID Field" core tool

### ISSUE THREAD

**Issue by mfunk** [Esri/solutions-geoprocessing-toolbox#398]
New tool in core geoprocessing **Add Incrementing ID Field** could easily replace **Add Unique Row ID** in several templates. List of templates and tools that it should replace will follow.

@csmoore will be happy to see it go.

**Comment by csmoore** [comment]
@mfunk - I will indeed- this and any other files/code that are repeated. I believe the old software adage goes something like: "if something exists in 2 places, it is usually wrong in one of them"

**Comment by mfunk** [comment]
@csmoore which reminds me I owe you a conversation about tools as methods.

**Comment by mfunk** [comment]
So the new tool **Add Incrementing ID Field** is for Standard and Advanced license only, and is NOT intended for geodatabase tables, per the first Usage bullet point:

```
This tool can only be used with database tables, not geodatabase tables.
```

So we will need to keep **Add Unique Row ID** around.
