### ISSUE TITLE
Please update the "G" labels to reflect the current offerings on the Solutions Website

### ISSUE THREAD

**Issue by jrweakland** [Esri/solutions-geoprocessing-toolbox#399]
Please remove the "G - Intelligence Team" and the "G - Military Team" labels and replace with "G - Defense Team" in this repo to reflect the current offering on http://solutions.arcgis.com/. This will also need to be completed at https://github.com/Esri/solutions-geoprocessing-toolbox/wiki#issue-labels

**Comment by mfunk** [comment]
Done.
