### ISSUE TITLE
MAoT: Documentation Unclear

### ISSUE THREAD

**Issue by rfeuerstein** [Esri/solutions-geoprocessing-toolbox#40]
1. Under "Data Requirements" on page 5 for MAoT for 10.1 states...
Operational Environment sample data.
▪ Download from www.ArcGIS.com, search for 'operational environment'
▪ The MAoT template requires the Operational Environment (OE) to be completed. The Operational Environment geodatabases are where MAoT gets input data and publishes analytic results.

2. Why isn't there a hyperlink to the Operational Environment template that produces and/or contains the prerequisite data for MAoT? 

3. Searched for "Operational Environment" in ArcGIS Online and the searched returned zero results with the title. The first and most recent search result is for the Military Aspects of Terrain (MAoT) template that I'm already attempting to use. 

4. After going in circles for awhile I realized there is a hyperlink to download the Operational Environment sample data on the item page for MAoT. Why not make the data part of the download if it's required for the template?

**Comment by mfunk** [comment]
This issue was moved to ArcGIS/solutions-templates#22
