### ISSUE TITLE
Incident Table to Point tool not importing datetimestart field from excel table as a date field

### ISSUE THREAD

**Issue by dfoll** [Esri/solutions-geoprocessing-toolbox#400]
When you run the Incident Table to Point tool it is importing the datetimestart field from the excel table as a text field instead of a date field as it should be. This is causing the definition queries for the date break out (last 24 hours, last 48 hours ... etc ...) of incidents to not work, which then causes other tools not to be able to perform analysis on the data.  Attached is the table in question, however I have observed this with tables from released versions of the template (10.1, 10.2) 
[MontereyIncidents.xlsx](https://github.com/Esri/solutions-geoprocessing-toolbox/files/165902/MontereyIncidents.xlsx)

**Comment by dfoll** [comment]
@lfunkhouser

**Comment by mfunk** [comment]
The problem we are having here is in ArcGIS's support of Excel files. Basically, Excel doesn't store field types, and therefore ArcGIS must interpret them based on the first 8 rows. So in reading a date field, which is a mix of numbers and characters, it is read as a mixed set, and is therefore a string. The direct info on the problem is here...

http://desktop.arcgis.com/en/arcmap/10.3/manage-data/tables/understanding-how-to-use-microsoft-excel-files-in-arcgis.htm

Where it states:

```
Excel does not enforce field types for values during data entry like standard databases do. Therefore, the field type specified in Excel is not used in determining the field type exposed in ArcGIS. Instead, field type in ArcGIS is determined by a scan of the values in the first eight rows for that field. If the scan finds mixed data types in a single field, that field will be returned as a string field, and the values will be converted to strings.
```

So at this time we can give them an alternate version of the data (suggest CSV with the included schema.ini) that will enforce date and time fields.

**Comment by dfoll** [comment]
@nfeuerstein we may need to get a hold of the original creator of this tool, and ask exactly how this was expected to work, given what matt just pointed out. i've never "workflow" tested this template, only certified it, and all the tools do certify given they have good data, which they always did. however the way i interpret things, this is an issue for a user to start from the true beginning using their own table. because none of the definition queries, nor any of the tools that compare dates will work with excel spreadsheets.
@conklinbd @lfunkhouser

**Comment by mfunk** [comment]
w.r.t. how the CSV with schema.ini file works, the **Overriding how text files are formatted** section of http://desktop.arcgis.com/en/arcmap/10.3/manage-data/tables/adding-an-ascii-or-text-file-table.htm.

...  suggests looking at MSDN for topics on schema.ini files. Here is one that I found that fits our needs:

https://msdn.microsoft.com/en-us/library/ms709353(v=vs.85).aspx

**Comment by mfunk** [comment]
So when I saved *MontereyIncidents.xlsx* as a CSV, I made **schema.ini** that went along with it that contained the following:

```
[MontereyIncidents.csv]
Col1=title Text
Col2=category Text
Col3=datetimestart DateTime
Col4=datetimeend DateTime
```

**Comment by dfoll** [comment]
@mfunk good start, the field is coming in as a "Date" with this workaround, however now all the values in that field are null

**Comment by nfeuerstein** [comment]
@dfoll @mfunk -the "Incident Table to Point" tool is the same "Table to Point" tool that is in the Import and Conversion toolbox (which was previously included in the Position Analysis template).  So, unless I'm mistaken I actually think Matt was the original author of that tool.  I also believe the intent of the tool was to create points out of a table in the TOC, not go straight from an .xls/x to points.  So, the user would need to have a valid table (with the date being in a date format) for the tool to work.  The sample table IncidentData.xls that was included with the template has a date field that remains a date field when its added as a table to the TOC - so I'm still unclear why the Monterey .xlsx is not working.

**Comment by mfunk** [comment]
@nfeuerstein Simply they way ArcGIS reads XLSX files, we (Esri) are not interpreting dates correctly. The same problem happens with the **Excel To Table** tool. We have no problem with text or number fields, but dates are a combination of numbers and characters, and are then read as string/text fields.

**Comment by mfunk** [comment]
Let me ammend that last comment. Whatever library Esri uses to read XLSX doesn't handle dates well. I don't want to assume its some bit of code that Esri wrote, but it might be.

**Comment by nfeuerstein** [comment]
I hear what you're saying, but is that a blanket statement that applies to all date and date/time formats?  Because the Incidents.xls spreadsheet that was included in the data folder of the template has a date field with a date format (3/14/2012), and when I add that sheet to the TOC as a table and look at the properties the field type is Date.  So, I'm thinking that perhaps only certain date formats are accepted (read by ArcGIS as dates).

**Comment by mfunk** [comment]
I can only speak to the file and date/time format that is with this template which is using a combined date and time format of "DD/MM/YY hh:mm:ssAM". Even Excel can define it as a date/time...

![image](https://cloud.githubusercontent.com/assets/3093182/13994111/86d65986-f0e0-11e5-9fb4-734a59ec7929.png)

However, if we just open the XLSX in ArcMap. It only sees this as a TEXT field:

![image](https://cloud.githubusercontent.com/assets/3093182/13994281/568f79dc-f0e1-11e5-84ca-3b77015e2bb9.png)

At this point we haven't even touched the tool. The tool is just reading what the platform tells it this file is.

**Comment by dfoll** [comment]
@karlterrey fyi

**Comment by dfoll** [comment]
i went way back in time, and went and got Incident Analysis 1.0.0 from the [downloads page](http://www.esri.com/apps/products/download/#ArcGIS_for_Defense). when you add the Incidents.xls spreadsheet as data, or by dragging and dropping it on the table of contents, then view the open the table, the "datetimestart" field shows as type text. I have attached the exact spreadsheet i am seeing this with, or it can be retrieved from IA version 1.0.0 from the link above
[Incidents.zip](https://github.com/Esri/solutions-geoprocessing-toolbox/files/188676/Incidents.zip)

**Comment by dfoll** [comment]
took another look at this today, and the data being used for testing was in fact bad. essentially the problem was this... the datetimestart field as we used it over jalalabad had only the date, no time. (see matt's explanation as to why this was a problem). the sample data now included with the monterey location of the template now matches that format and has only the date in the datetimestart. i'm closing this issue, and proceeding with testing the pro version and creating content for the website.
