### ISSUE TITLE
Place data for Maritime Decision Aid Tools into tooldata folder

### ISSUE THREAD

**Issue by JudTown17** [Esri/solutions-geoprocessing-toolbox#401]
@mfunk , @jfrygeo :

Currently when running most tools in the Maritime Decision Aid Tools_10.4.tbx, there is a dependency on rasters in _data.gdb_ in the _\solutions-geoprocessing-toolbox\data_ folder. Instead, the tools should point to data in a geodatabase in the _\solutions-geoprocessing-toolbox\suitability\toolboxes\tooldata_ folder.

**Comment by mfunk** [comment]
@jfrygeo can we update the tools to pull required data from **tooldata* folder?

**Comment by jfrygeo** [comment]
I think  it will work.

**Comment by JudTown17** [comment]
@jfrygeo  Farthest On Circle now points to the _tooldata_ folder. As far as I can tell, it looks like **Find Submarine Canyons**, **Sensor Viewshed Processing**, and **Sub Depth Restriction Suitability** tools use data from the _data.gdb_ or _scratch.gdb_ in the _\solutions-geoprocessing-toolbox\data_ folder. Can you point data for those three tools to the _tooldata_ folder as well? Thanks!

**Comment by jfrygeo** [comment]
Sure can. Will do.

Sent from my iPhone

On Apr 14, 2016, at 7:11 PM, Judson Hardy <notifications@github.com<mailto:notifications@github.com>> wrote:


@jfrygeo<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_jfrygeo&d=CwMCaQ&c=n6-cguzQvX_tUIrZOS_4Og&r=LOFtvHGMxkJ_DWps2cZi-A&m=W6LF9dqRGp3K0KRIE9vsYYjyCoXeOnXoY2W6lzE4hfM&s=MbEkg5aBt6NtQuBTa23dJT-XZJiZdFpEAW56osOW-k4&e=> Farthest On Circle now points to the tooldata folder. As far as I can tell, it looks like Find Submarine Canyons, Sensor Viewshed Processing, and Sub Depth Restriction Suitability tools use data from the data.gdb or scratch.gdb in the \solutions-geoprocessing-toolbox\data folder. Can you point data for those three tools to the tooldata folder as well? Thanks!

-

**Comment by mfunk** [comment]
@JudTown17 Can you verify the fix and close this issue?
