### ISSUE TITLE
Range Card Tools should include Visibility Analysis

### ISSUE THREAD

**Issue by joebayles** [Esri/solutions-geoprocessing-toolbox#41]
Part of the workflow for developing a range card is identifying the "dead space," area that is not visible to the firing position.

Currently, the user can sketch out the dead space, but it would be much easier and accurate to provide a tool that does that automatically.

**Comment by jrweakland** [comment]
@joebayles - Take a look at @mfunk comments and provide feedback.

**Comment by joebayles** [comment]
@mfunk, that's exactly what I was talking about. Thanks.

@jrweakland I'll add it to the Asana task for Range Card template conversion to Pro.
