### ISSUE TITLE
Range Rings (in ArcGIS Pro 1.2) Model - not accepting feature class from TOC, or browsing to one.

### ISSUE THREAD

**Issue by pshowalter** [Esri/solutions-geoprocessing-toolbox#414]
Range Ring (in ArcGIS Pro) Model - not accepting Range Ring Centers from feature class/layer in TOC, or browsing to one.  By default it populates Range Ring Centers with "in_memory\feature_set".  Setting to point fc in toc, or browsing to point fc, results in red X.  The custom toolbox being used was created by @mfunk.  If I Edit the Model, the sourceRR script tool will not open and indicates "Tool has failed to open:...".  If I replace sourceRR with by adding sourceRR from "\Source Scripts" folder, and reconnect, then the tool works.  Appears that the model function has an underlying disconnect.
- ![image](https://cloud.githubusercontent.com/assets/6842145/14325570/f07f1b58-fbf7-11e5-89cc-7a86163a8b2a.png)
- ![image](https://cloud.githubusercontent.com/assets/6842145/14325632/2e06f360-fbf8-11e5-9e2c-c60057f35492.png)
- ![image](https://cloud.githubusercontent.com/assets/6842145/14325719/95310616-fbf8-11e5-9b28-5a6a7666c456.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/129342386639048/129373044063107)

**Comment by mfunk** [comment]
The tool/toolbox associated with this issue has been deprecated and is no longer actively supported. Earlier versions of this toolbox will still be available from previous [Releases](https://github.com/Esri/solutions-geoprocessing-toolbox/releases)
