### ISSUE TITLE
Range Rings (in ArcGIS Pro 1.2) Model - not applying symbology or labels from Layer file.

### ISSUE THREAD

**Issue by pshowalter** [Esri/solutions-geoprocessing-toolbox#415]
Range Rings (in ArcGIS Pro 1.2) Model - not applying symbology or labels from Layer file.  Yser can manually apply the Layer file. 

If applied manually:
Labels for range rings appear.
Labels for radials do not appear,  unless user manually turns on labels after applying Layer file..

**Comment by mfunk** [comment]
Duplicate of #379
