### ISSUE TITLE
Range Rings (in ArcGIS Pro 1.2) Model - in some cases radials do not extend to ring.

### ISSUE THREAD

**Issue by pshowalter** [Esri/solutions-geoprocessing-toolbox#416]
Range Rings (in ArcGIS Pro 1.2) Model - in some cases radials do not extend to ring.  Using Web Mercator, and have Map Property set to "Enable wrapping around date line"

![image](https://cloud.githubusercontent.com/assets/6842145/14328308/1d110dd2-fc04-11e5-91e0-f62b3bf5a9e3.png)

**Comment by mfunk** [comment]
@pshowalter Does this happen with the 'new' version of **Range Rings (from Interval)**? or is this with the older one. My guess is the older one, but if you get the same results with the new tool we'll want to know about it.

**Comment by pshowalter** [comment]
With a little help from @dhagens, working much better.

**Comment by pshowalter** [comment]
Confirming that the GP Model is working.  I mistakenly re-tested using the Add-in which was not related to this issue.
![image](https://cloud.githubusercontent.com/assets/6842145/15119772/82d41d26-15e0-11e6-900b-85a176cab819.png)
