### ISSUE TITLE
Visibility & Range Tools > Range Fans by Feature issue

### ISSUE THREAD

**Issue by joebayles** [Esri/solutions-geoprocessing-toolbox#42]
This tool throws an error when running due to a Python version issue (!grid_code! vs. !gridcode!). @mfunk is aware.

![6-12-2014 16-07-30](https://cloud.githubusercontent.com/assets/5016557/3264971/cae1b930-f287-11e3-9d1a-1b7083cd81d8.png)
![6-12-2014 16-06-26](https://cloud.githubusercontent.com/assets/5016557/3264972/cd43c57e-f287-11e3-84a4-116fc24063c5.png)

**Comment by mfunk** [comment]
Closing this issue as this tool was removed from Visibility and Range before Release v10.2.2.0.
