### ISSUE TITLE
Incident Density is not producing valid results

### ISSUE THREAD

**Issue by dfoll** [Esri/solutions-geoprocessing-toolbox#421]
Incident Density calls the Optimized Hot Spot tool. The surface output was producing output without the tool failing, however i noticed OHS doesn't like geographic coordinate systems... this is what was producing the bizarre results. 

To fix this problem i edited the model for Incident Density and now project the input points and the input boundary, before OHS runs. Also added the parameter to the model for the projects. Made the change in both Pro and 10.4, as i was seeing it in both places.

Results should look something like below, patterns and sizes will vary depending on your test data.
![image](https://cloud.githubusercontent.com/assets/5322669/14335105/bf991686-fc0d-11e5-9bad-e48db0f84edf.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/129342386639048/129373043864891)

**Comment by mfunk** [comment]
So as of today's running of these tools the output I'm getting is the same as the picture above so I'm assuming this is fixed.

![image](https://cloud.githubusercontent.com/assets/3093182/25448361/09d101b2-2a6d-11e7-8297-de95019747a8.png)
