### ISSUE TITLE
Replicated tools

### ISSUE THREAD

**Issue by topowright** [Esri/solutions-geoprocessing-toolbox#425]
Incident Table To Point in the Patterns folder and Table to Point in the Import and Conversion are the same tool. How do we deal with this issue? @mfunk

**Comment by topowright** [comment]
We also have:
**MAOT**
Highest Points in Near Locations
Lowest Points in Near Locations
**Visibility and Range**
Highest Points
Lowest Points

**Comment by mfunk** [comment]
For *Incident Analysis*, remove the tool from the toolbox, then include the **Import and Conversion Tools** toolbox in the template.

For *MAoT* and *V&R* the tools are NOT the same tools.

**Comment by mfunk** [comment]
@nfeuerstein We are not going to duplicate tools in multiple toolboxes anymore (because maintenance nightmares for keeping tools up-to-date in multiple locations is not working at all). If you think you will need to have a *Table To Point* capability, can you add the Import and Conversion Toolbox to the template?

**Comment by nfeuerstein** [comment]
@mfunk that's possible, or we may just be able to completely remove that tool from the template.

**Comment by mfunk** [comment]
Pretty much what I want to do. Drop the one from IA tools, and include *Import and Conversion* in the IA templates. Nothing we have to do immediately, but next time you are updating IA templates would be ideal.

**Comment by mfunk** [comment]
@topowright 
@nfeuerstein 
@dfoll 
Since we are deprecating *Import and Conversion* toolbox per our backlog plans for November 2016 release I'm going to close this one and we will keep the *Table To Point* in Incident Analysis.
