### ISSUE TITLE
Build Elevation Mosaics tool uses Web Mercator for mosaic

### ISSUE THREAD

**Issue by mfunk** [Esri/solutions-geoprocessing-toolbox#43]
Currently the existing Build Elevation Mosaics tool builds a mosaic dataset in Web Mercator. 

![webmercinbuildelevmosaics](https://cloud.githubusercontent.com/assets/3093182/3463115/d55f243e-0235-11e4-828c-77d7564bddee.png)

We need to start using Geographic WGS 1984 for this dataset.

**Comment by NatalieCampos** [comment]
The tools in the Build Elevation tool box have all had the SRS changed from Web Mercator to WGS 84
