### ISSUE TITLE
GP Repo needs to include Range Dome Analysis tools

### ISSUE THREAD

**Issue by topowright** [Esri/solutions-geoprocessing-toolbox#431]
Add Range Dome analysis tools

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/129342386639048/129373043930493)

**Comment by topowright** [comment]
This has been done in the following pull request: https://github.com/Esri/solutions-geoprocessing-toolbox/pull/460. @mfunk please verify.

**Comment by mfunk** [comment]
@topowright  per #460 these tools need a lot of work to get them into the repo. I don't have an exhaustive list of stuff to do as I don't have a copy for 10.4.1 (yet). When you're back in the office we'll have to meet for an hour or so and make it work.

**Comment by mfunk** [comment]
The tool/toolbox associated with this issue has been deprecated and is no longer actively supported. Earlier versions of this toolbox will still be available from previous [Releases](https://github.com/Esri/solutions-geoprocessing-toolbox/releases)
