### ISSUE TITLE
Need to sort out unit test log file in TestKickStart.bat

### ISSUE THREAD

**Issue by mfunk** [Esri/solutions-geoprocessing-toolbox#439]
@JudTown17 

Something else we left go... we are currently only appending to a single 'default.log' rather than increment based on date/time/id as we originally set out to do.

Right now the TestKickStart.bat is always setting the log to go to 'default.log', and not using the facility we had originally set up. I think we need to revisit this after your current test building is done. We'll need to discuss it before you get started though, as I think we should roll this into a new format for the log files (XML vs JSON, rather than text).

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/129342386639048/129373049241011)

**Comment by csmoore** [comment]
The 'default.log' in .bat's does not seem to be an issue any more - OK to close?

**Comment by mfunk** [comment]
Agreed.
