### ISSUE TITLE
Build a script that allows users to pull out their templates tools

### ISSUE THREAD

**Issue by mfunk** [Esri/solutions-geoprocessing-toolbox#447]
**Problem:**
Right now the engineer must manually copy all of the parts of a GP tool for deployment in a template. This means the engineer must know which files belong with the toolbox. Sometimes the required files are not obvious (imported PY modules, output LYRX files, tooldata, etc.). This means the engineer may not be copying the right files, or copying the wrong ones. This means the toolbox will either not function, or will be bloated with extra files. What we need is something that will allow the engineer to deploy just one toolbox and all of it's required files from the entire repository.

**How:**
Each toolbox will have an associated INI file that acts as an inventory file, listing all of the parts that go with the toolbox.

This would include TBX/PYT toolbox, PY scripts, LYR/LYRX layer files, tool data, etc. From one centralized "deployment" script the inventory file would be read, the pieces found, and placed into a target folder. The inventory/deployment would exclude scratch data, intermediate data, test files, etc.

**What:**
The deployment would contain the following parts
- A main deployment script (Python) in .\solutions-geoprocessing-toolbox\utils\deploy
- A <template>Inventory.ini file for each toolbox, or template .\solutions-geoprocessing-toolbox\utils\deploy\inventories
- A unit test for the deployment script, that would 'deploy' several example templates to an intermediate folder, then check the contents against the inventory files.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/129342386639048/152131732600120)

**Comment by topowright** [comment]
Based on us now using Jenkins to deliver our solutions I do not think this is needed. we are able to use path checkout tool with the git command to get exactly what we need. I am going to close this with an invalid label.
