### ISSUE TITLE
Detaset for testing solutions-geoprocessing-toolbox

### ISSUE THREAD

**Issue by igrSimonSandberg** [Esri/solutions-geoprocessing-toolbox#459]
I have been tasked with testing solutions-geoprocessing-toolbox and to see whether the tools can be used in my organisation.

My problem is that the data I have access to is coded differently from what the tools are set up for.
Is there a dataset I can download, with the right coding, i can then use to see whether the solutions-geoprocessing-tools are something for us?

**Comment by mfunk** [comment]
Hello @igrSimonSandberg, 
This repository is basically a way for us to store and manage tools that are part of Solutions maps/apps [http://solutions.arcgis.com/](http://solutions.arcgis.com/). That means there are MANY tools (about 200) in several toolboxes (about 70). Many of these tools are part of map/app Solution products that include sample data and workflows. Can you identify which tools/toolboxes and which ArcGIS version you are interested in working with? That way I can make suggestions as to which template maps/apps you can take a look at.

**Comment by igrSimonSandberg** [comment]
Of course. 
I work with ArcGIS 10.4.1 for Desktop. And I am looking at the Military Aspects of Terrain Tools, Helicopter Landing Zone Tools, Point Of Origin Tools, Clearing Operations Tools,  Range Card Tools and ERG Tools.

**Comment by mfunk** [comment]
@igrSimonSandberg 

So as I mentioned the templates that include include tutorials and exercise data can be downloaded from our our Solutions page: [http://solutions.arcgis.com/](http://solutions.arcgis.com/). But you can also download many of the original templates from the Downloads: [http://appsforms.esri.com/products/download/#ArcGIS_for_Defense](http://appsforms.esri.com/products/download/#ArcGIS_for_Defense).

These have online documentation as well as a download:
* Military Aspects of Terrain: http://solutions.arcgis.com/defense/templates/maot/
* Helicopter Landing Zones: http://solutions.arcgis.com/defense/templates/hlz/
* Clearing Operations: http://solutions.arcgis.com/defense/templates/clearing-operations/

These are just a template download and don't have any online help:
* Point of Origin (for ArcGIS 10.2): http://appsforms.esri.com/products/download/index.cfm?fuseaction=download.main&downloadid=1569
* Range Card Tools (for ArcGIS 10.4): http://appsforms.esri.com/products/download/index.cfm?fuseaction=download.main&downloadid=1889

The ERG Tools are the only one that doesn't have a full template or online help and are a stand-alone tool. As far as I know this tool doesn't need any outside data.

**Comment by igrSimonSandberg** [comment]
I have downloaded the tamplates and the data from the links you have provided, but I still get broken data links. I have also attempted to run the "cover and concealment" tool and I can't get it to work because I can't give it the correct data input.

I have run through the "Getting_Started_with_the_Military_Aspects_of_Terrain_template.pdf" and I get stuck at the part you can see below.

![image](https://cloud.githubusercontent.com/assets/22344598/18905058/87f53236-8561-11e6-9745-fcfd926aac5c.png)

I can't find the MAOT.sde and I don't have a connection to the Land Ops server already set up.
Neither can find the MAoT.gdb, in the data I have downloaded.

Can you give me access to one of those things or am I on the wrong tract?

**Comment by mfunk** [comment]
@igrSimonSandberg I didn't realize how old this template is. First, the *.sde* file is a connection to an enterprise geodatabase (think Oracle) so if you don't have one that you know about, then I would skip that. Instead I found the reference link to the Operational Environment data in an older template download link (http://esrifederal.maps.arcgis.com/home/item.html?id=21365ac7f05648c4a69cc6b8125aa584). In the description it has the link to the data as:

```
This version of Military Aspects of Terrain works with ArcGIS 10.1 and requires the Operational Environment (OE) sample data schema.

Operational Environment Sample Data

Warning: ZIP file download is 560 MB. Unzipped data is approximately 1.3 GB.

The Operational Environment is part of the information  model for either Land Operations or Maritime Operations. It is an organizing structure for foundation data used in Intelligence Preparation of the Battlefield (IPB). This version specifically includes urban topographic data and elevation and imagery mosaic datasets.
```

The ZIP file is about 574 MB and took about 4 minutes to download. After extracting I got these files:
![image](https://cloud.githubusercontent.com/assets/3093182/18915931/8006aa92-8547-11e6-860b-91a20abc1ffb.png)

After I did that I opened the *Create Suitability Overlays.mxd* and was able to fix most of the broken links by connecting to the data in the *MAoT.gdb* and *digitalelevationmodel.gdb*. Basically you can click on the red exclamation (!) and reset the data source. I did this for:

* Combined Vegetation Coverage  --> MAoT.gdb/CombinedVegetationCoverage
* Slope --> digitalelevationmodel.gdb/Slope

The *Elevation Service* layer should probably match up with digitalelevationmodel.gdb/DigitalElevationModel, but doesn't seem to like the connection. You should probably just drag the DigitalElevationModel into the map directly and use it instead.

I didn't look at the other MXDs in the MAoT template, but the process would be simiar, to match the broken layers to the features/rasters in digitalelevationmodel.gdb, MAoT.gdb, and utds.gdb. That being said I think the tools really only use *Create Suitability Overlay.mxd*. The others are for publishing map products for planning.
