### ISSUE TITLE
Run Range Fan geoprocessing service error

### ISSUE THREAD

**Issue by jyi67** [Esri/solutions-geoprocessing-toolbox#46]
I successfully published the Range Fan service (Visibility and Range Tools.tbx\Range Fan tool). However, the Range Fan geoprocessing service cannot be run. In ArcGIS Server log, it says:

PYTHON ERRORS: Traceback info: File "C:\arcgisserver\directories\arcgissystem\arcgisinput\RangeFan.GPServer\extracted\v101\toolboxes\RangeFan.py", line 91, in shapefieldname = arcpy.Describe(prjInFeature).ShapeFieldName Error Info: "c:\arcgisserver\directories\arcgisjobs\rangefan_gpserver\ja4e234d0a9934efaa82727afdb487f03\scratch\prjInFeature" does not exist ArcPy ERRORS: Executing: Project c:\arcgisserver\directories\arcgisjobs\rangefan_gpserver\ja4e234d0a9934efaa82727afdb487f03\scratch\scratch.gdb\obs c:\arcgisserver\directories\arcgisjobs\rangefan_gpserver\ja4e234d0a9934efaa82727afdb487f03\scratch\prjInFeature PROJCS['WGS_1984_Web_Mercator_Auxiliary_Sphere',GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Mercator_Auxiliary_Sphere'],PARAMETER['False_Easting',0.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',0.0],PARAMETER['Standard_Parallel_1',0.0],PARAMETER['Auxiliary_Sphere_Type',0.0],UNIT['Meter',1.0]] # PROJCS['WGS_1984_Web_Mercator_Auxiliary_Sphere',GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Mercator_Auxiliary_Sphere'],PARAMETER['False_Easting',0.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',0.0],PARAMETER['Standard_Parallel_1',0.0],PARAMETER['Auxiliary_Sphere_Type',0.0],UNIT['Meter',1.0]],VERTCS['WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PARAMETER['Vertical_Shift',0.0],PARAMETER['Direction',1.0],UNIT['Meter',1.0]] Start Time: Mon Jul 21 13:10:13 2014 Succeeded at Mon Jul 21 13:10:13 2014 (Elapsed Time: 0.12 seconds) Failed to execute (sourceRangeFan). Failed to execute (RangeFan). Failed to execute (Range Fan).

**Comment by mfunk** [comment]
Web Mercator issues were fixed in recent commits by 1) adding Spatial Reference option and 2) by choosing between SR option and Input Centers as the default spatial reference.

@jyi67 would you please retest?

**Comment by mfunk** [comment]
Closing.
