### ISSUE TITLE
ERG: Change lookup value storage from .dbf to file geodatabase table

### ISSUE THREAD

**Issue by elinz** [Esri/solutions-geoprocessing-toolbox#467]
## Current Behavior

ERG lookup values are stored in .dbf format, which has limitations such as a field name limit of 10 characters, and you can set field aliases.

While updating the lookup values to ERG 2016, many new fields were added. Being limited to 10 characters for field names leads to extremely difficult to read abbreviated field names; the issue is compounded because we can't set a field alias to describe the contents of the field.

@kgonzago @joebayles FYI.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by mfunk** [comment]
Should consider .CSV as alternative. This would be MUCH easier to update for next ERG changes.

**Comment by mfunk** [comment]
The tool/toolbox associated with this issue has been deprecated and is no longer actively supported. Earlier versions of this toolbox will still be available from previous [Releases](https://github.com/Esri/solutions-geoprocessing-toolbox/releases)
