### ISSUE TITLE
ERG: does not handle initial isolation and protective action distances defined in Table 3 and Guide section of ERG

### ISSUE THREAD

**Issue by elinz** [Esri/solutions-geoprocessing-toolbox#468]
## Current Behavior

The gp tools and underlying data table do not account for the materials specified in Table 3 (Initial isolation and protective action distances for large spills for different quantities of six comman TIH [Toxic Inhalation Harard] gases) and the Guide (i.e. orange) section of the Emergency Responsive Guidebook.

Table 3 specifies the isolate in all directions distance based on the transport container; and for protective action distances based on time of day and wind speeds for large spills. The current data table has isolation and protective action distances which are not based on the transport container or wind speed. I'm not sure how the values in the current data table where derived.

@kgonzago @joebayles FYI. I consider this a showstopper. There's no GitHub label for showstopper.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by mfunk** [comment]
The tool/toolbox associated with this issue has been deprecated and is no longer actively supported. Earlier versions of this toolbox will still be available from previous [Releases](https://github.com/Esri/solutions-geoprocessing-toolbox/releases)
