### ISSUE TITLE
Clearing Ops - GRG Canvas Area Tool model and "Canvas Area GRG Script" not referencing tools

### ISSUE THREAD

**Issue by jfrygeo** [Esri/solutions-geoprocessing-toolbox#47]
There was a problem with windows not finding the path to the toolboxes. 

I was able to get it working on my machine by changing the first line of code (commented out) to the second.

#toolboxPath = os.path.dirname(os.path.dirname(arcpy.env.workspace)) + "\\toolboxes\ClearingOperations.tbx"
toolboxPath = os.path.dirname(arcpy.env.workspace) + "\\toolboxes\ClearingOperations.tbx"

#arcpy.ImportToolbox(toolboxPath, "VillageClearing")
arcpy.ImportToolbox(toolboxPath, "ClearingOperations")
...........................
...........................

Also fixed references to the .lyr file at the end of the script.

#symbologyPath = os.path.abspath(os.path.join(os.path.dirname(arcpy.env.workspace), os.pardir)) + "\data\Layers\GRG.lyr"

symbologyPath = os.path.dirname(arcpy.env.workspace) + "\data\Layers\GRG.lyr"

**Comment by mfunk** [comment]
@jscott11 can you check it this is 'fixed' or not?

**Comment by jscott11** [comment]
@mfunk this is pretty much the same problem Joe was having with #185 and #186 . I'm hoping to have a fix submitted for this today, and that'll take care of all 3 of these.

**Comment by mfunk** [comment]
@jscott11 excellent. thanks for the info!

**Comment by joebayles** [comment]
@jfrygeo as the author of this issue, can you verify?
