### ISSUE TITLE
Repo issue: The link in the "Running Verification Tests" section of Readme.md is broken

### ISSUE THREAD

**Issue by elinz** [Esri/solutions-geoprocessing-toolbox#470]
(Update) - Here: https://github.com/Esri/solutions-geoprocessing-toolbox#running-verification-tests

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by csmoore** [comment]
Verify in #513

**Comment by mfunk** [comment]
Link works. Closing.
