### ISSUE TITLE
ERG tests won't execute; throws "ImportError: No module named Configuration" error

### ISSUE THREAD

**Issue by elinz** [Esri/solutions-geoprocessing-toolbox#471]
## Current Behavior

Tried running the following scripts, which all threw the same error:
ERGByChemicalTestCase.py
ERGByPlacardTestCase.py
ERGScriptTestCase.py
ERGToolsTestSuite.py
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by mfunk** [comment]
The tool/toolbox associated with this issue has been deprecated and is no longer actively supported. Earlier versions of this toolbox will still be available from previous [Releases](https://github.com/Esri/solutions-geoprocessing-toolbox/releases)
