### ISSUE TITLE
Cover from Flat Trajectory Weapons failing

### ISSUE THREAD

**Issue by BobBooth** [Esri/solutions-geoprocessing-toolbox#472]
While testing the MAoT template, I've found that the Cover from Flat Trajectory Weapons is failing a couple of different ways.
1) the tool is set up to only take image service as input for the terrain; if you don't have one, you have to edit the tool properties.  Default service is GIS Servers\arcgis on dislcomags01_6080 (user)\BattlefieldEnv\Slope.ImageServer
2) After loading image services from Operational Environment data, ran the tool. It failed with a warning and an error message in the output:
WARNING 000950: Output raster exceeds the size limitation (rows: 4100 and columns: 15000) defined on the image server. Please input a smaller extent.
...
...
if min(slopeCat,vegCat) == 2: return "FAIR"  \n      if min(slopeCat,vegCat) == 3: return "GOOD"\n\n"
Start Time: Fri Feb 03 14:12:39 2017
ERROR 000539: Invalid field grid_code
Failed to execute (Calculate Field: Final Suitability).
Failed at Fri Feb 03 14:12:39 2017 (Elapsed Time: 0.02 seconds)
Failed to execute (CoverFromFlatTrajectoryWeapons).
Failed at Fri Feb 03 14:12:40 2017 (Elapsed Time: 3 minutes 43 seconds)

I re-ran the tool with a much smaller AOI, still failed with this in the output:
if min(slopeCat,vegCat) == 2: return "FAIR"  \n      if min(slopeCat,vegCat) == 3: return "GOOD"\n\n"
Start Time: Fri Feb 03 14:28:22 2017
ERROR 000539: Invalid field grid_code
Failed to execute (Calculate Field: Final Suitability).
Failed at Fri Feb 03 14:28:22 2017 (Elapsed Time: 0.02 seconds)
Failed to execute (CoverFromFlatTrajectoryWeapons).
Failed at Fri Feb 03 14:28:23 2017 (Elapsed Time: 3 minutes 32 seconds)

## Your Environment

ArcGIS 10.3.1

**Comment by lfunkhouser** [comment]
The Military Aspects of Terrain tools will not be enhanced. Last supported version was 10.1. These tools are retired as of the April 2018 release. Future work is planned for environmental impacts on operations, release date TBD.
