### ISSUE TITLE
Suitable HLZs (MAoT) only accepts feature layer inputs for AOI, not feature sets

### ISSUE THREAD

**Issue by BobBooth** [Esri/solutions-geoprocessing-toolbox#473]
The Suitable HLZs tool only accepts feature layer inputs for AOI, not feature sets, (in contrast: Concealment From Aerial Detection and Cover From Flat Trajectory Weapons, Suitable Drop Zones accept both). Why?
Tool Help suggests that it supports feature set input: "You must select an area (polygon) layer or use the Area of Interest tool to draw one on the map.

## Your Environment

ArcMap 10.3.1

**Comment by lfunkhouser** [comment]
The Military Aspects of Terrain tools will not be enhanced. Last supported version was 10.1. These tools are retired as of the April 2018 release. Future work is planned for environmental impacts on operations, release date TBD.
