### ISSUE TITLE
Suitable Drop Zones tool (MAoT) fails with ERROR 000539: Invalid field grid_code when run on local slope data

### ISSUE THREAD

**Issue by BobBooth** [Esri/solutions-geoprocessing-toolbox#474]
The Suitable Drop Zones tool (MAoT) fails when run on local slope data with this message:
Start Time: Thu Feb 02 14:37:04 2017
ERROR 000539: Invalid field grid_code
Failed to execute (Calculate Field).

Failed at Thu Feb 02 14:37:04 2017 (Elapsed Time: 0.02 seconds)
Failed to execute (SuitableDropZones).
Failed at Thu Feb 02 14:37:05 2017 (Elapsed Time: 5 minutes 16 seconds)\militaryaspectsofterrain_1.0.0\Maps\Toolbox\sc

This is using the Operational Environment data.

## Your Environment
ArcMap 10.3.1

**Comment by lfunkhouser** [comment]
The Military Aspects of Terrain tools will not be enhanced. Last supported version was 10.1. These tools are retired as of the April 2018 release. Future work is planned for environmental impacts on operations, release date TBD.
