### ISSUE TITLE
Off-road mobility FM 5-33 CCM tool (MAoT) error on Input Vegetation Table 

### ISSUE THREAD

**Issue by BobBooth** [Esri/solutions-geoprocessing-toolbox#475]
Ran the Off-road mobility FM 5-33 CCM tool, got an error on Input Vegetation Table (bad path to data)
\l "ERROR HYPERLINK  \l "000732 
Input Vegetation Table: Dataset C:\Workspace\ArcGIS Defense 10.1\MAoT for A4W\A4W\Military Aspects of Terrain Template\Maps\OperationGDB.gdb\maotLandCover does not exist or is not supported
I re-pointed it to:
C:\MAOT_Test\Operational_Environment\Data\MAoT\MAoT_Examples.gdb\maotVehicleParameters

I can't find the soils or Surface Roughness feature class/tables in the Operational Environment data.

## Your Environment
ArcMap 10.3.1

**Comment by lfunkhouser** [comment]
The Military Aspects of Terrain tools will not be enhanced. Last supported version was 10.1. These tools are retired as of the April 2018 release. Future work is planned for environmental impacts on operations, release date TBD.
