### ISSUE TITLE
Output error in test_incident_density_pro in ArcGIS Pro

### ISSUE THREAD

**Issue by mfunk** [Esri/solutions-geoprocessing-toolbox#477]
Output from test_incident_density_pro is not being created and test is failing. This test does not fail in ArcMap.

## Expected Behavior
Test should run and not fail (duh), specifically the output should exist after the test is done.

## Current Behavior
Error in automated test test_incident_density_pro

```
test_incident_density_pro (patterns_tests.IncidentDensityTestCase.IncidentDensityTestCase)Traceback (most recent call last):
  File "D:\GitHub\solutions-geoprocessing-toolbox\utils\test\patterns_tests\IncidentDensityTestCase.py", line 78, in test_incident_density_pro
    self.assertTrue(arcpy.Exists(outputDensity))
AssertionError: False is not true
```

## Steps to Reproduce (for bugs)
Run automated tests
1. Open command prompt in solutions-geoprocessing-toolbox folder
2. cd .\utils\test
3. .\TestKickStarter.bat

## Context
Found during 10.5 testing during automated test run from repo (Pro 1.4.1 is run along with it).

## Your Environment
* Version used: ArcGIS Pro 1.4.1
* Environment name and version (e.g. Chrome 39, node.js 5.4): N/A
* Operating System and version (desktop or mobile): Windows 10

**Comment by csmoore** [comment]
Looking closer at this error, it is being caused here:

ERROR 000725: Output Density Overlay: Dataset C:\...\AppData\Local\Temp\scratch.gdb\IncidentDensitySurface_Output already exists.

![image](https://user-images.githubusercontent.com/3090809/29074277-b10cb7d6-7c1c-11e7-9829-a7b910188eee.png)

Adding: arcpy.env.overwriteOutput did not fix this error so added a more specific workaround to the test driver, but not sure how this tool is working in Pro. Workaround added in https://github.com/Esri/solutions-geoprocessing-toolbox/commit/7a2de796856097ad5b606d2f0bb7a75046590bcd

**Comment by csmoore** [comment]
Verify with/after #563

**Comment by mfunk** [comment]
Verified as running in test cases.
