### ISSUE TITLE
Error creating output in test_cluster_analysis_pro in ArcGIS Pro

### ISSUE THREAD

**Issue by mfunk** [Esri/solutions-geoprocessing-toolbox#478]
Error in the automated test of test_cluster_analysis_pro.

## Expected Behavior
Test should run and not fail (duh), specifically the output should exist after the test is done.

## Current Behavior
Error in ArcGIS Pro automated test

```
test_cluster_analysis_pro (patterns_tests.ClusterAnalysisTestCase.ClusterAnalysisTestCase)Traceback (most recent call last):
  File "D:\GitHub\solutions-geoprocessing-toolbox\utils\test\patterns_tests\ClusterAnalysisTestCase.py", line 77, in test_cluster_analysis_pro
    arcpy.ClusterAnalysis_iaTools(self.inputPointsFeatures, "#", outputClusterFeatures)
arcgisscripting.ExecuteError: ERROR 000210: Cannot create output C:\Users\<user>\AppData\Local\Temp\\copy_cluster
Failed to execute (Copy Features).
Failed to execute (ClusterAnalysis).


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\GitHub\solutions-geoprocessing-toolbox\utils\test\patterns_tests\ClusterAnalysisTestCase.py", line 80, in test_cluster_analysis_pro
    self.fail('Exception in ClusterAnalysis_iaTools for Pro toolbox \n' + msg)
AssertionError: Exception in ClusterAnalysis_iaTools for Pro toolbox
ERROR 000210: Cannot create output C:\Users\<user>\AppData\Local\Temp\\copy_cluster
Failed to execute (Copy Features).
Failed to execute (ClusterAnalysis).
```

## Possible Solution
Check how the output path is being assigned before the tool is run. Seems like the output path might be getting messed up  somehow.

## Steps to Reproduce (for bugs)
Run automated tests

Open command prompt in solutions-geoprocessing-toolbox folder
cd .\utils\test
.\TestKickStarter.bat

## Your Environment
Version used: ArcGIS Pro 1.4.1
Environment name and version (e.g. Chrome 39, node.js 5.4): N/A
Operating System and version (desktop or mobile): Windows 10

**Comment by csmoore** [comment]
Verify with/after #563

**Comment by mfunk** [comment]
Fixed.
