### ISSUE TITLE
Error with Search_Radius parameter in test_count_incidents_pro (and test_count_incidents_desktop)

### ISSUE THREAD

**Issue by mfunk** [Esri/solutions-geoprocessing-toolbox#479]
Getting an error in automated test for Incident Analysis test_count_incidents_pro. Does not happen in Desktkop test.

## Expected Behavior
Should not fail.

## Current Behavior
Error in the test_count_incidents_pro automated test.

```
test_count_incidents_pro (patterns_tests.CountIncidentsByLOCTestCase.CountIncidentsByLOCTestCase)Traceback (most recent call last):
  File "D:\GitHub\solutions-geoprocessing-toolbox\utils\test\patterns_tests\CountIncidentsByLOCTestCase.py", line 73, in test_count_incidents_pro
    arcpy.CountIncidentsByLOC_iaTools(self.inputPointsFeatures, self.inputLinesFeatures, "#", outputCountFeatures)
arcgisscripting.ExecuteError: ERROR 000622: Failed to execute (Count Incidents By LOC). Parameters are not valid.
ERROR 000628: Cannot set input into parameter Search_Radius.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\GitHub\solutions-geoprocessing-toolbox\utils\test\patterns_tests\CountIncidentsByLOCTestCase.py", line 76, in test_count_incidents_pro
    self.fail('Exception in CountIncidentsByLOC_iaTools in Pro toolbox \n' + msg)
AssertionError: Exception in CountIncidentsByLOC_iaTools in Pro toolbox
ERROR 000622: Failed to execute (Count Incidents By LOC). Parameters are not valid.
ERROR 000628: Cannot set input into parameter Search_Radius.
```

## Possible Solution
Change in parameter order for the tool? Have to crack open the model and see if any parameters have changed for the constituent tools.

## Steps to Reproduce (for bugs)
Run automated tests

1. Open command prompt in solutions-geoprocessing-toolbox folder
2. cd .\utils\test
3. .\TestKickStarter.bat

## Your Environment
Version used: ArcGIS Pro 1.4.1
Environment name and version (e.g. Chrome 39, node.js 5.4): N/A
Operating System and version (desktop or mobile): Windows 10

**Comment by csmoore** [comment]
Error also occurs for me in ArcMap 10.4.1 - updating title/tags:

```
test_count_incidents_desktop (patterns_tests.CountIncidentsByLOCTestCase.CountIncidentsByLOCTestCase)Traceback (most recent call last):
  File "C:\Users\----\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\patterns_tests\CountIncidentsByLOCTestCase.py", line 97, in test_count_incidents_desktop
    self.assertFeatureClassEqual(self.resultCompareFeatures0001,outputCountFeatures,"OBJECTID")
  File "C:\Users\----\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\arcpyAssert.py", line 89, in assertFeatureClassEqual
    out_compare_file=compare_file[1])
  File "C:\Program Files (x86)\ArcGIS\Desktop10.4\ArcPy\arcpy\management.py", line 419, in FeatureCompare
    raise e
ExecuteError: Failed to execute. Parameters are not valid.
ERROR 000732: Input Base Features: Dataset C:\Users\----\Documents\GitHub\solutions-geoprocessing-toolbox\utils\test\patterns_tests\data\test_incident_analysis_results.gdb\resultsCountIncidentsByLOC_0001 does not exist or is not supported
Failed to execute (FeatureCompare).
```

**Comment by csmoore** [comment]
Addressed in https://github.com/Esri/solutions-geoprocessing-toolbox/commit/3a935ccd545245d51f6881c42d7973263e7715df 

There were a couple of issues going on:

1. Parameters are ordered differently in Pro 
2. Pro *only* takes a feature layer as input (not feature class) because of differences in behavior of Select Layer By Location tool in ArcMap/Pro

There is still an issue where Pro version of CountIncidentsByLOC creates slightly different output from ArcMap version but will record as a different issue.

**Comment by mfunk** [comment]
Unfortunately @csmoore Pro has been known to reorder the parameters in model/script tools. This has been an persistent problem with Pro for several versions as @topowright will verify.

**Comment by csmoore** [comment]
Verify with/after #563

**Comment by mfunk** [comment]
Fixed.
