### ISSUE TITLE
Find Local Peaks will not run

### ISSUE THREAD

**Issue by topowright** [Esri/solutions-geoprocessing-toolbox#480]
The Local Peaks tool shows this error: 

![image](https://cloud.githubusercontent.com/assets/5488313/24430201/52820384-13ca-11e7-874a-856e3d2252f2.png)

## Expected Behavior

Tool runs and returns local peaks
## Current Behavior

Tool does not run
## Possible Solution

We should replace the tool script with Military Tools with this tool
## Steps to Reproduce (for bugs)

1. Run the find local peaks tool
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by topowright** [comment]
This is also an issue with Highest Points:
https://github.com/Esri/solutions-geoprocessing-toolbox/issues/444

**Comment by mfunk** [comment]
The tool/toolbox associated with this issue has been deprecated and is no longer actively supported. Earlier versions of this toolbox will still be available from previous [Releases](https://github.com/Esri/solutions-geoprocessing-toolbox/releases)
