### ISSUE TITLE
Incident Analysis - Incident Table to Point model is broken

### ISSUE THREAD

**Issue by elinz** [Esri/solutions-geoprocessing-toolbox#484]
Can't run or open the model:
![image](https://cloud.githubusercontent.com/assets/4635490/25092671/956d2ef2-2343-11e7-9a1b-52ee41b7d018.png)

Here's the current model:
![image](https://cloud.githubusercontent.com/assets/4635490/25092695/b3cbe83e-2343-11e7-8685-765bc1f7a626.png)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by mfunk** [comment]
This model was removed from Incident Analysis tools. The model added some field manipulation that the core **Convert Coordinate Notation** now does, making this model unnecessary.
