### ISSUE TITLE
Incident Analysis - Incident Table to Point model creates duplicate fields (ArcMap)

### ISSUE THREAD

**Issue by elinz** [Esri/solutions-geoprocessing-toolbox#485]
After running the model, the output point feature class will have all the fields duplicated.
For example, if source table has fields A, B, and C, the output feature class will have A, B, C, A_1, B_1, C_1.

## Expected Behavior

I would expect that the output feature class would not have these duplicate fields.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by elinz** [comment]
Talked with @mfunk and learned that the issue is caused by newer versions of the Convert Coordinate Notation gp tool copy the fields from the source table into the output feature class. Older versions of the Convert Coordinate Notation tool did not copy the fields, so the Incident Table to Point gp tool model performed a "join" so that the output feature class would contain the fields from the input table. Based on the behavior of the newer versions of Convert Coordinate Notation gp tool, I believe there is no reason for the Incident Table to Point model to exist. Deleting this model would also fix issue #484.

**Comment by mfunk** [comment]
@elinz Going to drop this one as a known issue with previous version of the template, since we are removing Incident Table To Point entirely.
