### ISSUE TITLE
Incident Analysis - Incident Table to Point model creates duplicate fields (ArcGIS Pro)

### ISSUE THREAD

**Issue by elinz** [Esri/solutions-geoprocessing-toolbox#487]
Same as #485 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by mfunk** [comment]
Known Issue/As Designed however Incident Table To Point is being removed from future versions of the template.
