### ISSUE TITLE
Incident Analysis - "Change Sample Data Dates to Recent Dates" gp tool fails if fields already exist (ArcGIS Pro)

### ISSUE THREAD

**Issue by elinz** [Esri/solutions-geoprocessing-toolbox#490]
This tool adds the tempDate and tempPosted fields. If these fields already exist the tool will fail without calculating the date fields. The tool should calculate the date fields even if the fields already exist. This is how the ArcMap version of the gp tool is working.

Here is the output from the tool:

Start Time: Friday, April 28, 2017 11:08:02 AM
Executing (Add Field): AddField "Incidents\All Incidents" tempDate DATE # # # # NULLABLE NON_REQUIRED #
Start Time: Friday, April 28, 2017 11:08:05 AM
 ERROR 000012: tempDate already exists
Failed to execute (Add Field).
Failed at Friday, April 28, 2017 11:08:05 AM (Elapsed Time: 0.01 seconds)
Failed to execute (ChangeSampleDataDatestoRecentDates).
Failed at Friday, April 28, 2017 11:08:05 AM (Elapsed Time: 2.46 seconds)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by elinz** [comment]
Upon further investigation, I found that the message type is different in ArcMap and ArcGIS Pro. In ArcMap, if the field being added by the Add Field gp tool already exists, the message type thrown is a warning, in ArcGIS Pro it's an error. The model does perform a "delete field", but it actually performs the delete on the scratch output feature class. I'll change so that the delete field is performed on the final output incidents feature class.

**Comment by mfunk** [comment]
Tested from recent PR #493 and is working as expected in ArcGIS Pro.

```
Start Time: Wednesday, May 3, 2017 8:11:50 AM
Executing (Add Field): AddField "Incidents\All Incidents" tempDate DATE # # # # NULLABLE NON_REQUIRED #
Start Time: Wednesday, May 3, 2017 8:11:51 AM
Adding tempDate to Incidents\All Incidents...
Succeeded at Wednesday, May 3, 2017 8:11:53 AM (Elapsed Time: 2.00 seconds)
Executing (Calculate Field): CalculateField "Incidents\All Incidents" tempDate datetime.datetime.now( ) PYTHON_9.3 #
Start Time: Wednesday, May 3, 2017 8:11:53 AM
Succeeded at Wednesday, May 3, 2017 8:12:00 AM (Elapsed Time: 6.75 seconds)
Executing (Sort): Sort "Incidents\All Incidents" C:\Users\<user>\Documents\ArcGIS\Projects\IncidentAnalysis_DBARNES_2MAY2017_1445\results.gdb\SIGACTS_Sort "datetimestart DESCENDING" UR
Start Time: Wednesday, May 3, 2017 8:12:00 AM
Succeeded at Wednesday, May 3, 2017 8:12:01 AM (Elapsed Time: 0.92 seconds)
Executing (Get Field Value (2)): GetFieldValue C:\Users\<user>\Documents\ArcGIS\Projects\IncidentAnalysis_DBARNES_2MAY2017_1445\results.gdb\SIGACTS_Sort datetimestart Date #
Start Time: Wednesday, May 3, 2017 8:12:02 AM
Succeeded at Wednesday, May 3, 2017 8:12:02 AM (Elapsed Time: 0.19 seconds)
Executing (Calculate tempDate field): CalculateField "Incidents\All Incidents" tempDate calcDay(!datetimestart!, '5/2/2017 1:10:54 PM') PYTHON_9.3 "import datetime\nfrom dateutil.parser import *\ndef calcDay (x,y):\n    #Get today's date\n    rNow =  datetime.datetime.now()\n    \n    #Get the most recent date\n    oldDate = parse(y)\n    \n    #Get the record date\n    recDate= parse(x)\n    \n    # get the delta\n    tDiff = rNow - oldDate\n    \n    # add the days delta to the record date\n    newDay = recDate + tDiff\n    return newDay"
Start Time: Wednesday, May 3, 2017 8:12:02 AM
Succeeded at Wednesday, May 3, 2017 8:12:12 AM (Elapsed Time: 9.75 seconds)
Executing (Calculate new datetimestart field): CalculateField "Incidents\All Incidents" datetimestart !tempDate! PYTHON_9.3 #
Start Time: Wednesday, May 3, 2017 8:12:12 AM
Succeeded at Wednesday, May 3, 2017 8:12:20 AM (Elapsed Time: 7.78 seconds)
Executing (Delete temp fields): DeleteField "Incidents\All Incidents" tempDate
Start Time: Wednesday, May 3, 2017 8:12:20 AM
Dropping tempDate from Incidents\All Incidents...
Succeeded at Wednesday, May 3, 2017 8:12:21 AM (Elapsed Time: 0.99 seconds)
Succeeded at Wednesday, May 3, 2017 8:12:21 AM (Elapsed Time: 30.79 seconds)
```
