### ISSUE TITLE
Incident Analysis - Sample Data Update Tool Doc Typo

### ISSUE THREAD

**Issue by joebayles** [Esri/solutions-geoprocessing-toolbox#491]
The tool doc for **Change Sample Data Dates to Recent Dates** has a typo.

`This tool takes the incident sample data and ajusts the dates to make the sample data seem recent. This is useful for tutorial purposes because it allows you to use the Incident Analysis map with layer definition queries that pull out parts of the incident data for the last 24, 48, 72 hours, or last 30 days, and the month before last, based on your system's current date.`

> ... and **ajusts**...

#### Possible Solutions

- [ ] Fix the typo
- [x] Change it to:
`This tool updates the incident sample data dates for the rest of the time-based analysis to work. This allows the the Incident Analysis map to use layer definition queries for the last 24, 48, and 72 hours, last 30 days, and the month before last, based on your system's current date.`

**Comment by joebayles** [comment]
Not sure if this is intended, but the picture is pretty grainy.
![image](https://cloud.githubusercontent.com/assets/5016557/25647341/01fb8422-2f76-11e7-975e-90e7dda30d7f.png)

**Comment by joebayles** [comment]
Not fixed.

**Comment by mfunk** [comment]
This was on the *MFUNK 5/9/2017 10:05AM Pacific* version?

**Comment by joebayles** [comment]
You're right, it was.
