### ISSUE TITLE
Incident Analysis - Cluster Analysis Issue

### ISSUE THREAD

**Issue by joebayles** [Esri/solutions-geoprocessing-toolbox#492]
When running the tool with all defaults, the tool runs successfully, but clusters all incidents into one cluster.

## Expected Behavior

![image](https://cloud.githubusercontent.com/assets/5016557/25631765/3ffec7ca-2f26-11e7-80ba-d2d8a5a42d8b.png)

## Current Behavior

![image](https://cloud.githubusercontent.com/assets/5016557/25631767/4222afa8-2f26-11e7-9bb7-9da5bbc3c022.png)

## Your Environment

* Version used: 4.0.2
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile): Windows 10, ArcGIS 10.5
* Link to your project:

### FYI @Dbarnes1 @BobBooth @elinz @lfunkhouser

**Comment by joebayles** [comment]
I went back and tried to reproduce this and failed. Went back and looked at the GP Results. Apparently, it changed to 500 _Miles_ instead of _Meters_. Closing.

**Comment by BobBooth** [comment]
500 Meters seems to have been the default, when I last grabbed the Pro project template. Not to say someone didn't change it.

**Comment by joebayles** [comment]
That's the weird thing. When I re-ran it, it defaulted to meters. I didn't change it to miles. Oh well.
