### ISSUE TITLE
Incident Analysis - Percent Change - Symbology not honoring in ArcMap

### ISSUE THREAD

**Issue by joebayles** [Esri/solutions-geoprocessing-toolbox#496]
The Output from the **Find Percent Change** Tool in ArcMap is not honoring the symbology.

## Expected Behavior

![image](https://cloud.githubusercontent.com/assets/5016557/25643201/1e6f1ccc-2f53-11e7-828c-0e7b7459b062.png)

## Current Behavior

![image](https://cloud.githubusercontent.com/assets/5016557/25643207/28911872-2f53-11e7-87af-52e2889f43cc.png)

**Comment by joebayles** [comment]
@migueldls confirmed.

**Comment by mfunk** [comment]
Looking at tool output symbology and it's blank... not sure how it got lost but an easy fix.
![image](https://cloud.githubusercontent.com/assets/3093182/25677121/a311fa52-2ff9-11e7-9cb4-714904008ad0.png)

**Comment by elinz** [comment]
FYI. The layer file was set on the last "output" object of the model.

**Comment by joebayles** [comment]
Verified.
