### ISSUE TITLE
Incident Analysis - Find Percent Change tool - Output is not added to map (ArcGIS Pro)

### ISSUE THREAD

**Issue by elinz** [Esri/solutions-geoprocessing-toolbox#499]
When the Find Percent Change tool is run, the output feature class is not added to map. 

NOTE: also make sure that symbology is set correctly on output. ArcMap template version had a problem that may exist in the Pro version. See #496.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by Dbarnes1** [comment]
Verified, closing out. Transparency won't automatically get applied in Pro, so I'm going to add a sentence in the task instructing the user how to do so
