### ISSUE TITLE
Issues after testing #500 in ArcMap

### ISSUE THREAD

**Issue by joebayles** [Esri/solutions-geoprocessing-toolbox#501]
### Incident Hot Spot
- [x] Change Parameter Name `Incidents_OptimizedHotSpotAn` to `Incident Hot Spot`
- [x] Tool defaults back to ArcGIS/default.gdb

### Hot Spot by Area
- [x] Keeps features selected after completed analysis (Clear Selection either in doc or tool)
![image](https://cloud.githubusercontent.com/assets/5016557/25864601/e9dc0748-34a4-11e7-9e3c-1499ad555861.png)

- [ ] Group result layers (Add a doc step)

### Incident Density
- [ ] Raster output does not display

### Incidents by LOC
- [ ] Not receiving expected results

Expected:
![image](https://cloud.githubusercontent.com/assets/5016557/25864395/256acdd6-34a4-11e7-928b-90622fc91768.png)

Received:
![image](https://cloud.githubusercontent.com/assets/5016557/25864406/2d09e2c0-34a4-11e7-9af3-401c45b8596c.png)

#### FYI
@mfunk @Dbarnes1 @BobBooth @elinz @migueldls

**Comment by BobBooth** [comment]
@joebayles - did the default search radius get changed, for Count Incidents by LOC?  Or is it running against one of the subset layers rather than All Incidents?

**Comment by BobBooth** [comment]
@joebayles - also this:
https://github.com/ArcGIS/solutions-desktop-templates/issues/353

**Comment by BobBooth** [comment]
I'm seeing the same result.

**Comment by mfunk** [comment]
Tried two tests with Count Incidents by LOC, first using the Districts as the AOI, and second using the feature set tool to draw a box that completely encompasses the Roads layer. The difference in the AOI is the reason we are seeing differences.

Just looking at the Roads, Districts, and Incidents we can start to see the affect of adding an AOI. There are Roads and Incidents that extent outside of the Districts layer. Roads are medium gray, Districts in black and incidents are yellow dots. Notice on the eastern edge there are incidents that are outside of a black polygon. These incidents aren't counted.:
![image](https://cloud.githubusercontent.com/assets/3093182/25870462/04dc2898-34b9-11e7-8e85-1e697402b493.png)

Next look at the Analysis Results >> Count Incidents by LOC layer visually and check the number of features: 2971. Let's also zoom into the block of roads in District 4. Here are the original analysis results:
![image](https://cloud.githubusercontent.com/assets/3093182/25870648/af7195c2-34b9-11e7-9ba8-c8d0fca75192.png)

Next run Count Incidents by LOC using the Districts layer as the AOI clip:
1) Input Incident Point Features: Incidents\All Incidents
2) Input Line Features: Roads
3) Input Area Of Interest: Districts
4) Output Count by LOC Features: ......\RoadWIC_dist
5) Search Radius: 50 Meters
Here we get 2077 Results and very different output:
![image](https://cloud.githubusercontent.com/assets/3093182/25870741/16e1896a-34ba-11e7-9723-c9545140330f.png)


Finally we zoom to the Roads and draw a large box that completely encompasses all roads.
1) Input Incident Point Features: Incidents\All Incidents
2) Input Line Features: Roads
3) Input Area Of Interest: <use the tool to draw the box around roads>
4) Output Count by LOC Features: ......\RoadWIC_bigsquare
5) Search Radius: 50 Meters
This time we are back to 2971 features in the results and a similar (but not exact) result to the original.
![image](https://cloud.githubusercontent.com/assets/3093182/25870836/6b618e2c-34ba-11e7-9ac8-90126e3d18be.png)

I'm pretty certain that if we took out the AOI selection that the results would match the original data exactly. We have modified the tool for #321 so therefore the output should change. So here I can do one of three things:
1: Remove the AOI selection and put the tool back to what it was before #321.
2: Keep the tool as is with the AOI and use the new tool results as the sample data
3: Continue to tweak the tool and force the results to match the sample data (effectively an indefinite task as I am not sure how this will work out or how long it will take).

**Comment by BobBooth** [comment]
@mfunk - it is a rather different output.  I think the problem must be in the way the districts are being used - the geometry of the districts features may be corrupted some way, or the logic for applying them is off. I Dissolved the districts into one feature and got the same results.
These results are plainly wrong, though.
I would vote for option 1, as it actually produces reasonable results.
Given more time and resources perhaps we could go with option 3. 

How can a road feature that is completely inside the D-4 district, and the incidents within 50 m of it are also completely inside the D-4 district:
![image](https://cloud.githubusercontent.com/assets/3801392/25902438/868a805c-3567-11e7-846f-5ea49aa9892c.png)
go from having 59 points that are closest to it, with a search radius of 50 m:
![image](https://cloud.githubusercontent.com/assets/3801392/25902488/a725a260-3567-11e7-93aa-70d12c8e1e56.png)
to having 0 features that are closest to it, with the same search radius?
![image](https://cloud.githubusercontent.com/assets/3801392/25902508/bb4c61ac-3567-11e7-977e-4cddb1f3d7e5.png)

I guess the question is how much effort do we want to invest in making the AOI function work.

**Comment by BobBooth** [comment]
Ah. There's your problem, right there:
![image](https://cloud.githubusercontent.com/assets/3801392/25903084/6ff2f80e-3569-11e7-9900-49f0d17bdfa9.png)
When you do the copy features to make a subset of the roads, if the number of features changes (which it will, unless you select all of the roads) you renumber the OIDs in the copy, so when you join on them, you're joining the counts to the wrong roads.
![image](https://cloud.githubusercontent.com/assets/3801392/25903245/dce61ffe-3569-11e7-8a10-ad69c187c0af.png)

**Comment by BobBooth** [comment]
So, before the "Select Layer By Location" for the AOI, you need to add and calculate a new field with the oid values, and join on that static field later on.
@mfunk

**Comment by BobBooth** [comment]
Or do the Generate Near table step on the results of Copy Features after you do the  "Select Layer By Location" for the AOI.
@mfunk

**Comment by BobBooth** [comment]
@joebayles - I think the "Incident Density - Raster output does not display" issue is dependent on whether or not you have the Spatial Analyst extension checked on.
I tried it and saw the same, but the output included the message:
 - Could not create output raster layer; make sure that your Spatial Analyst extension has been checked out.
Checked SA on (it was not enabled), re-ran the tool, got the raster layer added.

**Comment by BobBooth** [comment]
@mfunk  - to fix LOC tool:
![image](https://cloud.githubusercontent.com/assets/3801392/25918982/3deeca36-359b-11e7-9c07-0730e6458929.png)
So it looks like this:
![image](https://cloud.githubusercontent.com/assets/3801392/25919018/5c7cca34-359b-11e7-8cf2-c2eee0220c3b.png)
I've emailed you a copy of the model.

**Comment by mfunk** [comment]
Hidden in the Output Density Overlay parameter help is this:

```
This tool will only work if Spatial Analyst extension is installed and activated.
```

Kinda crappy location of this message. This should be in a bullet point under Usage. Will fix this when I get to #500 today.

**Comment by mfunk** [comment]
# Incident Hot Spots:
* Parameter Names matching the XMetaL help doc:
   * Input Incident Point Features defaulting to "Incidents/All Incidents", filtering for Point features
   * Output Features defaulting to "%scratchGDB%/IncidentHotSpots"
   * Input Incident Boundary Features defaulting to "Districts", filtering for Polygon features

![image](https://cloud.githubusercontent.com/assets/3093182/25970884/330171b4-364f-11e7-883e-d70ced80c034.png)

![image](https://cloud.githubusercontent.com/assets/3093182/25970934/547141bc-364f-11e7-9ba5-20f2164a974b.png)

**Comment by mfunk** [comment]
Hot Spots by Area
* Input Area of Interest Features defaults to "Districts", and is filtering for Polygon features.
* Input Incident Points Features defaults to "All Incidents", and is filtering for Point features
* Incident Points Name Field defaults to "District"
* Output Workspace is blank by default, and filters for Local Database and Remote Database

![image](https://cloud.githubusercontent.com/assets/3093182/25973863/ca03fba8-365a-11e7-84e6-05592f42f6df.png)

![image](https://cloud.githubusercontent.com/assets/3093182/25973867/ce63ff2c-365a-11e7-867d-3735ae3349ff.png)

This fixes #502.

**Comment by mfunk** [comment]
@joebayles If Spatial Analyst is installed and extension is turned on (ArcMap: Customize >> Extensions) does the problem with Incident Density not showing output raster resolved?

**Comment by mfunk** [comment]
@BobBooth So I modified the Count Incidents by LOC and also ran the tool you sent me. The output match each other, but still don't match the original sample layer. So in this screenshot there are three coincident line features, so visually it will be hard to tell the difference so I labelled on FREQUENCY field where
* Original sample data is in RED.
* Matt's modified tool output is in PURPLE
* Bob's modified tool output is in BLACK

![image](https://cloud.githubusercontent.com/assets/3093182/26003462/994c5b4e-36e7-11e7-827c-5b2176dba7fa.png)

On the road to the far left there is the greatest difference where the original counted 11 incidents and the modifications counted 35. 

This is also showing another hidden bug that we haven't found before. Notice that there are a bunch of floating 78's in the middle but no road? Weird huh? The road does exist there, but our output symbology classification's max break is at 76... effectively excluding anything that is a FREQUENCY of 77 or higher. While you can't see it on this screenshot the actual FREQUENCY maximum is 85. So we are not displaying several roads that have VERY HIGH incident counts.

![image](https://cloud.githubusercontent.com/assets/3093182/26003788/8f9f8674-36e8-11e7-979e-f9db935f76f3.png)




So I think we are back to removing the AOI from Count Incident By LOC.

**Comment by BobBooth** [comment]
@mfunk - Hmm.  Maybe we don't want to specify the output symbology at all, unless there is a way to set a top class of >N.  Never know when the tool is used on someone else's data what the max number of incidents associated with a road will be.

**Comment by BobBooth** [comment]
@mfunk - I tripled the number of incident features and ran both Incidents by LOC and Cluster. The symbology for Cluster adapted to the larger number of features. the symbology for Incidents by LOC did not. Definitely need to change something about the symbology or the way it is applied.

**Comment by Dbarnes1** [comment]
@BobBooth I was just talking to @mfunk and it looks like the way we fix the symbology for Incidents by LOC is by changing the symbology classification in our sample layer file from manual to some other class breaks (preferably natural breaks)

**Comment by mfunk** [comment]
Output symbology classification was set to MANUAL. Should NOT be. Resetting to Natural Breaks works just fine. BUT we are still not matching the original sample data. FEATURE compare (ignoring NULL --> 0) still shows several roads that were different in FREQUENCY.

**Comment by mfunk** [comment]
... more info later. Meeting now.

**Comment by joebayles** [comment]
@mfunk Who's to say the original sample data was right?

**Comment by Dbarnes1** [comment]
I've verified that the various components of this issue have been resolved. Closing out.
