### ISSUE TITLE
Incident Analysis - Hot Spots by Area label, help "Output Workspace" is imprecise, misleading

### ISSUE THREAD

**Issue by BobBooth** [Esri/solutions-geoprocessing-toolbox#502]
The output for Hot Spots by Area is a set of feature classes (one for each AOI feature).
The way a user specifies where they go is to set the "Output Workspace" parameter. I suggest that this output parameter/label be changed to "Output Geodatabase" because if you set it to a folder the tool fails.
A filter could also be set on the parameter to only allow GDBs as input:
![image](https://cloud.githubusercontent.com/assets/3801392/25907041/4f33336c-3574-11e7-928b-df3cebe80dac.png)

Also, the Help for this parameter is:
Output Workspace for resulting analysis layer
(no punctuation)
"Workspace" is imprecise, since it has to be a specific type of workspace (a GDB) and the result is not an "analysis layer" but actually a set of feature classes.
I suggest the help text be changed to:
Output Geodatabase for the result feature classes.

**Comment by mfunk** [comment]
So this is probably something we should be doing for each of the models for each of the inputs. I know we aren't filtering the input feature layers which would help filter what type (Point, Polyline, Polygon, etc.) the user will see when they select a layer that isn't the default.

**Comment by elinz** [comment]
@BobBooth @mfunk Can't we also just set this parameter to %scratchGDB%? Since most if not all of the other tools write output to the scratchGDB, why can't we do that for this tool?

**Comment by BobBooth** [comment]
@elinz - could do that. It is a convenient default, known output location.  
I would argue it isn't best practice to send the result of your tool to scratch because it is meant for intermediate outputs, right?

**Comment by elinz** [comment]
@BobBooth The name would imply that, however, in the Tasks we have the user change the scratch workspace and suggest they use the project file geodatadatabase.

**Comment by Dbarnes1** [comment]
Taking a fresh look at this, for ArcMap, the Hot Spot by Area tool only has geodatabases checked on in the tool properties: 
![image](https://user-images.githubusercontent.com/13024357/28691459-e3ad8458-72d1-11e7-873c-193fb50bb6fc.png)
I don't think the workspace filter exists in the same way in ArcGIS Pro, but in one of the first steps that we narrate for going through the tools we suggest that the users choose a file geodatabase as their scratch workspace: 
![image](https://user-images.githubusercontent.com/13024357/28691561-511713f6-72d2-11e7-97f9-b16d74db2a8f.png)


I think this is good enough to close, @BobBooth and @mfunk let me know if I'm off base by closing.
