### ISSUE TITLE
Incident Analysis - Incident Density - No warning for Spatial Analyst

### ISSUE THREAD

**Issue by joebayles** [Esri/solutions-geoprocessing-toolbox#504]
If you run the Incident Density tool with Spatial Analyst disabled and expect a raster output, there is no warning or error that it will not show up. The question is, do we need to add an error or warning that the Spatial Analyst extension is not enabled?

We already document the Spatial Analyst requirement on the Solutions Pages, and in the tool documentation. Should we also put it in the Known Issues or Release Notes?

FYI @mfunk @Dbarnes1 @BobBooth @elinz @nfeuerstein @lfunkhouser

**Comment by Dbarnes1** [comment]
why not add it in release notes?

**Comment by mfunk** [comment]
Responded in https://github.com/Esri/solutions-geoprocessing-toolbox/pull/503#issuecomment-301487681

**Comment by BobBooth** [comment]
I would mention it in the release notes. 
The Help for the Density output mentions Spatial Analyst is required. The GP results (from the script tool) say:
- Could not create output raster layer; make sure that your Spatial Analyst extension has been checked out.
Would be nice if we could check for the extension in tool validation, but we can't.

**Comment by joebayles** [comment]
Well documented at this point. Closing.
