### ISSUE TITLE
Cluster Analysis Output parameter label says "Feature" singular rather than "Features" (plural)

### ISSUE THREAD

**Issue by BobBooth** [Esri/solutions-geoprocessing-toolbox#505]
The output label for the Cluster Analysis tool is labeled "Output Cluster Feature". Should be "Output Cluster Features" (plural, there will nearly always be multiple output cluster features.
![image](https://cloud.githubusercontent.com/assets/3801392/26066384/a62e6e0e-3964-11e7-8c69-5a6b4d666a65.png)

**Comment by joebayles** [comment]
We recently changed all of our documentation to be "feature" (singular), i.e. http://solutionsdev.arcgis.com/defense/help/incident-analysis/workflows/cluster-analysis.htm

**Comment by Dbarnes1** [comment]
I'm looking at the released version of IA on Pro and Map and it looks like this has been fixed, I'm going to quickly update the topic in our doc to be plural, I'll close this issue. 
![image](https://user-images.githubusercontent.com/13024357/28432969-e327e8b8-6d3e-11e7-8931-2e740c0a8faa.png)
