### ISSUE TITLE
Hot Spot By Area fails if area has no incidents

### ISSUE THREAD

**Issue by ScottCecilio** [Esri/solutions-geoprocessing-toolbox#508]
As reported back in February when the Hot Spot by Area tool is ran again areas where no incidents are present the tool fails.  Using Pro 1.4 and Version May 2017 release of the tools given to me for testing.

![image](https://cloud.githubusercontent.com/assets/6999909/26216392/e3eb989c-3bd1-11e7-8354-40938e543b69.png)

**Comment by joebayles** [comment]
For inclusion in the known issue list.

**Comment by Dbarnes1** [comment]
Adding a select by location at the beginning so the tool only runs hot spot analysis on districts that intersect incident data is how I would approach fixing this, but for now we'll leave it as a known issue

**Comment by BobBooth** [comment]
The tool also fails if there are fewer than 30 incident features within any given one of the polygons:
"...
ERROR 001570: The analysis option you selected requires a minimum of 30 points to be inside the bounding polygon area(s).
..."
Could do a spatial join of the incidents to the boundary polygons, then select from them the ones that have more than 30 incidents, make a new "bounds_with_enough_points" feature class and then run the iterator/hotspot analysis on them.

**Comment by joebayles** [comment]
So, it fails on <30 (0-29) incidents in a polygon?

**Comment by BobBooth** [comment]
@joebayles - yes.  The core Optimized Hot Spot Analysis tool embedded in the model is returning that error message - it needs at least 30 points to do the spatial stats. This value is hard-coded in the script:
minNumFeatures = 30
.
.
.

def checkNumberPolygons(numObs):
    if numObs < minNumFeatures:
        ARCPY.AddIDMessage("ERROR", 1535, str(minNumFeatures))
        raise SystemExit()

**Comment by joebayles** [comment]
OK, I'll update the known issue.

**Comment by topowright** [comment]
I think the best approach to fixing this issue is using the calculate value tool in model builder to only run the analysis if the input points for a given area are more than 29. 
This is what will be put into the tool to check if there are more than 29 points. If so it will produce a true statement and the model will continue if not the model will start back at the beginning for the next area. 
def getCount(featureclass):
    import arcpy
    count = arcpy.GetCount_management(featureclass)
    if count > 29:
        print("true")
        return "true"

    else:
        print("false")
        return "false"


getCount(data)

**Comment by topowright** [comment]
The approach that will allow the tool to not fail with less than 29 points and not add a script tool is using the collect value in model tool. This allows a true or false Boolean to be returned and stops the tool if the amount of selected points is under 29. Here is the function that is being placed in the tool: 

def main(fc):
    import arcpy
    x = int(arcpy.GetCount_management(fc).getOutput(0))
    if x >29:
        return "true"
    else:
        return "false"

**Comment by topowright** [comment]
Now that the updates have been added to the model the areas that are passed up by the tool (less than thirty points) will show this return
![image](https://user-images.githubusercontent.com/5488313/30585173-ce9ccd56-9ce0-11e7-8fac-7ac01f76baff.png)

**Comment by topowright** [comment]
This is what was added to the model: 
![image](https://user-images.githubusercontent.com/5488313/30586142-d68fd000-9ce3-11e7-8c43-b0e6ad2e00d4.png)

**Comment by topowright** [comment]
Now with the updates the tools results populate for areas where there are enough points. This is an example of the area that was skipped in the sample data: 
![image](https://user-images.githubusercontent.com/5488313/30586276-47df3ca0-9ce4-11e7-8b5a-a1bbb60cb041.png)

**Comment by BobBooth** [comment]
@topowright - it might be helpful to the user to translate that message to something they understand, such as "The area with FID # ___ was skipped because it contained fewer than 29 points, the minimum number required for the hot spot analysis."

**Comment by csmoore** [comment]
Seems to work in ArcMap - Tested with Template data and "Last 30 days" layer and Districts 1 & 10 were skipped below and tool ran without error.

I agree with @BobBooth that the current skipped output might confuse but I guess that would be an enhancement (and I believe we have had issues trying to get AddWarning/Error messages from ModelBuilder). Current output on skip:

```
Value = false
...
The process did not execute because the precondition is false.
...
All the inputs are not current. 
```

![image](https://user-images.githubusercontent.com/3090809/30608546-c5056058-9d46-11e7-856d-ef8831c0cacf.png)

**Comment by csmoore** [comment]
Verified. Tested successfully on Pro - sorry for delay - needed to repackage the template to test because updated tools were using "layers" and previous template was using "layerfiles"
