### ISSUE TITLE
Range Fan is not passing bearing limits to Viewshed

### ISSUE THREAD

**Issue by mfunk** [Esri/solutions-geoprocessing-toolbox#51]
Range Fan tool in Visibility and Range passes RADIUS2 and OFFSETA to the target observer for VIEWSHED, but it does NOT pass any other variables. This is a problem with overlapping range fans where the bearing limits of one may not be correctly transferred to the other (see screenshot below). We need to account for (and use the defaults) for the others including RADIUS1 = 0.0, VERT1 = 90.0, VERT2 = -90.0, OFFSETB = 0.0. But for AZIMUTH1 and AZIMUTH2 we need to calculate from the central bearing and traversal.

![image](https://cloud.githubusercontent.com/assets/3093182/3756633/6107d0de-1830-11e4-9f4e-0cd03446f02b.png)

**Comment by mfunk** [comment]
Should be fixed now. @jrweakland please test and close or update. Thanks.

**Comment by jrweakland** [comment]
I added this issue to the current sprint.

**Comment by jrweakland** [comment]
Tested.
