### ISSUE TITLE
Remove mature support toolboxes and document location in Wiki

### ISSUE THREAD

**Issue by mfunk** [Esri/solutions-geoprocessing-toolbox#516]
This is a cleanup issue to remove existing mature support toolboxes and supporting tasks.

## Expected Behavior
Only currently supported toolboxes will remain in the repository.

## Current Behavior
Mature support toolboxes are included in dev/master branches of repository.

## Possible Solution
Remove the following toolboxes and supporting files:
Capability:
- [X] ERG Tools
- [X] Helicopter Landing Zone Tools
- [X] Point Of Origin Tools
Data Management
- [x] CADRG ECRG Tools
- [x] CIB Tools
- [x] Elevation Tools
- [x] Import and Conversion Tools [NOTE: this has moved to Military Tools and is supported in military-tools-geprocessing-toolbox repository]
- [x] Network Data Preparation Tools
- [x] Patrol Data Capture Tools
- [x] Publishable Task Tools
Operational Graphics
- [x] Range Card Tools
Patterns
- [X] Movement Analysis Tools
Suitability
- [x] Maritime Decision Aid Tools
- [x] Path Slope Tools
Visibility
- [x] Visibility and Range
- [x] Visibility Data Prep

Additonally
- [x] Document in Wiki that these tools have been deprecated from the repo and are available from June 2017 Release: https://github.com/Esri/solutions-geoprocessing-toolbox/releases/tag/JUNE2017

## Steps to Reproduce (for bugs)
N/A

## Context
N/A

## Your Environment
* Version used: ArcGIS Desktop 10.3.1 and ArcGIS Pro 1.4
* Environment name and version (e.g. Chrome 39, node.js 5.4): N/A
* Operating System and version (desktop or mobile): Windows 10
* Link to your project:

**Comment by csmoore** [comment]
Are these toolboxes used by a template and/or should these be included in the list for mature support?

Movement Analysis
Maritime Decision Aid

Also, would it be possible to remove all of the mature support in this pass or are you waiting for a release cycle after you  announce to remove (ex. Visibility and Range,  Visibility Data Prep Tools, etc.)

**Comment by mfunk** [comment]
Neither of those toolboxes is included in a template, however I did suggest at some point that Movement Analysis could be included in Incident Analysis. 

In my opinion we should wait a release to have the marking for Mature Support before we remove it. But somehow I think the current thinking would be to have them removed immediately and if needed get it from a previous release. What do you prefer?

**Comment by csmoore** [comment]
IMHO it would be nice to remove all the mature support ones now to start with a fresh slate (with both the toolboxes and test drivers).

**Comment by csmoore** [comment]
@mfunk - here is the final list of toolboxes (not mentioned above in original issue), that I couldn't find an obvious template for:

Adjust Sample Data Dates Tools
ERG Tools
Helicopter Landing Zone
LiDAR elevation
Maritime Decision Aid
Movement Analysis

Can you let us know which of these can also be moved to Mature Support? 

For instance, some of these may not be directly used in a template, but may be used to publish a required service for a Web App Builder widget, so should these stay?

**Comment by mfunk** [comment]
@lfunkhouser @nfeuerstein PLEASE REVIEW THIS LIST AND COMMENT:

- **Adjust Sample Data Dates Tools** - This goes with Incident Analysis and will be moved into the Incident Analysis tools folder with the reorgainzation.
- _ERG Tools_ - Mature Support - Which I guess means we delete it entirely.
- _Helicopter Landing Zone_ - Should probably go in with MAoT, but no plans so Mature and delete?
- _LiDAR elevation_ - Mature Support
- _Maritime Decision Aid_ - Mature Support
- _Movement Analysis_ - Mature Support

**Comment by csmoore** [comment]
The toolbox wiki was added here (and the task marked complete above):

https://github.com/Esri/solutions-geoprocessing-toolbox/wiki/Template-Toolboxes  

It made the assumption that if a toolbox didn't have a template, it was retired, but if that is not the case, feel free to edit the wiki.

**Comment by mfunk** [comment]
@csmoore
- We don't have a Compound Map Tools toolbox in the repo. Isn't that one under Clearing Operations Tools?
- Incident Analysis includes Adjust Sample Data Dates Tools.
- All of these should have a Pro and an ArcMap toolbox, though not necessarily an ArcMap and Pro Template.
