### ISSUE TITLE
 Add Compound Map Tools toolbox to repo

### ISSUE THREAD

**Issue by csmoore** [Esri/solutions-geoprocessing-toolbox#519]
## Expected Behavior

The Compound Map template contains a toolbox: `Compound Map Tools.tbx` - this template's toolbox should be added to this repo

**Comment by adgiles** [comment]
The compound map toolbox only has one tool in it which is the number features tool which is already in the repo: https://github.com/Esri/solutions-geoprocessing-toolbox/tree/dev/operational_graphics/toolboxes/scripts

**Comment by csmoore** [comment]
@adgiles - you may have left the meeting before we discussed this (and not sure if we have found the shared meeting minutes location yet) but I believed we agreed to add/include this extra toolbox - even though this one tool is a repeat of Incident Analysis Tools

**Comment by csmoore** [comment]
This is done ( in #538)
