### ISSUE TITLE
Incident Analysis - Incident Hot Spots returns with an error when run on incidents definition query

### ISSUE THREAD

**Issue by Dbarnes1** [Esri/solutions-geoprocessing-toolbox#521]
## Expected Behavior
I would expect the Incident Hot Spots tool to honor definition queries in our data, so long as the definition query meets the minimum required point features for Optimized Hot Spot Analysis to run.

## Current Behavior
When running the tool on Incidents/MonthBeforeLast, I get an error message, as opposed to when I run it on the AllIncidents layer. Below is a picture of the error message I received. 
![image](https://user-images.githubusercontent.com/13024357/28628505-ae0ed34a-71d9-11e7-81cd-f568991379d9.png)

When I run the out of the box Optimized Hot Spot Analysis tool, I received the same error:
![image](https://user-images.githubusercontent.com/13024357/28628670-230c0f50-71da-11e7-9ee6-f8b99d888dfc.png)

## Possible Solution
It looks like the error is saying that we need to have an OID field in all of the layers that we run the tool against. It looks like we have that in the All Incidents Layer, but not any of the definition query layers. Anyone know why the OID field drops once you set a definition query on these layers? Pictures below for reference.
All Incidents:
![image](https://user-images.githubusercontent.com/13024357/28628769-6c5fb968-71da-11e7-9fd3-a84d856ca24f.png)

MonthBeforeLast:
![image](https://user-images.githubusercontent.com/13024357/28629642-dd3c8254-71dc-11e7-8b61-63066245ab76.png)

## Steps to Reproduce
1. Open up IncidentAnalysis.aptx
2. Update the sample date/time fields so that the definition query layers are populated with data
3. Run Incident Hot Spots on an Incidents definition query layer (last 30 days or month before last usually meet minimum feature count requirements). Tool should fail pretty quick

## Your Environment
Incident Analysis July 2017 on Pro 1.4 (also pretty sure that this bug can be replicated in ArcMap

This issue is related to https://github.com/Esri/solutions-geoprocessing-toolbox/issues/483 as they both rely on the OHSA tool

**Comment by Dbarnes1** [comment]
For clarification, this issue is specific to ArcGIS Pro

**Comment by Dbarnes1** [comment]
We can do two things to fix this specific issue. This bug was logged with core and is now fixed in 2.1. 
So we can add a known issue for Pro 1.4 and 2.0
OR 
We can implement the easy workaround, which is to make the OID and shape fields visible in our definition query tables. 

Neither of these fixes solves issue #483, So I think we should chalk it up as a known issue that will be fixed in 2.1. @BobBooth thoughts?

**Comment by BobBooth** [comment]
@Dbarnes1 & @mfunk - possible solution suggested here:
https://github.com/Esri/solutions-geoprocessing-toolbox/issues/483

**Comment by Dbarnes1** [comment]
@BobBooth ready to verify using the incidentanalysis_test.aptx on the release staging file share

**Comment by mfunk** [comment]
@Dbarnes1 @BobBooth Did we fix this one already? If so can we close it out?

**Comment by BobBooth** [comment]
@mfunk - this should also be fixed by adding that copy features step before projecting.

**Comment by Dbarnes1** [comment]
This has already been fixed, this just needs to be verified

**Comment by mfunk** [comment]
Verify is usually done by person who logged it, but in this case I can check it out.

**Comment by mfunk** [comment]
manually tested and it's working for me....

> Start Time: Tuesday, August 1, 2017 11:11:51 AM
> Executing (Optimized Hot Spot Analysis): OptimizedHotSpotAnalysis "Incidents\Month Before Last" C:\Users\<user>\Documents\ArcGIS\Projects\TestSGT521again\results.gdb\IncidentHotSpots0001 # "Count incidents within fishnet grid" Districts # # # #
> Start Time: Tuesday, August 1, 2017 11:11:53 AM
> Running script OptimizedHotSpotAnalysis...
>  WARNING 001605: Distances for Geographic Coordinates (degrees, minutes, seconds) are analyzed using Chordal Distances in meters.
> ************************** Initial Data Assessment ***************************
> Making sure there are enough incidents for analysis....
> - There are 512 valid input features.
> Looking for locational outliers....
> - There were 6 outlier locations; these will not be used to compute the polygon cell size.
> Evaluating the bounding polygon feature class....
> - The total study area is 78300941.6387 Meters.
> **************************** Incident Aggregation ****************************
> Creating fishnet polygon mesh to use for aggregating incidents....
> - Using a polygon cell size of 253.0000 Meters
> Counting the number of incidents in each polygon cell....
> - Analysis is performed on all polygon cells within the bounding polygon feature class.
> Evaluating incident counts and number of polygons....
> - The aggregation process resulted in 2124 weighted polygons.
> - Incident Count Properties:
>         Min:       0.0000
>         Max:       7.0000
>         Mean:      0.2411
>         Std. Dev.: 0.6850
> ***************************** Scale of Analysis ******************************
> Looking for an optimal scale of analysis by assessing the intensity of clustering at increasing distances....
> - No optimal distance was found using this method.
> Determining an optimal distance using the spatial distribution of features....
> - The optimal fixed distance band is based on the average distance to 30 nearest neighbors: 693.0000 Meters
> ***************************** Hot Spot Analysis ******************************
> Finding statistically significant clusters of high and low incident counts....
> - There are 382 output features statistically significant based on an FDR correction for multiple testing and spatial dependence.
> - % of features had less than 8 neighbors based on the distance band of 693.0000 Meters
> *********************************** Output ***********************************
> Creating output feature class: C:\Users\<user>\Documents\ArcGIS\Projects\TestSGT521again\results.gdb\IncidentHotSpots0001
> - Red output features represent hot spots where high incident counts cluster.
> - Blue output features represent cold spots where low incident counts cluster.
> Completed script OptimizedHotSpotAnalysis...
> Succeeded at Tuesday, August 1, 2017 11:12:24 AM (Elapsed Time: 31.22 seconds)
> Succeeded at Tuesday, August 1, 2017 11:12:24 AM (Elapsed Time: 32.84 seconds)

**Comment by Dbarnes1** [comment]
@mfunk procedural question. If I log the issue and then fix it, am I also responsible to verify it without having anyone else look at it?
