### ISSUE TITLE
Number Features missing parameter doc for Output Feature Class

### ISSUE THREAD

**Issue by mfunk** [Esri/solutions-geoprocessing-toolbox#523]
Missing doc for *Output Feature Class* parameter in **Number Features** tool.
This is for both Pro and ArcMap.

## Expected Behavior
Should have something saying something like "Type a name or browse to a path for the output point features."

## Current Behavior
Right now... nothing:
![image](https://user-images.githubusercontent.com/3093182/28634205-4fbaf51e-71eb-11e7-96c1-9d346f4bfca8.png)

## Possible Solution
Write the doc.

## Steps to Reproduce (for bugs)
1. Open Number Features dialog in Pro or ArcMap
2. Open tool help or hover over help (?)
3. either blank (Pro) or "No description available" (ArcMap)
4.

## Your Environment
* Version used: 10.3.1, 1.4
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by adgiles** [comment]
Fixed in PR#541

![523](https://user-images.githubusercontent.com/3740334/28870295-9e7d076e-7777-11e7-9fc1-8acf9ca4af90.png)

**Comment by adgiles** [comment]
Fixed, Closing
