### ISSUE TITLE
Canvas Area GRG tool has parameter named "CanvasAreaGRGScript"

### ISSUE THREAD

**Issue by mfunk** [Esri/solutions-geoprocessing-toolbox#524]
In Pro and ArcMap the **Canvas Area GRG** tool has a parameter named *CanvasAreaGRGScript*. I'm guesing this is probably the "Output GRG Features" parameter.

## Expected Behavior
Parameter names/labels should identify direction and be descriptive. Think this was just an oversight, but needs to be fixed.

## Current Behavior
![image](https://user-images.githubusercontent.com/3093182/28634778-232fd5f8-71ed-11e7-958e-bb44bc3357cb.png)

## Possible Solution
Needs to be fixed in Pro and ArcMap

**Comment by adgiles** [comment]
Fixed in PR #541 

![524](https://user-images.githubusercontent.com/3740334/28870245-7225cd5e-7777-11e7-9fd6-c91bb4e0eef2.png)

**Comment by adgiles** [comment]
Fixed, Closing
