### ISSUE TITLE
ClearingOperations.tbx needs unit tests written.

### ISSUE THREAD

**Issue by ACueva** [Esri/solutions-geoprocessing-toolbox#530]
ClearingOperations.tbx currently has no unit tests written.

### Minimum Requirements:
Confidence that after unit tests are run that the toolbox works as expected.
Tests Will need to be written to both run against ArcMap and ArcGIS Pro.

### Max Requirements:
Ask yourself, "Am I writing tests for the sake of writing tests?".  If they provided little to no value, please don't write one.

### Main Focus:
Focus tests on workflows customers would use.  If additional instructions on workflows are needed please refer to the solutions pages:
http://solutions.arcgis.com/defense/help/clearing-operations/

## Tests needed:

- [x] CanvasAreaGRG
- [x] NumberFeatures
- [x] PointTargetGRG

**Comment by ACueva** [comment]
Note: issue depends on / related to #531 (add toolbox to repo)

**Comment by mfunk** [comment]
Number Features tool also exists in *Compound Map Tools* toolbox as a separate tool. See if the test can be shared between toolboxes:
https://github.com/Esri/solutions-geoprocessing-toolbox/issues/539

**Comment by topowright** [comment]
This has been completed.
