### ISSUE TITLE
Add Clearing Operations Tools toolbox to repo

### ISSUE THREAD

**Issue by ACueva** [Esri/solutions-geoprocessing-toolbox#531]
## Expected Behavior

The Clearing Operations Map template contains a toolbox: `Clearing Operations Tools.tbx` - this template's toolbox should be added to this repo

**Comment by csmoore** [comment]
Similar to https://github.com/Esri/solutions-geoprocessing-toolbox/issues/533#issuecomment-318637248

This may just be an issue with exact naming in template vs. repo - https://github.com/Esri/solutions-geoprocessing-toolbox/tree/dev/clearing_operations

**Comment by mfunk** [comment]
The the toolboxes already exist in the repo. Closing.
