### ISSUE TITLE
Geonames.tbx needs unit tests written.

### ISSUE THREAD

**Issue by ACueva** [Esri/solutions-geoprocessing-toolbox#532]
Geonames Tools.tbx currently has no unit tests written.

### Minimum Requirements:
Confidence that after unit tests are run that the toolbox works as expected.
Tests will need to be written to both run against ArcMap and ArcGIS Pro.

### Max Requirements:
Ask yourself, "Am I writing tests for the sake of writing tests?".  If they provided little to no value, please don't write one.

### Main Focus:
Focus tests on workflows customers would use.  If additional instructions on workflows are needed please refer to the solutions pages:
http://solutions.arcgis.com/defense/help/geonames-locator/

## Tests needed:

- [x] Create Geonames Gazetteer Locator
- [x] Load Geonames Files

**Comment by ACueva** [comment]
Note: issue depends on / related to #533 (add toolbox to repo)

**Comment by csmoore** [comment]
@ACueva - ready to verify at: https://github.com/Esri/solutions-geoprocessing-toolbox/tree/dev/utils/test/geonames_tests

**Comment by ACueva** [comment]
Verified Geonames is running.  There are errors in the test suite not related to Geonames.  Will speak with @mfunk and log issues as needed.
