### ISSUE TITLE
Add Geonames Tools toolbox to repo

### ISSUE THREAD

**Issue by ACueva** [Esri/solutions-geoprocessing-toolbox#533]
## Expected Behavior

The Geonames template contains a toolbox: `Geonames Tools.tbx` - this template's toolbox should be added to this repo.

**Comment by csmoore** [comment]
This toolbox is in the repo: https://github.com/Esri/solutions-geoprocessing-toolbox/tree/dev/geonames - though the name does not *exactly* match what's in the template - should the name be changed in the template/doc?

**Comment by mfunk** [comment]
We've discussed this in meetings that the toolbox MAY be renamed when 'added' to the output template, be it Pro or Desktop, or it may stay the same (with _arcmap or _pro). Either way the toolbox already exists in the repo so we should be good to go. Closing.
