### ISSUE TITLE
Distance to Assets - Geocode Assets and Bases tool doesn't have Esri World Geocoder as an input parameter

### ISSUE THREAD

**Issue by Dbarnes1** [Esri/solutions-geoprocessing-toolbox#537]
## Expected Behavior
When using tasks in the ArcGIS Pro version of Distance to Assets, the first task runs through the **1. Geocode Assets and Bases** tool. I'd expect the input geocoding service in the tool to default to the Esri World Geocoder.

## Current Behavior
The current default geocoder is https://geocode.arcgis.com/arcgis/rest/services/World\GeocodeServer. I'm not sure if it is the same as the Esri World Geocoder, but this seems like a remnant of how you needed to enter the specific url to connect to the geocoder in ArcMap.
![image](https://user-images.githubusercontent.com/13024357/28838887-a1c897d4-76a6-11e7-89e2-a86e37587d53.png)

## Possible Solution
The quick workaround is to document to the user that they need to replace the default geocoder with the Esri World Geocoder, but a more elegant enhancement would be to remove the parameter that includes the file path in the pro version of the template. 

## Steps to Reproduce (for bugs)

1. Open Distance to Assets In ArcGIS Pro
2. Run the Task Item entitled Create Distance to Assets
3. The first task is 1. Geocode Assets and Bases, which is where you'll encounter the filepath as the geocoder.

## Your Environment
Pro 2.0

**Comment by adgiles** [comment]
@dbarnes1 why do you think this incorrect? This is the online geocoder and functions as required

**Comment by Dbarnes1** [comment]
@adgiles it looks like there are two options when you click on the drop down in that parameter. Those options are Esri World Geocoder and MGRS Geocoder. I guess my question is whether the Esri World Geocoder in the drop down is the same as this path: https://geocode.arcgis.com/arcgis/rest/services/World\GeocodeServer. If it is, why do we need to have that path set in the tool? 

This is related to the fact that I'm unable to actually run the tool in Pro: https://github.com/ArcGIS/solutions-desktop-templates/issues/400

**Comment by adgiles** [comment]
@dbarnes1 they are the same but you will only get the drop down if the locators are set as ready to use services within your portal

**Comment by Dbarnes1** [comment]
@adgiles thanks for clarifying! Just wanted to make sure everything makes sense as I go through the documentation for the template. I'll go ahead and close this
