### ISSUE TITLE
Geonames Tools_pro.tbx/LoadGeonamesFile corrupt/not running in Pro

### ISSUE THREAD

**Issue by csmoore** [Esri/solutions-geoprocessing-toolbox#547]
Something about the conversion process when converting the model from ArcMap to ArcPro is corrupting the Model `Geonames Tools_pro.tbx/LoadGeonamesFile`

The ArcMap model works fine unmodified in Pro but something about saving the model/toolbox in Pro is corrupting the model. Suggest we just use the ArcMap version in the repo and for the Pro template.

Problems noticed (after saving and running in Pro):

`1.` You can't run the model because it won't let you set the feature class parameter

![image](https://user-images.githubusercontent.com/3090809/28896183-66a66d08-77a9-11e7-9303-e1d7cf595d0b.png)

`2.` You can no longer open parts of the model:

![image](https://user-images.githubusercontent.com/3090809/28896041-daefe2c6-77a8-11e7-9f24-4f0e3e44da31.png)

`3.` MakeFeatureLayer step of the model does not show the expression when opened
![image](https://user-images.githubusercontent.com/3090809/28896108-27b9a81c-77a9-11e7-8401-e69e02de9149.png)

`4.` When run from the command line [in test driver](https://github.com/Esri/solutions-geoprocessing-toolbox/blob/dev/utils/test/geonames_tests/GeoNamesTestCase.py) - you get a bit more info - again this appears to be an issue with the MakeFeatureLayer step (Note: same **"ERROR 000816"** as above):

```
test_load_geonames (geonames_tests.GeoNamesTestCase.GeoNamesTestCase)Traceback (most recent call last):
  File "C:\DefenseTemplates\Github\solutions-geoprocessing-toolbox\utils\test\geonames_tests\GeoNamesTestCase.py", line 88, in test_load_geonames
    countryCodes, adminCodes, featureCodes)
  File "C:\DefenseTemplates\Github\solutions-geoprocessing-toolbox\geonames\Geonames Tools_pro.tbx", line 86, in LoadGeonamesFile
     ' F u l l   A d d r e s s '   & l t ; N o n e & g t ;   V I S I B L E   N O N E 
  File "C:\DefenseTemplates\Github\solutions-geoprocessing-toolbox\geonames\Geonames Tools_pro.tbx", line 83, in LoadGeonamesFile
     C o u n t r y   C O U N T R Y N A M E 1   V I S I B L E   N O N E 
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 506, in <lambda>
    return lambda *args: val(*gp_fixargs(args, True))
arcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.
ERROR 000816: The tool is not valid.
```

**Comment by Dbarnes1** [comment]
@csmoore did you try and run it from the .aptx file that @adgiles put on the staging server a couple of hours ago?

**Comment by Dbarnes1** [comment]
I realize that this doesn't fix the issue of putting the stand-alone toolbox in the repository, just wanted to make you aware of the .aptx file

**Comment by csmoore** [comment]
@Dbarnes1 Thanks for tip - that version does work and also is about half the size of the corrupted one (285KB vs 470KB). 

I would be curious to know how the corrupted one vs. good ones got created just so we could avoid this happening in future.

Note: the toolbox/deployment is slightly different (no "scripts" folder) - something to do with how Pro packages - But I'll adjust this and make a PR with good _pro.tbx:

![image](https://user-images.githubusercontent.com/3090809/28923611-9eab1fc2-782c-11e7-91ed-201a9d46b859.png)

![image](https://user-images.githubusercontent.com/3090809/28923636-b317befc-782c-11e7-8c56-2e5929fdd9b3.png)

**Comment by adgiles** [comment]
The good toolbox is just the arcmap tool boxed renamed using arccatalog (not explorer as this breaks the model) added into pro

**Comment by csmoore** [comment]
@adgiles - thanks for explaining - perhaps another argument for keeping/maintaining the models in ArcMap - though for this model the python actually looks simpler than the model, so perhaps an argument for just using python or converting to when we get a chance:  [LoadGeoNames.py.txt](https://github.com/Esri/solutions-geoprocessing-toolbox/files/1197447/LoadGeoNames.py.txt) - it would hopefully simplify tracking down bedeviling errors like above

**Comment by mfunk** [comment]
Checked and merged.
