### ISSUE TITLE
Clearing Operations ArcMap template coordinate system and incorrect size

### ISSUE THREAD

**Issue by llsjr2** [Esri/solutions-geoprocessing-toolbox#548]
## Expected Behavior
Open the template and the coordinate in the bottom be a coordinate that an individual would recongize (UTM, MGRS, Geo Lat/Long)
When the Canvas GRG Tool is run with the default 100 meters.  It should be 100 x 100 meters.

## Current Behavior
The coordinate on the bottom is an unrecognizable coordinate.  (( This coordinate is utilized by Soldiers as the reference for where to draw there boxes based on the Request For Information Sheet
Suggest it is saved in UTM or MGRS.

The Canvas GRG Tool produces GRG boxes that are 80 meters, not 100 meters.

Context
Coordinate is a useful reference for the end user to know where the boxes need to be drawn.
Inaccurate GRG size degrades the creditably and usability of the product.  
![issue 1](https://user-images.githubusercontent.com/30242778/28898154-3883afe0-7799-11e7-887f-2dc4d01c1624.JPG)
![issue 2](https://user-images.githubusercontent.com/30242778/28898155-3885b592-7799-11e7-9cc2-846d3e59d889.JPG)

**Comment by adgiles** [comment]
Larry,

The first issue of the map frame not having any display coordinates is an easy fix. I have set this to MGRS and saved a new version of the mxd in the staging folder.

The second issue of the grids not being the correct size, I cannot replicate, tested in both map & pro:

![grid_arcmap](https://user-images.githubusercontent.com/3740334/28913074-a4d16710-782e-11e7-9dcd-115b2ac7daab.png)

![grid_pro](https://user-images.githubusercontent.com/3740334/28913081-a8170416-782e-11e7-8a2a-6f9db3e3d2b7.png)

The grid is created using the [Create Fishnet Tool](http://desktop.arcgis.com/en/arcmap/latest/tools/data-management-toolbox/create-fishnet.htm) which is core functionality so even if we can replicate I am not sure how we would fix it

**Comment by topowright** [comment]
@llsjr2 Can we look at this again today? I am not seeing this same behavior.

**Comment by llsjr2** [comment]
@topowright I checked it.  It was fixed by @adgiles. I am closing the issue.
