### ISSUE TITLE
Pro Incident Analysis Tools point to different layer/symbology folder

### ISSUE THREAD

**Issue by csmoore** [Esri/solutions-geoprocessing-toolbox#559]
The Incident Analysis tools/template point to symbology (Layer files (lyrx) ) in the `"layerfiles"` folder but in this repo these files are store in the ["layers" folder](https://github.com/Esri/solutions-geoprocessing-toolbox/tree/dev/incident_analysis/layers)

## Current Behavior

In Pro, Symbology is not applied and model does not run from test script using the [Incident Analysis tools](https://github.com/Esri/solutions-geoprocessing-toolbox/tree/dev/incident_analysis/) from this repo because the tools reference the `layerfiles` folder vs. the  `layers` folder

## Possible Solution

Point symbology output to `layers` folder

## Steps to Reproduce (for bugs)

1. Look at the properties for the output parameters for one of the IA tools (ex. Cluster Analysis)
2. Observe the symbology point to `layerfiles` folder (which does not exist in this repo)

![image](https://user-images.githubusercontent.com/3090809/29031872-95753f12-7b5d-11e7-90a4-11e72264a39e.png)

Note: this also causes the unit/scripted tests to fail to run with 
```
ERROR: 2017-08-07 09:04:23,874 arcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.
ERROR: 2017-08-07 09:04:23,874 The value does not exist.
ERROR: 2017-08-07 09:04:23,875 ERROR 000732: Symbology Layer: Dataset C:\...\solutions-geoprocessing-toolbox\incident_analysis\layerfiles\IncidentDensitySurface.lyrx does not exist or is not supported
```

## Your Environment

* Version used:
* Pro 2.0 / Win 10

**Comment by mfunk** [comment]
I thought this was just the output symbology in the model parameters, but unfortunately it's hardcoded into the model itself:

![image](https://user-images.githubusercontent.com/3093182/29046158-12ddb1ba-7b7b-11e7-99b9-4a1db94a9190.png)

**Comment by csmoore** [comment]
I'm confused - I thought @topowright removed that portion of the model and set the symbology on the tool's property page ( [shown above](https://user-images.githubusercontent.com/3090809/29031872-95753f12-7b5d-11e7-90a4-11e72264a39e.png) ). Is there any reason to keep that part of the model if setting symbology elsewhere?

If we don't want to affect the working template - can we just rename the folder in this repo `layerfiles` to match the template?

**Comment by mfunk** [comment]
@topowright was working on Clearing Ops at the time. Best case *symbology* should be handled by the model parameters (not the Apply Symbology ... which presents us with path issues again), however a bug in Pro does not show the Labels set in the .LYRX files.

**Comment by mfunk** [comment]
Reviewing this what happened is that the toolbox was packaged in Pro for release with a bad folder name "layerfiles". The packaging of the project modified the paths in the model, the model was then merged into the repo, again with the modified paths, and now has bad paths in the model.

**Comment by mfunk** [comment]
Unfortunately **Cluster Analysis** is one of those tools that doesn't like it's .LYRX file. It doesn't render the point symbols properly with it's LYRX file when referenced in the script tool properties. It does seem to pick it up (again, not labeling, just symbols) with **Apply Symbology**. But because the path to the .LYRX is template specific, it leaves it untestable in the repo.

**Comment by csmoore** [comment]
@mfunk so this is a "wontfix"/"known issue" and we should just skip the tests for the 2 tools/tests affected (ClusterAnalysis, IncidentDensity) ? 

Ex:
`@unittest.skipIf(Configuration.Platform == Configuration.PLATFORM_PRO, "Pro Unit Test not currently working")`  

I can adjust PR #563 if that is the case

**Comment by mfunk** [comment]
There are a few other issues with the tools as-is (feature filters, Incident Density has same LYRX issue,... etc.) but I think that if the correct folder name *layer* was used to package the template instead of *layerfile* it would work. Still testing stuff out though.

**Comment by mfunk** [comment]
This is going nowhere. Can't package it up as a template. Dead in the water.

![image](https://user-images.githubusercontent.com/3093182/29090717-4cf6a54a-7c35-11e7-8f7f-c25fe94872cc.png)

**Comment by csmoore** [comment]
There were some packaging issues with this template ( that I believe @BobBooth & @Dbarnes1 eventually worked out ) so perhaps just pick your preferred workaround for now:

1. have both folders "layers" and "layerfiles" in this repo (seemed to work for me)
2. skip the affected tests

**Comment by mfunk** [comment]
Got it to work by making sure the target folder included in the packaging was named "layers". Had to reset paths before packaging but it seems to be working now on both the unpackaged template and the repo tests.
