### ISSUE TITLE
ArcMap HotSpotsByArea ignores output workspace parameter

### ISSUE THREAD

**Issue by csmoore** [Esri/solutions-geoprocessing-toolbox#560]
Incident Analysis HotSpotsByArea ignores the output workspace parameter in ArcMap 

## Expected Behavior

Output data to be created in workspace set in output workspace parameter 

## Current Behavior

Output data is created in default environment workspace

## Steps to Reproduce (for bugs)

1. In ArcMap, run Incident Analysis HotSpotsByArea 
2. Set the output workspace parameter
3. Observe that the output is not created in this workspace

![image](https://user-images.githubusercontent.com/3090809/29033474-349c4810-7b63-11e7-80ca-ae4fffb29691.png)

## Your Environment

* ArcMap 10.4.1 Win 10

**Comment by kgonzago** [comment]
Executed tool twice it results wrote to user specified workspace. Issue could not be reproduced.

**Comment by topowright** [comment]
@kgonzago I am able to reproduce this issue with the latest from dev.

**Comment by topowright** [comment]
Also, I am finding that the tool will only write out one result, which I am not sure if this is because of this. I have experienced this in ArcMap.

**Comment by topowright** [comment]
I am seeing some crazy behavior with what it is writing. It will take me some time to capture it. This is a placeholder until I can get capture what is happening.

**Comment by topowright** [comment]
I was able to fix the issue with multiple layers not adding to the map. That was done in pull request #602 . It was an issue with how long the names were possibly. I fixed it by just taking away the words "selectvalue" in the output name.

**Comment by BobBooth** [comment]
@topowright - the "only one output" issue is also noted here:
https://github.com/ArcGIS/solutions-defense/issues/423
It is something that cropped up before and was supposed to have been fixed:
https://github.com/Esri/solutions-geoprocessing-toolbox/issues/497

At the time, the problem was that it was iterating the areas correctly, but then writing all of the outputs to the same path string, overwriting each one in turn.

**Comment by topowright** [comment]
@BobBooth I have addressed the naming issues in PR #602. I am going to verify this issue. now.

**Comment by ACueva** [comment]
Verified we are now able to save the output to location specified when running the GP tool.
![2017-09-19_14-11-04](https://user-images.githubusercontent.com/3093940/30615658-6d1e430c-9d44-11e7-94bb-89cc871f176d.png)

**Comment by ACueva** [comment]
Verified a second time with @topowright present to confirm results.
