### ISSUE TITLE
ClearingOperationsTools.tbx has no tool help

### ISSUE THREAD

**Issue by dfoll** [Esri/solutions-geoprocessing-toolbox#574]
There are three tools in this toolbox. None of the tools have any tool help for them. They should have tool help. I have inserted a single screenshot from one parameter on the number features tool, but all parameters on all three tools are missing tool help. Included a second screenshot to show that this is also an issue in Pro

![image](https://user-images.githubusercontent.com/5322669/29578760-46469ae8-8725-11e7-8aa0-f55e9810ced6.png)

![image](https://user-images.githubusercontent.com/5322669/29578848-9576322c-8725-11e7-9994-d98d2a34fee7.png)

**Comment by dfoll** [comment]
@lfunkhouser @nfeuerstein

**Comment by dfoll** [comment]
a good guideline on properly fleshing out good releasable tools can be found here
https://github.com/ArcGIS/Solutions-Resources/blob/master/Python/Style/SolutionsGuideToCreatingGeoprocessingTools.md#testing-geoprocessing-tools

a topic specifically addressing tool help is found with in this document
https://github.com/ArcGIS/Solutions-Resources/blob/master/Python/Style/SolutionsGuideToCreatingGeoprocessingTools.md#tool-documentation

**Comment by dfoll** [comment]
follow up to this... the tools that are currently in the repo do have tool help, but somewhere along the line with moving tools around and combining them, the ones used in the packaging of the solutions for both ClearingOperations.mxd and CompoundMap.mxd do not

**Comment by topowright** [comment]
This has been fixed by the following pull request: https://github.com/Esri/solutions-geoprocessing-toolbox/pull/577#pullrequestreview-58499213

Please verify @dfoll. I have also verified this will review of the pull request, but I think you might want to see the changes as well.

**Comment by mfunk** [comment]
Fixed.
