### ISSUE TITLE
Point Target GRG parameter name  is misleading

### ISSUE THREAD

**Issue by dfoll** [Esri/solutions-geoprocessing-toolbox#575]
Point Target GRG "Grid Size (optional)" parameter name can be misleading. What that parameter actually does is control the size of the Grid Cell. Recommend changing the name of the parameter to "Grid Cell Size (optional)"

**Comment by dfoll** [comment]
@lfunkhouser @nfeuerstein

**Comment by topowright** [comment]
@dfoll I need some more context on this issue. I will reach out to you to make sure my thoughts are the same as yours.

**Comment by topowright** [comment]
@dfoll I feel that after our discussion today we both understand that the polygon feature set input for this tool now makes sense. It should be the size set for each grid. I think it has been verified and we can close this.
