### ISSUE TITLE
Update GRG tools

### ISSUE THREAD

**Issue by Dbarnes1** [Esri/solutions-geoprocessing-toolbox#579]
As part of the GRG project, we need to have a GRG option for desktop. In order to get started with that, we should assess the current functionality of the existing GRG tools in this repository. From this, we can open up new issues related to bugs we find or enhancements that will make these tools similar to the functionality we're building in the GRG widget.

- [x] holistic test canvas area GRG tool
- [x] holistic test point area GRG tool
- [x] open up issues and enhancements related to creating GRG from MGRS
- [x] document GP tools as part of GRG solution
- [x] review the documentation
- [x] update unit tests for new tool names
- [x] update checklist test for GRG with GP tool functionality

Do we also need to look at the number features tool?
It would also be useful to discuss with team members who recently did maintenance work on Clearing Operations, as that is where these tools currently live.

**Comment by mfunk** [comment]
Per meeting yesterday:

- Renaming Clearing Operations Tools to more generic. Suggested GRG Tools. #582 
- Rename GRG tools to match GRG widget:
   - Canvas Area GRG --> Create GRG from Area
   - Point Target GRG --> Create GRG from Point
- New tool for creating reference grids (MGRS/USNG). #581 
- Need to document geoprocessing tools as part of GRG solution.
   - Use existing Clearing Operations requirements for GP: http://solutionsdev.arcgis.com/defense/help/clearing-operations/
   - Use existing Clearing Operations workflows as start for GRG workflows:
      - Canvas Area GRG (Create GRG by Area): http://solutionsdev.arcgis.com/defense/help/clearing-operations/workflows/creating-a-canvas-grg-tool.htm
      - Point Target GRG (Create GRG by Point): http://solutionsdev.arcgis.com/defense/help/clearing-operations/workflows/creating-a-point-target-grg.htm
   - Use existing Resources >> References: http://solutionsdev.arcgis.com/defense/help/clearing-operations/resources/references.htm
- Would still like opportunity to refactor existing tools.
- Update unit tests in GP framework for toolbox and tool name changes
- Update sanity/checklist tests for GRG solution to include geoprocessing tools.

**Comment by Dbarnes1** [comment]
@mfunk I updated the checklist for this issue based on your list. I also added issue #582 to our current sprint.

**Comment by mfunk** [comment]
Clearing Operations and GRG tools are updated for #582, including unit test names.

**Comment by mfunk** [comment]
@elinz I've seen a good portion of the GP tool doc in XMetaL. Would you say the writing of the doc is completed?

**Comment by mfunk** [comment]
@lfunkhouser  @joebayles 
Added new checklist test for GRG tools, separate from Widget tests. Done under PR #20: https://github.com/ArcGIS/solutions-defense-test-catalog/pull/20

**Comment by mfunk** [comment]
@elinz @joebayles @Dbarnes1 
So there is workflow topics on solutionsdev for the GRG gp tools. I'm going to check *document GP tools as part of GRG solution*.
I'm guessing the remaining *review the documentation* will put this in Verify until Tech Review is complete?

**Comment by Dbarnes1** [comment]
@mfunk that sounds like a good plan

**Comment by elinz** [comment]
@Dbarnes1 I updated the gp tool xmetal doc topics for pro grg point tool, pro grg area tool, arcmap point tool, and arcmap area tool; checked them in and republished web help and pdf help.

**Comment by Dbarnes1** [comment]
documentation reviewed and updates made for all workflow topics. Moving the topic status to "to be reviewed" @joebayles fyi. closing and moving this to done
