### ISSUE TITLE
Help missing for Number Features - Field To Number parameter (ArcMap only)

### ISSUE THREAD

**Issue by mfunk** [Esri/solutions-geoprocessing-toolbox#580]
Help missing for Number Features - Field To Number parameter in the ClearingOperationsTools_arcmap.tbx tools (not a problem in Pro).

## Expected Behavior
Include tool help:
"The field from the point feature class that you wish to have numbered. "

## Current Behavior
Tool help is missing.

![image](https://user-images.githubusercontent.com/3093182/29982325-1c76d708-8f06-11e7-8bad-057a28bfd6fb.png)

## Possible Solution
Just fix it.

## Steps to Reproduce (for bugs)
N/A

## Context
N/A

## Your Environment
* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by topowright** [comment]
This has been fixed in pull request: https://github.com/Esri/solutions-geoprocessing-toolbox/pull/578

Please verify @mfunk

**Comment by mfunk** [comment]
Fixed.
