### ISSUE TITLE
Create MGRS/USNG reference grid as geoprocessing tool

### ISSUE THREAD

**Issue by mfunk** [Esri/solutions-geoprocessing-toolbox#581]
Need a tool to create a reference grid based on MGRS/USNG in Clearing Operations (currently). This should be similar in function to the GRG widget.

## Expected Behavior
Create a reference grid based on Military Grid Reference System (MGRS)/United States National Grid (USNG).
* User will select a starting point or area.
* User should be able to enter a size for the grid (10km, 1km, 100m, 10m, etc.)
* User should be able to select output feature name/location
* Output features should match MGRS boundary

![image](https://user-images.githubusercontent.com/3093182/30080589-ec7e61ac-9238-11e7-8962-cc822ff00c4a.png)

## Possible Solution
Add new tool(s) to existing Clearing Operations toolbox.

## Context
Based on ideas in GRG widget.

## Your Environment
* Version used: Desktop 10.5, Pro 2.0
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by mfunk** [comment]
Looking at the Make Grids and Graticules Layer tool in ArcMap (tool is NOT available in Pro). This tool generates several features within a defined extent including a series of lines (USNG boundaries in the screenshot), mask/neatlines (not really needed), annotation, tick marks, etc.

USNG corner showing annotation and ticks:
![image](https://user-images.githubusercontent.com/3093182/30495271-3b920b58-9a00-11e7-8ec1-118f8501b731.png)

USNG lines:
![image](https://user-images.githubusercontent.com/3093182/30495311-62fdfecc-9a00-11e7-830e-d84d2c7c49d0.png)

**Comment by mfunk** [comment]
Spoke with @adgiles today and he's started working on porting pieces of the JS code to Python for building MGRS/USNG grids in geoprocessing tools. If he can build the business logic I can build the tool logic.

Also heard from Layout team about the Make G&G Layer tool. Apparently you can use Production Mapping to build the template XML files for the tool. It's supposed to be outlined in Exercise 2b of "Creating grids and graticule layers" tutorial: http://desktop.arcgis.com/en/arcmap/latest/extensions/production-mapping/exercise-2-creating-grid-and-graticule-layers.htm

**Comment by mfunk** [comment]
Added tool UI to my working branch (mf-581-mgrs-in-grg):

![image](https://user-images.githubusercontent.com/3093182/30669769-5e41412e-9e14-11e7-9d6d-217fd7dc3ff2.png)

Tool is (tentatively) called **Define Reference Grid From Area**. UI/params (tentatively) are:
* Input Grid Area - feature set to select/draw an area on the map to create the ref grid.
* Reference Grid - select MGRS or USNG
* Grid Square Size - select from:
   * GRID_ZONE_DESIGNATOR
   * 100000M_GRID
   * 10000M_GRID
   * 1000M_GRID
   * 100M_GRID
   * 10M_GRID
* Output Grid Features - output grid feature to be created

![image](https://user-images.githubusercontent.com/3093182/30669758-50236892-9e14-11e7-9f80-2cee729cd776.png)

**Comment by mfunk** [comment]
Got a starter script from @adgiles this morning. I'll start working on:
* some validation code to check input area against Grid Square Size to error or warn user (or reduce selection options) when they are trying to create more than 2000 grid squares.
* code review on the stuff from gigzy.
* begin tool test logic for the new tool.

**Comment by mfunk** [comment]
I've been trying to play with tool validation for the MGRS tool that would only allow specific grid sizes for a defined area. What I would like is to not allow grid size options that will generate more than 2000 grid features. However, I can't get access to the extent object of a feature set during validation (submitted a Q to sp-geoprocessing on this). So my other option is to move that limitation to the tool class logic, with an option to ALLOW_LARGE_GRIDS or NO_LARGE_GRIDS and add an error/warning as needed. What are your thoughts? Need feedback.

**Comment by Dbarnes1** [comment]
@mfunk it seems like the tool class logic option will work fine, it just wont be as accurate as the specific grid size limitation. In other words, the limitation will be based on size of the AOI, not the potential number of cells. In my opinion, I think this would be fine to implement for this release, as it will still successfully warn users that they are about to create a GRG that will have an excessive number of cells and they should increase their cell size.

**Comment by Dbarnes1** [comment]
writing a draft of the checklist test for this tool, unless anyone disagrees I'm going to append checks for this tool to the test @mfunk made for the other GP tools

**Comment by BobBooth** [comment]
I like the idea of having an ALLOW_LARGE_GRIDS or NO_LARGE_GRIDS option.  Nice to be able to warn people that the're going to be creating a lot of cells. Also nice for them to be able to go ahead an do that. Maybe they actually do want 10x10m cells for the entire Western US... if they want to burn the disk space, why shouldn't they?

**Comment by mfunk** [comment]
First running prototype of the **Define Reference Grid from Area** tool is in the *mf-581-mgrs-in-grg* branch. Right now it:
* creates MGRS grids, not USNG
* stops execution if the selected area's extent exceeds the grid size critical values (see tool doc).
* creates output in WGS 84 only
* Has different field names depending upon grid size selected
* could still break easily.

**Comment by Dbarnes1** [comment]
looks like it basically works, but labeling hasn't been implemented yet.

Screenshot is 100m grid squares over Brooklyn: 
![image](https://user-images.githubusercontent.com/13024357/30767784-d21d625c-9fb4-11e7-87a3-de389c604eaf.png)


@mfunk is that the case?

**Comment by mfunk** [comment]
Yes. No labels yet.

**Comment by mfunk** [comment]
Need this one to be verified.
Going to log a separate issue to figure out how to label grids. Not as simple as just turning them on.

**Comment by Dbarnes1** [comment]
@mfunk looks like the tool is basically working in ArcMap, but not in Pro

ArcMap: 
![image](https://user-images.githubusercontent.com/13024357/30833888-bb7ffef8-a205-11e7-9e80-843b38994446.png)

Pro:
![image](https://user-images.githubusercontent.com/13024357/30833908-cd2a5392-a205-11e7-97c7-fe7780e740e9.png)

@mfunk I'm going to push this one back to in progress, let me know if I can help figure out how to get the tool to run in Pro

**Comment by Dbarnes1** [comment]
now that the tool runs in pro, I'm going to verify this and move it to done, we can track bugs and other features in future issues, but this initial create tool issue has been completed.
