### ISSUE TITLE
Rename Clearing Operations Tools

### ISSUE THREAD

**Issue by mfunk** [Esri/solutions-geoprocessing-toolbox#582]
Rename Clearing Operations tools to a more generic name such as GRG Tools. 
Name: 
* ClearingOperationsTools_pro.tbx --> GRGTools_pro.tbx
* ClearingOperationsTools_arcmap.tbx --> GRGTools_arcmap.tbx
Alias: _grg

It was also discussed to rename the tools in the new GRG toolbox to reflect those in the GRG widget:
* Canvas Area GRG --> Create GRG from Area
* Point Target GRG --> Create GRG from Point

Also need to update tests to reflect new toolbox name.
* .\utils\tests\Configuation.py

**Comment by mfunk** [comment]
Current refactor examples:

![image](https://user-images.githubusercontent.com/3093182/30120625-3de7f9a4-92de-11e7-85ae-2b76e57bc41b.png)

**Comment by mfunk** [comment]
Got rename working for Create GRG from Area. Compared output from original Canvas Area GRG (CAGRG) and Create GRG from Area (CGRGFA):
```
Executing: FeatureCompare CAGRG0002 CGRGFA0005 Grid ALL # "0.001 Meters" 0.001 0.001 # # NO_CONTINUE_COMPARE #
Start Time: Thu Sep 07 15:50:09 2017
FeatureClass: Shape types are the same.
FeatureClass: Feature types are the same.
Table: Table row counts are the same.
FeatureClass: Feature class extents are the same.
GeometryDef: GeometryDefs are the same.
Field: Field properties are the same.
Table: Table row counts are the same.
SpatialReference: Spatial references are the same.
Table: Rows are the same.
Succeeded at Thu Sep 07 15:50:09 2017 (Elapsed Time: 0.21 seconds)
```

**Comment by mfunk** [comment]
PR #587 is in to rename the tools.

**Comment by mfunk** [comment]
Just need one reviewer to verify and close this one out once the PR is merged.

**Comment by joebayles** [comment]
@mfunk not to be difficult, but should we call them:
- Create GRG from Area
- Create GRG from Point
  -or-
- Define Grid from an Area
- Define Grid from a Point

... based on the widget?
![image](https://user-images.githubusercontent.com/5016557/30460961-2c889758-996f-11e7-985a-284fec32b293.png)

**Comment by mfunk** [comment]
@joebayles 
We went with **Create GRG from Area** and **Create GRG from Point** based on the GRG widget, and made all the associated changes that went with it. I'm really not looking forward to changing them again, and again in another few weeks. Pick something and stick with it please.

**Comment by joebayles** [comment]
Verified.
