### ISSUE TITLE
Create GRG from Area tool should have more choices for Cell Units

### ISSUE THREAD

**Issue by elinz** [Esri/solutions-geoprocessing-toolbox#589]
Tool only has Meters and Feet as the only choices. This tool is being released in the GRG solution with the GRG widget, which has the following choices for cell units:
Meters
Kilometers
Miles
Nautical Miles
Yards
Feet

I believe the minimum viable product should include all the same Cell Unit values as the widget.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by adgiles** [comment]
Addressed in PR #640

I have checked the documentation on solutions.arcgis.com and it doesn't go into detail about the options for the unit values, so no documentation change is required.

**Comment by lfunkhouser** [comment]
Have the GRG and Clearing Operations solutions been updated for the next release to include this feature? @topowright @dfoll @ACueva
