### ISSUE TITLE
GRG GP tools that use Alpha-Alpha or Numeric-Numeric labeling style should employ separator

### ISSUE THREAD

**Issue by BobBooth** [Esri/solutions-geoprocessing-toolbox#591]
The Create GRG from Area and Create GRG from Point tools both have an Alpha-Alpha and Numeric-Numeric labeling options.
The labels should have a separator.
See discussion here:
https://github.com/ArcGIS/solutions-grg-widget/issues/16#issuecomment-327329412

**Comment by adgiles** [comment]
Addressed in PR #640 

The changes have been made to the code within the solutions-geoprocessing-toolbox repo but have not been applied to the templates

**Comment by topowright** [comment]
This change will need to be updated in the GRG solution and the Clearing Ops solution.

**Comment by topowright** [comment]
I have verified that the "-" separator has been added to the new layout for the GRG Tools. These tools are also the Clearing Operations toolbox. Going forward I think we should blow away the duplicate tools in the Clearing Operations toolbox and have the GRG Tools just in the GRG toolbox. Then when we release the update to the solution we can just pull in the Clearing Operations toolbox to give us the Number Features tool and the GRG toolbox to give us the GRG tools. 

The result of this would allow us to only have to maintain the tools in one location.

**Comment by topowright** [comment]
Can we use this item as the item to release the Clearing Ops and the GRG Updates or do we need a new item to track these changes?

**Comment by topowright** [comment]
I have updated the checklist task in the following repo: 
https://github.com/ArcGIS/solutions-defense-test-catalog/blob/master/Tests/Clearing-Operations_ArcGIS-Pro.md
https://github.com/ArcGIS/solutions-defense-test-catalog/blob/master/Tests/Clearing-Operations_ArcMap.md

**Comment by topowright** [comment]
I need someone to verify that what I have added to the checklist tests are good enough for the features that have been added.

**Comment by csmoore** [comment]
Reopening issue to fix unit tests that broke when parameter list changed.

**Comment by csmoore** [comment]
Unit tests updated in #642 - ready for QC

**Comment by topowright** [comment]
verified.
