### ISSUE TITLE
Update Tool help for Create GRG from Point

### ISSUE THREAD

**Issue by topowright** [Esri/solutions-geoprocessing-toolbox#592]
Red square missing around the call out area
## Expected Behavior

The image in the tool help should have a red square around the callout image to provide clarity
## Current Behavior

There is no red square around the call out area and it is hard to understand the graphic at first. 
## Possible Solution

Add a red square around the call out area
## Steps to Reproduce (for bugs)

1. Open the tool help
2. View the image
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by topowright** [comment]
Here is an example image of what it looks like now. 

![image](https://user-images.githubusercontent.com/5488313/30438773-edd050d4-9926-11e7-9d4e-d4e12b767d96.png)

**Comment by topowright** [comment]
Also the lines should match up with the squares on the map

**Comment by adgiles** [comment]
@topowright Addressed in PR #637

**Comment by topowright** [comment]
![image](https://user-images.githubusercontent.com/5488313/33618872-8b3adde2-d998-11e7-856b-32cd53e87340.png)
This looks good
