### ISSUE TITLE
Remove Grid Size feature set parameter from Create GRG from Point

### ISSUE THREAD

**Issue by mfunk** [Esri/solutions-geoprocessing-toolbox#593]
Per discussions earlier this week. The Grid Size parameter in the Create GRG From Point tool (GriddedReferenceGraphicTools.pyt) is unnecessary and should be removed. 

## Expected Behavior
User should either choose the default size or type in a height and width and select units using Cell Width, Cell Height, Cell Units.

## Current Behavior
The idea was that the user could draw a box to represent the size of the output GRG grid cells. But this is not really how things are done. The GRG grid cell height and width are based on more standard sizes like 100m, 200m, 500m, etc.

![image](https://user-images.githubusercontent.com/3093182/30453832-0fccc514-994f-11e7-8897-1578b2271456.png)

## Possible Solution
Have to remove parameter from tool logic (NumberFeaturesTools.py), and anything that dealt with it in the execution code.

## Steps to Reproduce (for bugs)
N/A

## Context
Confusing to user what is expected without opening tool help and reading about it.

## Your Environment
* Version used: ArcMap 10.3.1 and up, ArcGIS Pro 1.4 and up.
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile): Windows 10
* Link to your project:

**Comment by topowright** [comment]
@mfunk I am changing the title of this issue to reflect the proper tool "Create GRG from Point"

**Comment by adgiles** [comment]
Addressed in PR #640 

The changes have been made to the code within the solutions-geoprocessing-toolbox repo but have not been applied to the templates.

Documentation will require an update

**Comment by topowright** [comment]
I have verified this is now complete: 

![image](https://user-images.githubusercontent.com/5488313/34272659-f4074996-e645-11e7-917e-68814842b2b1.png)

Nothing else needs to be done on this item
