### ISSUE TITLE
Number Features tool fails if I specify the existing Number field as the target field to number 

### ISSUE THREAD

**Issue by BobBooth** [Esri/solutions-geoprocessing-toolbox#594]
Using the Clearing Operations solution sample data, if I run Number Features (from @mfunk mf-clrops-grg-framework branch) I am seeing the tool fail if I specify the Number field, but it works if I leave the input empty.

## Expected Behavior
Should number this field if it is specified.

## Steps to Reproduce (for bugs)
1. Open (ArcMap 10.3.1) the Clearing Operations solution
2. Connect to the toolbox
3. Run the Number Features tool.
4. Define an AOI around some or all of the features interactively.
5. Choose the "Numbered Structures Sample" layer as the features to number. This dataset has an Integer field called Number.
6. Leave Field to Number blank.
7. Leave output blank.
(INSERT EDITS BB)
The tool runs correctly.

8. Re-run, as before, but for step 6, change the Field to Number to use the "Number" field.
(END EDITS BB)
Tool will fail with:
Messages
Executing: NumberFeatures "Feature Set" "Results\Numbered Structures Sample" Number #
Start Time: Thu Sep 14 16:38:21 2017
Running script NumberFeatures...
outputFeatureClass: None
Shape type: Polygon
App environment: OTHER
Selecting points from <geoprocessing Layer object object at 0x0E3C7FC8> inside of the area in_memory\areaToNumber
Selected 15 points
Sorting the selected points geographically, left to right, top to bottom
Numbering the fields
Clearing the selection
Copying the features to the input, and then deleting the temporary feature class
PYTHON ERRORS:
Traceback info:
  File "C:\solutions-geoprocessing-toolbox-mf-clrops_Fix_Fix\solutions-geoprocessing-toolbox-mf-clrops-grg-framework\clearing_operations\scripts\NumberFeaturesTool.py", line 234, in NumberFeatures
    arcpy.AddMessage("what is the numberingField: " + numberingField)

Error Info:
cannot concatenate 'str' and 'geoprocessing value object' objects
ArcPy ERRORS:
Executing: SelectLayerByAttribute "<geoprocessing Layer object object at 0x0E3C7FC8>" CLEAR_SELECTION #
Start Time: Thu Sep 14 16:38:23 2017
Succeeded at Thu Sep 14 16:38:23 2017 (Elapsed Time: 0.00 seconds)

Completed script NumberFeatures...
Failed to execute (NumberFeatures).
Failed at Thu Sep 14 16:38:23 2017 (Elapsed Time: 1.46 seconds)

## Context
This causes an impediment for the Clearing Operations solution release.

## Your Environment
ArcMap 10.3.1
Clearing Operations Solution (from staging)
Tool from the current (mfunk mf-clrops-grg-framework) branch of the repo.

**Comment by BobBooth** [comment]
![image](https://user-images.githubusercontent.com/3801392/30455096-934f5790-996c-11e7-94ec-4818a47d4e8e.png)
![image](https://user-images.githubusercontent.com/3801392/30455107-9ca1d444-996c-11e7-9de7-a26b9d2949c0.png)

**Comment by BobBooth** [comment]
@mfunk @topowright @csmoore @lfunkhouser 
This failure of the tool is an Impediment for the integration of the new toolboxes in the Clearing Operations solution. FYI.

**Comment by BobBooth** [comment]
It seems as though I cannot assign or set labels at the moment for this repo.
??
@mfunk

**Comment by mfunk** [comment]
@BobBooth 
In the steps you have 'Leave Field to Number blank.'
But the dialog screenshot has "Number" selected.
By default it should be empty, even after selecting Features to Number.
Did you mean to use a different screenshot...
![image](https://user-images.githubusercontent.com/3093182/30455391-98834a2c-9954-11e7-88a2-2c552c7cb9cc.png)

**Comment by BobBooth** [comment]
@mfunk - sorry, I have edited the original issue text to clarify. When Field to Number is blank it runs fine. When it is set to the "Number" field in the data it fails.
