### ISSUE TITLE
Project Template packaging is failing for me when this LYRX file attached to project

### ISSUE THREAD

**Issue by BobBooth** [Esri/solutions-geoprocessing-toolbox#598]
I'm getting a Data Cannot Be Opened error message when I try to package up ClearingOperation with this LYRX file attached.
![badpathcompoundmap](https://user-images.githubusercontent.com/3801392/30500576-f4b18812-9a2c-11e7-9fc0-a23dcd7d3b8b.png)
![badpathcompoundmap_inareainputlyrx](https://user-images.githubusercontent.com/3801392/30500578-f72f699c-9a2c-11e7-8b5d-2ace4eaf5686.png)

https://github.com/Esri/solutions-geoprocessing-toolbox/blob/43b3f3ba06b044e99b1d8284bb2df26e82ee132a/clearing_operations/layers/AreaInput.lyrx#L40

**Comment by topowright** [comment]
This can be closed as it was a relic of us trying to figure out how to use the
