### ISSUE TITLE
GRG "Label Style" in GP tools is "Label Type" in widget

### ISSUE THREAD

**Issue by Dbarnes1** [Esri/solutions-geoprocessing-toolbox#604]
## Expected Behavior
I'd expect that what is currently called label style in the GP tools to be called label type (alpha-numeric, alpha, numeric)

## Possible Solution
Change the option that is called label style to label type so that they are the same between the widget and the GP tools

Here are screenshots for reference: 
GP tools
![image](https://user-images.githubusercontent.com/13024357/30608254-9bea0f62-9d2c-11e7-8050-a74f678cf690.png)
Widget
![image](https://user-images.githubusercontent.com/13024357/30608324-cf947104-9d2c-11e7-9fcd-78ae38ed5278.png)

Label style refers to things like font, text color, transparency, etc.

**Comment by elinz** [comment]
@Dbarnes1 How about the label name change in the gp tools and not the widget? Calling this property "Label Type" makes more sense. We are using the term "Label Style" to define the settings such as font, size, color. Or what would make maybe even more sense to the end users is call this property "Labeling Scheme" (this would require changing the widget, xmetal doc, gp tool, gp tool doc, and also xmetal doc.

**Comment by Dbarnes1** [comment]
@elinz we're on the same page - change the tool to label type makes the most sense

**Comment by mfunk** [comment]
@Dbarnes1 Please verify this with #608

**Comment by Dbarnes1** [comment]
looks good @mfunk 
![image](https://user-images.githubusercontent.com/13024357/30834683-19b74ffa-a209-11e7-94ae-331bfec19cc9.png)
![image](https://user-images.githubusercontent.com/13024357/30834705-386b950a-a209-11e7-84a0-720b657dc055.png)


cloing
