### ISSUE TITLE
Possibly change the name for multidimensional data

### ISSUE THREAD

**Issue by topowright** [Esri/solutions-geoprocessing-toolbox#605]
The multidimensional data xml file names are too long: 
![image](https://user-images.githubusercontent.com/5488313/30649857-3bcf128a-9dd6-11e7-9037-4b0aa3aea77b.png)

## Expected Behavior

As a user I should be able to copy these inside of a pro project
## Current Behavior

![image](https://user-images.githubusercontent.com/5488313/30649875-46973530-9dd6-11e7-87b3-1ea0df6c2717.png)

## Possible Solution

shorten the name
## Steps to Reproduce (for bugs)

1.copy the SGT folder into a Pro project
2.
3.
4.

## Context

Users might use projects to compartmentalize their work. We should be able to copy all of our tools into a Pro Project 
## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:
ArcGIS Pro 2.0

**Comment by lfunkhouser** [comment]
@topowright Is this still an issue? Are there additional files as culprits? Is there a workaround? Add labels to the issue to better categorize it.

**Comment by topowright-zz** [comment]
This is not an issue if you copy the file to a location where there is a shorter path. Currently I am closing this based on the fact that I am now able to clone the repo and this does not seem to be an issue any longer.
