### ISSUE TITLE
Define Reference System from Area tool does not create grids squares for zipper regions

### ISSUE THREAD

**Issue by elinz** [Esri/solutions-geoprocessing-toolbox#614]
Ran "Define Reference System from Area" gp tool in ArcGIS Pro 2.0 by creating an area using the "Polygon" template tool with the following parameters:
Reference Grid: MGRS
Grid Square Size: 10000M_GRID
Large Grid Handling: ALLOW_LARGE_GRIDS

Ran the tool. Output shown below:
![image](https://user-images.githubusercontent.com/4635490/30835732-9d24b4c2-a20e-11e7-94df-40935d215b64.png)

NOTE: I've exported the Input GRG area polygon to a file geodatabase found here:
Development\Commercial\GitHubIssueReplicationData\solutions-geoprocessing-toolbox\Issue_614\Issue_614.gdb feature class named "InputGRGArea".

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by adgiles** [comment]
Wrong use of the break statement to come out of the loop should have
been continue to make sure the rest of the loop continues

Addressed in PR #623
