### ISSUE TITLE
Define Reference Grid from Area gp tool is not prefixing grid value with the GZD value

### ISSUE THREAD

**Issue by elinz** [Esri/solutions-geoprocessing-toolbox#617]
When I run tool in Utah for the following sizes the grid value is not being prefixed with the GZD value (i.e. 12T): 

- [x] 100k: gp tool stores value: UK (should be 12TUK)
- [x] 10k:   gp tool stores value: UK85 (should be 12TUK85)
- [x] 1K:     gp too stores value: UK8461 (should be 12TUK8461)
- [x] 100:   gp tool stores value: UK844636 (should be 12TUK844636)
- [x] 10:     gp tool stores value: UK85886130	(should be 12TUK85886130)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by adgiles** [comment]
Addressed in PR #623

**Comment by elinz** [comment]
Verified the fix in both ArcMap and ArcGIS Pro in the dev branch.
