### ISSUE TITLE
Define Reference Grid from Area gp tool is not calculating grid name correctly for 10k cells (ArcGIS Pro)

### ISSUE THREAD

**Issue by elinz** [Esri/solutions-geoprocessing-toolbox#619]
Ran Define Reference Grid from Area gp tool with the following parameters:
![image](https://user-images.githubusercontent.com/4635490/30873976-d6341b6e-a2a3-11e7-9839-11bf14be4ac1.png)
NOTE: a file geodatabase feature class containing the input GRG area can be found here:
Development\Commercial\GitHubIssueReplicationData\solutions-geoprocessing-toolbox\Issue_619\Issue_619.gdb\InputGRGArea

Output is shown below. Identified the lower left corner grid and named the grid cell "CS2.03.0":
![image](https://user-images.githubusercontent.com/4635490/30874063-1e3785ae-a2a4-11e7-9515-6c6e80c94940.png)

![image](https://user-images.githubusercontent.com/4635490/30874303-b7e806ce-a2a4-11e7-9651-7350c4659cc8.png)
The grid cell should have been named 13UCS23 (note the issue for the missing GZD prefix is handled in another issue #617).

I was trying to verify that 1000m grid cells were named correctly but ran into issue #615 

NOTE: when running the tool in ArcMap the gp tool is calculating the grid to CS23.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by adgiles** [comment]
Addressed in this PR https://github.com/Esri/solutions-geoprocessing-toolbox/pull/623

**Comment by elinz** [comment]
Verified fixed in PR #623. Closing issue.
