### ISSUE TITLE
Define Reference Grid from Area gp tool is not creating all the necessary 10k cells

### ISSUE THREAD

**Issue by elinz** [Esri/solutions-geoprocessing-toolbox#620]
Ran the Define Reference Grid from Area gp tool with the following parameters:
![image](https://user-images.githubusercontent.com/4635490/30875669-17d73664-a2a9-11e7-95a0-d0fa5d402711.png)
NOTE: a file geodatabase feature class containing the input GRG area can be found here:
Development\Commercial\GitHubIssueReplicationData\solutions-geoprocessing-toolbox\Issue_620\Issue_620.gdb\InputGRGArea

The tool created the following output with missing grids:
![image](https://user-images.githubusercontent.com/4635490/30875828-93c76262-a2a9-11e7-883c-3aee1d8c600b.png)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by elinz** [comment]
@nfeuerstein I retested creating a 10k meter grid size over a much small area and the problem where the grid squares are not created over the zipper still exists. So we will definitely need to look more into this issue: 

![image](https://user-images.githubusercontent.com/4635490/30886035-767131e0-a2ca-11e7-99d7-f761590043e6.png)

**Comment by adgiles** [comment]
Same issue as #614 

Wrong use of the break statement to come out of the loop should have been continue to make sure the rest of the loop continues

**Comment by elinz** [comment]
Verified this is fixed. Fix in dev branch. Closing issue.
