### ISSUE TITLE
Define Reference Grid from Area - Scratch Workspace not deleting

### ISSUE THREAD

**Issue by adgiles** [Esri/solutions-geoprocessing-toolbox#624]
When running the Define Reference Grid from Area within ArcGIS pro a scratch workspace is created within the init function using Utilities.MakeScratchGeodatabase(). This creates a temp file geodatabase with a random 6 letter name.

This database is supposed to be deleted when the script finishes but this is not happening.

## Expected Behavior

The temp database is deleted

## Current Behavior

Temp databases are residing in the project/scratch folder

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by mfunk** [comment]
This doesn't cause the tool to crash or produce bad data, just not cleaning up after itself. The tool class destructor __del__ is set up to delete the scratch workspace when done, but it is silently ignoring the error that there is a schema lock on scratch workspace.
Will have to investigate further (in a later release) which dataset is still open and keeping the lock alive.

**Comment by adgiles** [comment]
Removed the need for the temp scratch database my creating all temp layers in_memory.

Changes within this PR #649
