### ISSUE TITLE
Create Reference System GRG from Area gp tool does not check if input area falls into polar region

### ISSUE THREAD

**Issue by elinz** [Esri/solutions-geoprocessing-toolbox#625]
The Create Reference System GRG from Area gp tool does not check if the input area is located in the MGRS polar regions (i.e. north of 84N degrees; south of 80S degrees). The tool runs successfully and  creates an output dataset, but the dataset does not contain any records.

## Expected Behavior

I would expect the tool to check if the input is in or crosses into the MGRS polar regions and exit with an error informing that the input area is invalid. With the current behavior, users won't understand the reason why the GRG was not created.

@nfeuerstein @lfunkhouser @joebayles I've labeled this with "sprint backlog" so we can address this through documentation as a "Known Issue" and add the check and error message at another release. Thoughts?

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by joebayles** [comment]
Documented.

**Comment by BobBooth** [comment]
I would expect the tool to use MGRS coordinates appropriate for polar regions. Would consider that an enhancement.

**Comment by joebayles** [comment]
@BobBooth already in the backlog, it's a core issue.

**Comment by mfunk** [comment]
Moved to After Next

**Comment by adgiles** [comment]
Addressed in PR #659 

Added check to see if the input AOI overlaps either of the polar
regions. If true message added to the console informing the user that
cells within the polar region will not be created

**Comment by topowright** [comment]
I cannot verify this because the toolbox shows broken. I am attempting to do this on ArcGIS Pro 2.1

**Comment by topowright** [comment]
I am not seeing this experience. I have attempted to create a GRG over this following area: 
![image](https://user-images.githubusercontent.com/5488313/35766178-be2f3aea-0887-11e8-92f5-3deb3aec3e67.png)

**Comment by adgiles** [comment]
@topowright I don’t think you are at a high enough latitude - 84N+

**Comment by BobBooth** [comment]
I tested, tool seems to be behaving correctly.
Grid created up to polar region, GP messages output warning about features not created in polar region.
![image](https://user-images.githubusercontent.com/3801392/35815376-4f3e1efe-0a66-11e8-8d57-4ad856b775e1.png)

@adgiles  @topowright

**Comment by BobBooth** [comment]
@adgiles - change message to a warning so user gets more obvious notification.

**Comment by topowright** [comment]
WE need to update the known issues for this .

**Comment by topowright** [comment]
I have removed this from the known issues for April release and added it to the issues addressed for April 2018

**Comment by topowright** [comment]
I have removed this from the known issues for April release and added it to the issues addressed for April 2018 @dfoll @ACueva please verify

**Comment by adgiles** [comment]
updated polar message to a warning to make it more obvious. PR #664

**Comment by BobBooth** [comment]
@adgiles  - thanks, this looks to be working correctly now - the results are created, but the GP results show a Warning condition.
![image](https://user-images.githubusercontent.com/3801392/35928619-98502452-0bfb-11e8-968f-b01634fec515.png)
@topowright

**Comment by BobBooth** [comment]
Updated checklist test to include test for MGRS grids that cross into polar region, in PR https://github.com/ArcGIS/solutions-defense-test-catalog/pull/91

**Comment by dfoll** [comment]
I verified this is no longer in known issues.

**Comment by topowright** [comment]
Testing this functionality on Build 8 of GRG . Using ArcGIS Pro 2.1 and ArcMap 10.6

**Comment by topowright** [comment]
I have verfied that these changes are working in 10.6 and ArcGIS Pro 2.1.

![image](https://user-images.githubusercontent.com/5488313/38201780-458f8a32-364e-11e8-847d-2ceacf1441ec.png)

**Comment by topowright** [comment]
I have updated the home page on the solutions page with the issues addressed for April 2018. I need to do the following things before I can move this issue to done: \

- [ ]  update the CMS pages with issues addressed
- [ ] submit pull request for website changes.

**Comment by topowright** [comment]
I have updated the website with the PR that is listed above and marked @dfoll as the reviewer.
