### ISSUE TITLE
GRG (CreateReferenceSystemGRGFromArea) Unit Tests Failing at Pro 2.1

### ISSUE THREAD

**Issue by csmoore** [Esri/solutions-geoprocessing-toolbox#634]
The GRG units tests - CreateReferenceSystemGRGFromAreaTestCase - are failing as of Pro 2.1.10223

Several Clearing Ops units tests are failing on the delete scratch GDB step at Pro 2.1

Error 1:

```
Exception ignored in: <bound method ReferenceGrid.__del__ of <scripts.RefGrid.ReferenceGrid object at 0x00000281C924E198>>
Traceback (most recent call last):
  File "C:\Users\----\Documents\GitHub\solutions-geoprocessing-toolbox\clearing_operations\scripts\RefGrid.py", line 43, in __del__
    arcpy.Delete_management(self.scratch_workspace)
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 4022, in Delete
    raise e
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 4019, in Delete
    retval = convertArcObjectToPythonObject(gp.Delete_management(*gp_fixargs((in_data, data_type), True)))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 506, in <lambda>
    return lambda *args: val(*gp_fixargs(args, True))
arcgisscripting.ExecuteError: ERROR 000601: Cannot delete C:\Users\----\AppData\Local\Temp\scratch\HXJOAH.gdb.  May be locked by another application.
Failed to execute (Delete).
```

## Steps to Reproduce (for bugs)

1. On **Pro 2.1**
2. Run Units Test Driver (TestKickstartPro.bat)
3. Note Clearing Ops error (above)

## Your Environment

* Versions used: 
Current Dev branch
Pro 2.1 Beta 1 (2.1.9865)
Windows 10

Error 2:

```
.....CreateReferenceSystemGRGFromAreaTestCase.testCreateReferenceSystemGRGFromArea_10mNoLargeGrids
Importing toolbox...
Running tool (CreateReferenceSystemGRGFromArea)
INFO: 2017-10-26 09:03:53,459 Running tool (CreateReferenceSystemGRGFromArea)
ERROR: Area (2310902.9806220606) exceeds large grid value for 10M_GRID. Use a smaller Input Area or choose a larger Grid Size.
```

![image](https://user-images.githubusercontent.com/3090809/32056227-1c47be94-ba32-11e7-9612-cd368089577e.png)

**Comment by BobBooth** [comment]
I am seeing the the Create Reference System GRG from Area tool producing an error (although it also seems to be outputting grid features), on Pro 2.1
![image](https://user-images.githubusercontent.com/3801392/34274607-552bc3f2-e667-11e7-96a2-c4bb5450c640.png)
2.1.0 build 10235
Windows 8 Enterprise

Start Time: Thursday, December 21, 2017 3:45:15 PM
Running script CreateReferenceSystemGRGFromArea...
Creating Grid zones/latitude bands...
Creating 100k grid squares...
Creating sub 100K grid squares...
Exception ignored in: <bound method ReferenceGrid.__del__ of <scripts.RefGrid.ReferenceGrid object at 0x0000000A8AC595C0>>Traceback (most recent call last):  File "C:\GriddedReferenceGraphic\GriddedReferenceGraphic\ArcGIS Desktop\toolboxes\scripts\RefGrid.py", line 43, in __del__    arcpy.Delete_management(self.scratch_workspace)  File "c:\program files\arcgis\pro\Resources\arcpy\arcpy\management.py", line 4103, in Delete    raise e  File "c:\program files\arcgis\pro\Resources\arcpy\arcpy\management.py", line 4100, in Delete    retval = convertArcObjectToPythonObject(gp.Delete_management(*gp_fixargs((in_data, data_type), True)))  File "c:\program files\arcgis\pro\Resources\arcpy\arcpy\geoprocessing\_base.py", line 506, in <lambda>    return lambda *args: val(*gp_fixargs(args, True))arcgisscripting.ExecuteError: ImageERROR 000601: Cannot delete C:\Users\{user}\Documents\ArcGIS\Projects\GRG_Blog_Post\scratch\JWSNRR.gdb.  May be locked by another application.Failed to execute (Delete).
Completed script Create Reference System GRG from Area...
ImageFailed to execute (CreateReferenceSystemGRGFromArea).
Failed at Thursday, December 21, 2017 3:45:27 PM (Elapsed Time: 11.56 seconds)

**Comment by BobBooth** [comment]
@mfunk - have you seen this?

**Comment by BobBooth** [comment]
@topowright  @dfoll  @ACueva  - FYI

**Comment by BobBooth** [comment]
@csmoore  observed that the issue I saw looks like this one: 
https://github.com/Esri/solutions-geoprocessing-toolbox/issues/627
@topowright

**Comment by topowright** [comment]
@BobBooth this is not an issue in the current version on the SGT repo. I have tested this tool from that repo and I do not see the issue. 

@csmoore we might need to update the unit test based on the new changes introduced with these tool updates.

**Comment by BobBooth** [comment]
@topowright - interesting. It is an issue with the currently released version of the template downloadable from the Solutions page, on Pro 2.1.
Guess that means the solution needs to be updated with the new GP tools. Will the change be backwards compatible, or are we going to need to point to two versions?

**Comment by csmoore** [comment]
@topowright - I do see where a new parameter was added last week in https://github.com/Esri/solutions-geoprocessing-toolbox/commit/e2ddfa9704d0ec2f41d790abe39ea013fb13c159  - so probably a different issue - but can update the tests and see if that changes anything.

Maybe @BobBooth - can test out the latest version from this repo to see if that does address the problem, I'd also be curious if anyone else is seeing a broken toolbox here:

![image](https://user-images.githubusercontent.com/3090809/34310070-61ffd282-e723-11e7-915a-076835e02faf.png)

**Comment by csmoore** [comment]
I got the same error @BobBooth got when I tried to run the CreateReferenceSystemGRGFromArea tool - also fails the same in unit test :

Config:
1. Last dev branch from this repo
2. Pro 2.1.10223

```
Start Time: Friday, December 22, 2017 7:25:42 PM
Running script CreateReferenceSystemGRGFromArea...
Creating Grid zones/latitude bands...
Exception ignored in: <bound method ReferenceGrid.__del__ of <scripts.RefGrid.ReferenceGrid object at 0x000001C1FC6AABA8>>
Traceback (most recent call last):
  File "C:\Users\---\Documents\ArcGIS\Projects\TestCO-new\scripts\RefGrid.py", line 43, in __del__
    arcpy.Delete_management(self.scratch_workspace)
  File "c:\program files\arcgis\pro\Resources\arcpy\arcpy\management.py", line 4103, in Delete
    raise e
  File "c:\program files\arcgis\pro\Resources\arcpy\arcpy\management.py", line 4100, in Delete
    retval = convertArcObjectToPythonObject(gp.Delete_management(*gp_fixargs((in_data, data_type), True)))
  File "c:\program files\arcgis\pro\Resources\arcpy\arcpy\geoprocessing\_base.py", line 506, in <lambda>
    return lambda *args: val(*gp_fixargs(args, True))
arcgisscripting.ExecuteError:  ERROR 000601: Cannot delete C:\Users\---\Documents\ArcGIS\Projects\TestCO-new\scratch\SZAZSG.gdb.  May be locked by another application.
Failed to execute (Delete).
Completed script Create Reference System GRG from Area...
 Failed to execute (CreateReferenceSystemGRGFromArea).
Failed at Friday, December 22, 2017 7:25:53 PM (Elapsed Time: 10.76 seconds)
```

![image](https://user-images.githubusercontent.com/3090809/34315507-90594232-e74e-11e7-8ca6-a2bdf30103ca.png)

![image](https://user-images.githubusercontent.com/3090809/34315492-46bb6c4a-e74e-11e7-9687-d0070028264e.png)

**Comment by topowright** [comment]
Verified that the unit tests works for Clearing Operations. That was done in issue : https://github.com/Esri/solutions-geoprocessing-toolbox/pull/642

**Comment by topowright** [comment]
The unit test does not seem to fail, but the tool fails in ArcGIS Pro 2.1

**Comment by topowright** [comment]
This is now ready to be moved into Jenkins to work in a build solution. The failing in ArcGIS Pro 2.1 was due to a schema lock on a database that @adgiles is looking into.

**Comment by ACueva** [comment]
@topowright Unassigned you on this one.  I'm assuming this is the issue we spoke about earlier.  I'll look into the Jenkins/unit test portion of this.
