### ISSUE TITLE
Create GRG from Area tool when run from Pro is creating cells that are too small

### ISSUE THREAD

**Issue by BobBooth** [Esri/solutions-geoprocessing-toolbox#652]
When I run the Create GRG From Area tool in ArcGIS Pro, with a Web Mercator coordinate system, and set the cell width and cell height to 1000 (units meters), when I check the results, the cells are .75 km on a side, not 1,000 meters.
![image](https://user-images.githubusercontent.com/3801392/35065094-2076bf8e-fb9a-11e7-9854-820a753b6ac2.png)

## Steps to Reproduce (for bugs)
1)	Open Pro 2.1.0 
2)	Create a brand new, empty project. 
3)	Add a new map. The default CS is Web Mercator based on the basemap.  
4)	Add the GriddedReferenceGraphicTools.pyt file to the project toolboxes.
5)	Double-click Create GRG From Area.
6)	Draw an area (I used a 150 km x 150 km area in the Cleveland area).
7)	Cell Width and Height should be 1,000.
8)	Units should be Meters.
9)	Run the tool. 
10)	Measure the cells. For cells that should be 1000 m on a side, I'm getting 3/4 of that (.75km).

Strangely enough, this does not seem to affect the same tool run in ArcMap (10.6.0 8321)
![image](https://user-images.githubusercontent.com/3801392/35065329-f823c008-fb9a-11e7-9e92-46d26fb38251.png)

Downloaded latest from http://solutions.arcgis.com/defense/help/gridded-reference-graphic/ (download item http://appsforms.esri.com/products/download/index.cfm?fuseaction=download.main&downloadid=1972) to test, per @topowright request. Unzipped GriddedReferenceGraphic.zip to a new folder on my system.

## Your Environment
Running Pro 2.1.0  build 10257.
Windows 8.1 Enterprise

**Comment by BobBooth** [comment]
@dfoll @topowright @csmoore  @ACueva @lfunkhouser 
This seems to be an issue with the Create GRG From Area tool in ArcGIS Pro.

**Comment by BobBooth** [comment]
![image](https://user-images.githubusercontent.com/3801392/35065894-b127ce04-fb9c-11e7-9a2b-2bcad2294b0e.png)

**Comment by dfoll** [comment]
I tested this on Pro 2.0 and am seeing the same thing.  It is not specific to just GRG from Area though, it seems any time grids are created using explicit cell height and width values they are being reduced by 25%

**Comment by BobBooth** [comment]
It doesn't seem to matter if the units are meters, feet, kilometers. The reduction seems to be consistent.

**Comment by BobBooth** [comment]
This affects the core Fishnet tool in Pro too.
![image](https://user-images.githubusercontent.com/3801392/35071007-4a0d17ea-fbad-11e7-8e3a-76bfc96a466c.png)

**Comment by adgiles** [comment]
@BobBooth Is it the settings within the measure tool within Pro? Specifically the mode Geodesic vs Planar, by default it looks like the mode in Pro is set to Geodesic:

![untitled](https://user-images.githubusercontent.com/3740334/35101850-ea53c7e8-fc58-11e7-9859-234f85dcabf7.png)

and Arcmap is Planar:

![untitled1](https://user-images.githubusercontent.com/3740334/35101858-f3160af8-fc58-11e7-96f7-afe3df76f4b8.png)

**Comment by BobBooth** [comment]
@adgiles - that's it.
I got an email from Ghislain who pointed the same thing out to me.
He said:
"...
Diff between Pro & 10.x, iirc, Pro’s distance tool by default uses geodesic distance, while 10.x default option is planar. 
![image](https://user-images.githubusercontent.com/3801392/35106948-a148ca46-fc3d-11e7-96a0-591d53f97b3c.png)
![image](https://user-images.githubusercontent.com/3801392/35106962-a971ebf8-fc3d-11e7-84c3-969f0a1c65e0.png)
Btw: web merc is a PCS, that looks like this (below), and has meters as units.  It’s a really terrible CS for any kind of analysis.
..."
For Defense/Intel users who will (hopefully) be using custom basemaps in WGS 84 Web Mercator per NGA guidance, this might be less of an issue (probably good for us to test), but we should probably add to the doc suggesting that they reset the measure tool to use Planar measurement mode when measuring local distances. 
@topowright  @dfoll  @csmoore  @ACueva @lfunkhouser

**Comment by BobBooth** [comment]
I think we should also include in the doc a recommendation to set the Environment for the tool to have an Output Coordinate System that is a projected coordinate system appropriate for doing analysis in the intended GRG location.

**Comment by dfoll** [comment]
@BobBooth i like your suggestion. I think for clarity and the ability to understand open issues, this issue should be closed after a new issue is opened as doc enhancement per your immediately previous comment. Also even though this issue is closed i would reference that new issue here, that is created for the doc enhancement.

**Comment by dfoll** [comment]
closing. added closing tag
