### ISSUE TITLE
Create GRG From Point alpha-numeric labels just include the alpha part

### ISSUE THREAD

**Issue by BobBooth** [Esri/solutions-geoprocessing-toolbox#657]
While testing https://github.com/Esri/solutions-geoprocessing-toolbox/issues/585 I encountered a new issue with the labeling of GRG from Point.
If a rotation is applied to the grid, the labels are only getting the Alpha component of the Alpha-Numeric labeling system.
![image](https://user-images.githubusercontent.com/3801392/35697525-79d182e8-0758-11e8-81f0-b6112b8e077d.png)

## Steps to Reproduce (for bugs)
1. Get latest version of tool from the repo.
2. Run the Create GRG from Point tool.
3. Drop a point on the map.
4. Accept all defaults, except add a rotation value.
4. Run the tool.
Cells are labeled with A, B, C, D...  for rows, but not with 1,2,3,4... for columns.
If you do not add a rotation factor the cells are labeled correctly.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by BobBooth** [comment]
It is possible that is is fixed in the unmerged PR here: https://github.com/Esri/solutions-geoprocessing-toolbox/pull/654
@adgiles

**Comment by BobBooth** [comment]
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/f94616ae-8c02-41d9-96ec-127482541adc)

**Comment by BobBooth** [comment]
This also affects the Alpha-Alpha label style.
The Numeric style labels from 1 to 9, then the rest of the cells seem to get 1 values.
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/dc9ad81d-42c0-423e-bcf3-e3e5e1956778)

**Comment by adgiles** [comment]
No the unmerged PR has nothing to do with this. I have had a visual look at the code and can’t see anything obvious to why this would be happening. I will dig a bit deeper tomorrow.

Out of interest is the label getting truncated for alpha-alpha and numeric, and is it also happening in ArcMap?

**Comment by adgiles** [comment]
What is the length of the Grid field?

**Comment by adgiles** [comment]
Strange maybe something going on with joins in Pro

**Comment by adgiles** [comment]
The script was reusing a rotate feature class function that was generic so that it could be used against any feature class. As part of this it used the arcpy.AddJoin_management to map over the existing feature class attributes. This process seemed to cause an issue in Pro.

As we know that there is only one attrribute field to map over (Grid) I have change script to do this in the search cursor and removed the join.

In PR https://github.com/Esri/solutions-geoprocessing-toolbox/pull/658

**Comment by topowright** [comment]
This would work as I would expect it to: 
![image](https://user-images.githubusercontent.com/5488313/35755634-e48b6d3c-081c-11e8-8ef1-3d9bf4dbd5dd.png)
