### ISSUE TITLE
Labels off for rotated, non-square grids created with the Create GRG from Area tool

### ISSUE THREAD

**Issue by BobBooth** [Esri/solutions-geoprocessing-toolbox#660]
Testing Create GRG from Area in ArcMap (10.6.0.8321) and I'm seeing some strange behavior with the labeling of rotated, non-square grids created with the Create GRG from Area tool. 
"A" series starts in the middle of first row, proceeds to edge, then "B" series continues from opposite edge of first row.
![image](https://user-images.githubusercontent.com/3801392/35745689-305003fa-0812-11e8-82fe-8507b0156bd7.png)

## Steps to Reproduce (for bugs)

1. Run Create GRG from Area tool
2. Create an area that is large enough to create a bunch of rows and cols for your cell size, and arrange for it to be rotated relative to the data frame.
3. Set the Cell Width less than the Cell Height (e.g. 55 and 100 meters)
4. Specify an output.
5. Run the tool.

The labeling will be off.

## Your Environment
ArcMap (10.6.0.8321)

**Comment by BobBooth** [comment]
@topowright  - new issue for this problem found while testing https://github.com/Esri/solutions-geoprocessing-toolbox/pull/658
@adgiles

**Comment by adgiles** [comment]
@bbooth hopefully addressed in PR https://github.com/Esri/solutions-geoprocessing-toolbox/pull/661

**Comment by bbooth** [comment]
Wrong bbooth :)

**Comment by adgiles** [comment]
Sorry @bbooth @bobbooth

**Comment by BobBooth** [comment]
@adgiles - I just grabbed the latest copy of Dev and I'm getting an error message related to the polar region check.  Tested in CA.
![image](https://user-images.githubusercontent.com/3801392/35750362-b8227b54-0822-11e8-8d3e-cc957fe5728c.png)

**Comment by adgiles** [comment]
@BobBooth sorry I removed a variable that I thought wasn’t being used try this PR: https://github.com/Esri/solutions-geoprocessing-toolbox/pull/662

**Comment by BobBooth** [comment]
@adgiles  - getting a Python error that verticalCells is referenced before assignment line 413 in GRGFromArea
![image](https://user-images.githubusercontent.com/3801392/35753752-eef9ecbe-082e-11e8-8edc-8bec52af6f8a.png)

**Comment by adgiles** [comment]
Not sure what’s happening here as there should be no polar check in this tool. It looks like files have got merged together some how. Latest PR should hopefully be alright

**Comment by BobBooth** [comment]
https://github.com/Esri/solutions-geoprocessing-toolbox/pull/662 seems to have fixed it.
