### ISSUE TITLE
Horizontal/Vertical inputs are reversed in Create GRG from Point 

### ISSUE THREAD

**Issue by BobBooth** [Esri/solutions-geoprocessing-toolbox#670]
### Tasks
- [ ] Fixes need to be reflected in SGT repo and the MT GP repo

The labels "Number of Horizontal Grid Cells" and "Number of Vertical Grid Cells" on two inputs to the GRG from Point tool are a little confusing.
I entered 33 Horizontal and 10 Vertical cells and ran the tool.
The output had 33 rows of cells in 10 columns. I had expected the reverse.  

![image](https://user-images.githubusercontent.com/3801392/38636214-90e01a6c-3d95-11e8-8461-b289bdf106c1.png)

## Possible Solution
Might consider switching the labels, or changing the labels to say "rows of cells" and "columns of cells".

## Your Environment
ArcGIS ArcMap 10.6

**Comment by lfunkhouser** [comment]
Changed title of issue. The vertical and horizontal cell inputs areare reversed. The behavior is inconsistent with the GRG widget. The widget inputs are: # Horizontal Cells and # Vertical Cells. The grid produced by should be 33 horizontal cells, creating 33 columns and 10 vertical cells, creating 10 rows.

**Comment by BobBooth** [comment]
Switch order of parameters.

**Comment by topowright-zz** [comment]
Addressed for Military Tools GP in the following PR: 
https://github.com/Esri/military-tools-geoprocessing-toolbox/pull/267

Addressed in SGT: 
https://github.com/Esri/solutions-geoprocessing-toolbox/pull/676

**Comment by topowright-zz** [comment]
To close this issue the above two pull requests need to be reviewed and tested. The quickest way to do this would we to have @csmoore show the code to @dfoll on @dfoll s machine and it woudl allow three of us on the team to see the changes that were made. More clarity of our code will help us create a better product in the end.

**Comment by ACueva** [comment]
Refer to code review: https://github.com/Esri/military-tools-geoprocessing-toolbox/pull/267

**Comment by kgonzago** [comment]
The logic for accepting rows and columns inputs is sound. Changed the labels to `Number of Rows` and `Number of Columns` to eliminate confusion. Fix is in this [PR](https://github.com/Esri/military-tools-geoprocessing-toolbox/pull/284)

**Comment by ACueva** [comment]
Verified in ArcMap 10.6 and ArcGIS Pro 2.1.  Row and Columns are correct in ArcMap and ArcGIS Pro.
![2018-05-08_11-42-38](https://user-images.githubusercontent.com/3093940/39776195-f207ee12-52b4-11e8-9e75-53c24a2e12c3.jpg)
![2018-05-08_11-17-55](https://user-images.githubusercontent.com/3093940/39775196-00c210f2-52b2-11e8-8271-b01b6b722f5b.jpg)
