### ISSUE TITLE
Update the scripts for  GRG

### ISSUE THREAD

**Issue by topowright-zz** [Esri/solutions-geoprocessing-toolbox#678]
### Background: 
Currently the geoprocessing tools released inside of Military Tools for ArcGIS 3.0 have updates and bug fixes that have not been updated in this repo

### Current Scenario
We have tools that are managed in multiple locations that are not in sync

### Expected Results
Update the  scripts for GRG updated with the changes made in Military Tools for ArcGIS 3.0

#### GRG Solution
- [x] Update GRG scripts @topowright 
- [x] Change the folder in the repo to GRG from clearing operations @topowright
- [x] Add Number Features tool to GRG Toolbox @topowright
The above fixes are in the PR below
https://github.com/Esri/solutions-geoprocessing-toolbox/pull/679

- [x] Update release notes @dfoll
- [x] update Defense whats new @dfoll
- [x] update homepage @BBooth  @dfoll
- [x] Create CMS topic for release @dfoll
- [x] Update Resources tab structure @dfoll
- [x] Remove WAB tab @dfoll
- [x] ~~Update the try it live update if needed~~ -@acueva
- [x] Add statement about where to find the GRG widget @dfoll
- [x] Verify CMS Workflows updates @team
- [x] Verify Solutions website @team
- [x] Verify the try it live is the most to update widget -@acueva
- [x] Update Jenkins Prod for August 2018

- [x] Verfiy changes in PR
https://github.com/Esri/solutions-geoprocessing-toolbox/pull/679

#### Clearing Ops
Clearing Operations: 
- [x] Create the Final aptx (this is done manually by the team)

- [x] update Defense Whats new for Clearing Ops @Bbooth
- [x] update August 2018 release topic (cms)
- [x] Updates the contents page for Clearing Operations in CMS @Bbooth
- [x] Remove the comments made about the widget in the overview (time and speed) @Bbooth
~~- [ ] Create a topic that would have a generic approach that would be used for settign up all desktop like solutions. @Bbooth~~

**Comment by csmoore** [comment]
Just copying the files from the Military Tools repo seems to work fine, the only end-user difference using these files is the Military Tools version has an extra toolset that was not in the original version so I just wanted to make sure this is OK or this toolset should be removed:

New Version (from Military Tools):

![image](https://user-images.githubusercontent.com/3090809/42828433-8738aa7a-89b6-11e8-868d-ce104cba1d2b.png)

Original Version:

![image](https://user-images.githubusercontent.com/3090809/42828494-9a790f1c-89b6-11e8-939b-4eac9d038db3.png)


Update: the working branch with the changes I made to move over the latest available is at: https://github.com/Esri/solutions-geoprocessing-toolbox/tree/csm/%23678-update-grg-with-latest

**Comment by dfoll** [comment]
can someone clarify what the name convention will be? The screenshot above has "GriddedReferenceGraphicTools.pyt" matching our naming convention from Military Tools, it should be "Gridded Reference Graphic.pyt"

**Comment by ACueva** [comment]
Marking  task "Update the try it live update if needed" completed.  The Try-it-Live (TIL) was originally created on May 15, 2018.  I cross referenced issues that were completed after this TIL was published.  I verified these issues do not occur in our current TIL and that the previously reported bugs are not present.  This tells me the back end code is being updated automatically.
The potential issue Mike Miller was warning us against is if we introduce new functionality and set the functionality to "on" by default.  Existing applications will have this functionality turned on automatically once the push is made.

**Comment by lfunkhouser** [comment]
Updated the original description to cross out the task, "Update the try it live since no work was done." The work was completed in Verify the try it live is the most to update widget. The Try It application did not require an update based on https://github.com/Esri/solutions-geoprocessing-toolbox/issues/678#issuecomment-406351622.

**Comment by ACueva** [comment]
Removed my assignment from:
Verify CMS Workflows updates
Verify Solutions website

These issues cannot be worked on currently as the workflow topics are still in copy editing.  @dfoll has reached out to the doc team and verified the doc team is not waiting on anything from us.

**Comment by BobBooth** [comment]
Have a PR in for the Clearing Operations homepage update:
https://github.com/ArcGIS/arcgis-solutions-website/pull/6753

**Comment by BobBooth** [comment]
Homepage updates complete, once merged. Removing my assignment and moving to Sprint 1.

**Comment by dfoll** [comment]
- There is a task in the issue body to add Number Features to the .pyt, can this be marked off?
- Should the August 2018 release of GRG include text that Number Features is included now? We added that to MT for June, but in the context of GRG, the August release includes it now
- There is a task in the body of this issue to remove Clearing Operations.pyt, if we have the complete toolbox in Military Tools Geoprocessing Toolbox (MTGT), when can we remove Clearing Operations.pyt from SGT?

**Comment by topowright-zz** [comment]
PR #679 addresses the top three issues in the tasks to be done.

**Comment by BobBooth** [comment]
I checked in the two topics I discussed in Scrum under reused-topics.  "Set up Defense solutions" is my second try, and seems to cover most of the cases.  "Set up the solution" was the first try, and only covers a minority of the cases.
@dfoll  @topowright  @ACueva  - feel free to have a look and think about Set up Defense solutions topic as an option.
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/166cb645-9ec7-4e41-bb99-89d84baaf8b5)

**Comment by BobBooth** [comment]
August 2018 release notes page for Clearing Operations on SolutionssDev says:
"...
August 2018 release notes
The Clearing Operations August 2018 release supports the following:

ArcMap 10.3.1-10.6.1
ArcGIS Pro 2.1–2.2
..."
Before I check that task off as done, are we agreed that this is all it needs to say?
@dfoll @topowright @ACueva 
Any note about changing the toolbox name, bug fixes, etc?

**Comment by dfoll** [comment]
my opinion is no bug fixes listed, because we did not make any bug fixes to the clearing operations solution. what I do think we should list is that we now use the GRG toolbox instead of the clearing operations toolbox. @topowright and I were trying to get that work finished but were experiencing some issues we need to continue digging into, before we do that, so the text has not been added yet. my opinion is leave it unchecked and we will check it off when what is happening with the toolbox is sorted out.
