### ISSUE TITLE
Rework Raster Off-road Mobility tool validation

### ISSUE THREAD

**Issue by mfunk** [Esri/solutions-geoprocessing-toolbox#69]
Rework Raster Off-road Mobility tool validation to not hide options as this causes some issues in Pro.
Pro hides tool parameters under certain conditions (parameter disabled, etc.). However in some cases (Raster Off-road Mobility) this throws hidden errors. When this tool comes from GitHub the required parameter tables do not exist (they come with the template, not repo) so the validation throws and error. Because these tables were optional in the dialog they (and the errors) are hidden. In the dialog below the ONLY clue we have that something is wrong is when you click RUN the tool gives a message **"Missing 3 required parameters"**....

![image](https://cloud.githubusercontent.com/assets/3093182/3913606/7513d042-2338-11e4-8fe0-d2791c44a0b2.png)

**Comment by mfunk** [comment]
Fixed this one by adding tooldata to the repo that includes the required tables, and rebuilding the path in tool Validation. @erikreid can you check this out and confirm that the Options on the dialog work?

**Comment by mfunk** [comment]
@erikreid can you confirm this works in your testing for the cell size/web mercator changes?

**Comment by erikreid** [comment]
Tested the tool in ArcMap and it works. In ArcPro, there are still errors:

![arcprorasteroffroadmobilityerrors](https://cloud.githubusercontent.com/assets/8561343/5923286/24c41b86-a607-11e4-9240-05c286801b10.png)

**Comment by csmoore** [comment]
Looks like you can fix the exception in your exception handler while you are at it...

https://github.com/Esri/solutions-geoprocessing-toolbox/blob/master/suitability/toolboxes/scripts/RasterOffRoad.py#L319

**Comment by mfunk** [comment]
@jrweakland @erikreid the original cell size projection issue was fixed separately a week or so ago. This fix is for the exception handler. Please test and close or update as necessary.

**Comment by mfunk** [comment]
Closing as unverified.
