### ISSUE TITLE
test_lowest_point failing in 10.3 Jenkins test

### ISSUE THREAD

**Issue by ACueva** [Esri/solutions-geoprocessing-toolbox#73]
http://vjenk01.esri.com:8080/job/Daily%20Build%20-%20solutions-geoprocessing-toolbox/234/console

test_lowest_point:
     [exec] Starting Test: LowestPoint
     [exec] Creating New Scratch Workspace (Workaround)
     [exec] Valid Object: samplePolygonArea
     [exec] Valid Object: Jbad_SRTM_USGS_EROS
     [exec] Valid Object: Visibility And Range Tools.tbx
     [exec] Running from: C:\Program Files (x86)\Jenkins\workspace\Daily Build - solutions-geoprocessing-toolbox\common\test\test_viz_and_range
     [exec] Geodatabase path: C:\Program Files (x86)\Jenkins\workspace\Daily Build - solutions-geoprocessing-toolbox\common\data\geodatabases
     [exec] Input FeatureClass: C:\Program Files (x86)\Jenkins\workspace\Daily Build - solutions-geoprocessing-toolbox\common\data\geodatabases\test_inputs.gdb\samplePolygonArea
     [exec] Input Feature Count: 1
     [exec] ERROR: Executing: GetCount "C:\Program Files (x86)\Jenkins\workspace\Daily Build - solutions-geoprocessing-toolbox\common\data\geodatabases\test_outputs.gdb\LowestPoint"
     [exec] Start Time: Mon Aug 18 20:40:08 2014
     [exec] Failed to execute. Parameters are not valid.
     [exec] ERROR 000732: Input Rows: Dataset C:\Program Files (x86)\Jenkins\workspace\Daily Build - solutions-geoprocessing-toolbox\common\data\geodatabases\test_outputs.gdb\LowestPoint does not exist or is not supported
     [exec] Failed to execute (GetCount).
     [exec] Failed at Mon Aug 18 20:40:08 2014 (Elapsed Time: 0.00 seconds)

**Comment by jrweakland** [comment]
Added to Asana - https://app.asana.com/0/23179693844547/23186355169309

**Comment by mfunk** [comment]
@ACueva This test seems to be running as of today.. on my local machine of course. Can we verify it is running in Jenkins tests?

```
test_lowest_point:
     [exec] Starting Test: LowestPoint
     [exec] Creating New Scratch Workspace (Workaround)
     [exec] Valid Object: samplePolygonArea
     [exec] Valid Object: Jbad_SRTM_USGS_EROS
     [exec] Valid Object: Visibility And Range Tools_10.3.tbx
     [exec] Running from: C:\Users\matt2542\Documents\GitHub\solutions-geoprocessing-toolbox\visibility\test\test_viz_and_range
     [exec] Geodatabase path: C:\Users\matt2542\Documents\GitHub\solutions-geoprocessing-toolbox\visibility\data\geodatabases
     [exec] Input FeatureClass: C:\Users\matt2542\Documents\GitHub\solutions-geoprocessing-toolbox\visibility\data\geodatabases\test_vis_and_range_inputs.gdb\samplePolygonArea
     [exec] Input Feature Count: 1
     [exec] <string>:1: SyntaxWarning: import * only allowed at module level
     [exec] Output FeatureClass: C:\Users\matt2542\Documents\GitHub\solutions-geoprocessing-toolbox\visibility\data\geodatabases\scratch.gdb\LowestPoint
     [exec] Output Feature Count: 35
     [exec] Deleting Scratch Workspace (Workaround)
     [exec] Test Successful
```

**Comment by mfunk** [comment]
Closing this as unverified.
