### ISSUE TITLE
PointOfOrigin needs test written

### ISSUE THREAD

**Issue by mfunk** [Esri/solutions-geoprocessing-toolbox#80]
PointOfOrigin toolbox needs test written for:
- [ ] Point of Origin Site Detection

**Comment by mfunk** [comment]
Test written during rewrite. posted it today. @jscott11  could you test it out and close this issue if it works?
1. run ```ant``` at *.\solutions-geoprocessing-toolbox* to get the test data
2. ```cd capability\test``` and then 
3. ```ant test_poo_tools```

**Comment by jscott11** [comment]
@mfunk When I run the 'ant test_poo_tools', the build fails. Am I missing something that I need? Let me know if you need the full output.

     [exec] Starting Test: Point of Origin Site Detection
     [exec] ERROR: PYTHON ERRORS:
     [exec] Traceback info:
     [exec]   File "./TestPointOfOrigin.py", line 49, in <module>
     [exec]     results = arcpy.PointOfOriginSiteDetection_ptorigin(inputImpactP
oints, inputWeaponsTable,
     [exec]
     [exec] Error Info:
     [exec] 'module' object has no attribute 'PointOfOriginSiteDetection_ptorigi
n'
     [exec] ERROR: ArcPy ERRORS:
     [exec]
     [exec]
     [exec] PYTHON ERRORS:
     [exec] Traceback info:
     [exec]   File "./TestPointOfOrigin.py", line 49, in <module>
     [exec]     results = arcpy.PointOfOriginSiteDetection_ptorigin(inputImpactP
oints, inputWeaponsTable,
     [exec]
     [exec] Error Info:
     [exec] 'module' object has no attribute 'PointOfOriginSiteDetection_ptorigi
n'
BUILD FAILED
C:\Projects\Templates\solutions-geoprocessing-toolbox\capability\test\build.xml:
22: The following error occurred while executing this line:
C:\Projects\Templates\solutions-geoprocessing-toolbox\capability\test\test_poo_t
ools\build.xml:26: exec returned: -1

**Comment by jscott11** [comment]
@mfunk  It's good, all passed! :+1: (It was just my version of ArcGIS before.)
